<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: DominikS (404), ET (12), etch (6), i7 (754), lubosdz (18), stefanbalaz (15), tomasadamcik (60), zweistein (1)
 */

$sLangName  = 'Slovenčina';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Pozor, dôležité',
'BUTTON_BEGIN_INSTALL' => 'Spustiť inštaláciu',
'BUTTON_DB_INSTALL' => 'Vytvoriť databázu',
'BUTTON_LICENCE' => 'Pokračovať',
'BUTTON_PROCEED_INSTALL' => 'Pokračovať v inštalácii',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Inštalovať demo dáta',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Súhlasím s licenčnými podmienkami.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Nesúhlasím s licenčnými podmienkami.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Neinštalovať</strong> demo dáta',
'BUTTON_START_INSTALL' => 'Reštarovať inštaláciu',
'BUTTON_WRITE_DATA' => 'Uložiť a pokračovať',
'BUTTON_WRITE_LICENCE' => 'Uložiť licenčný kľúč',
'ERROR_BAD_DEMODATA' => 'CHYBA: Nepodarilo sa vykonať nasledovné SQL príkazy:',
'ERROR_BAD_SERIAL_NUMBER' => 'CHYBA: Nesprávny licenčný kľúč!',
'ERROR_BAD_SQL' => 'CHYBA: Nepodarilo sa vykonať nasledovné SQL príkazy:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'Chyba: %s/config.inc.php nemožno zapisovať!',
'ERROR_COULD_NOT_CREATE_DB' => 'Chyba: databázy nie je k dispozícii, a tiež nemôže byť vytvorená!',
'ERROR_COULD_NOT_FIND_FILE' => 'Inštalačný program nemôže nájsť "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Nepodarilo sa načítať súbor %s! Prečítajte si najčastejšie otázky (FAQ), podobné problémy na diskusnom fóre alebo kontaktujte zákaznícku podporu OXID!',
'ERROR_COULD_NOT_READ_FILE' => 'Inštalačný program nemohol otvoriť "%s" pre čítanie!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Inštalačný program nemôže zapisovať do "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'Chyba: Zdá sa, že je už OXID eShop inštalovaný v databáze %s. Prosím, odstráňte ho pred pokračovaním!',
'ERROR_DB_CONNECT' => 'CHYBA: pripojenie k databáze nieje možné!',
'ERROR_FILL_ALL_FIELDS' => 'CHYBA: Vyplňte prosím všetky potrebné políčka!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Verzia MySQL nespĺňa systémové požiadavky',
'ERROR_NOT_AVAILABLE' => 'Chyba: %s nebol nájdený!',
'ERROR_NOT_WRITABLE' => 'Chyba: %s nie je možné zapisovať!',
'ERROR_OPENING_SQL_FILE' => 'CHYBA: Nedá sa otvoriť SQL súbor %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Heslá sa nezhodujú!',
'ERROR_PASSWORD_TOO_SHORT' => 'Heslo je príliš krátke!',
'ERROR_SETUP_CANCELLED' => 'Inštalácia bola zrušená, pretože ste nesúhlasili s licenčnými podmienkami.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Zadajte prosím platnú e-mailovú adresu!',
'ERROR_VIEWS_CANT_CREATE' => 'CHYBA: Nemožno vytvoriť zobrazenie. Skontrolujte si prosím svoje oprávnenia užívateľa databázy.',
'ERROR_VIEWS_CANT_DROP' => 'CHYBA: Nemožno odstrániť pohľady. Skontrolujte si prosím svoje oprávnenia užívateľa databázy.',
'ERROR_VIEWS_CANT_SELECT' => 'CHYBA: Nedá vybrať zo zobrazenia. Skontrolujte si prosím svoje oprávnenia užívateľa databázy.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'Sprievodca inštaláciou OXID eShop',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Ak inštalácia nebude pokračovať automaticky o niekoľko sekúnd, kliknite prosím',
'HERE' => 'sem',
'LOAD_DYN_CONTENT_NOTICE' => '',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen to port 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => '',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'Nahrávanie súborov je povolené (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] vrátane podpory JPEG',
'MOD_INI_SET' => 'ini_set povolené',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite module',
'MOD_MYSQL_CONNECT' => 'MySQL client connector for MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend compatibility mode musí byť vypnutý',
'MOD_PHP_CONFIG' => 'Konfigurácia PHP',
'MOD_PHP_EXTENNSIONS' => 'Rozšírenia PHP',
'MOD_PHP_VERSION' => 'PHP verzia minimálne 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals musí byť vypnuté',
'MOD_REQUEST_URI' => 'REQUEST_URI nastavené',
'MOD_SERVER_CONFIG' => 'Konfigurácia servera',
'MOD_SERVER_PERMISSIONS' => 'Súbory / priečinky prístupové práva',
'MOD_SESSION_AUTOSTART' => 'session.auto_start musí byť vypnutý',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'Podpora UTF-8',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer alebo Zend Guard Loader nainštalovaný',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform alebo Zend Server nainštalovaný',
'PRIVACY_POLICY' => 'ochrana osobných údajov',
'SELECT_DELIVERY_COUNTRY' => 'Hlavná krajina dodania',
'SELECT_DELIVERY_COUNTRY_HINT' => '',
'SELECT_PLEASE_CHOOSE' => 'Prosím vyberte',
'SELECT_SETUP_LANG' => 'jazyk pre inštalačný proces',
'SELECT_SETUP_LANG_SUBMIT' => 'Vybrať',
'SELECT_SHOP_LANG' => 'Jazyk obchodu',
'SELECT_SHOP_LANG_HINT' => 'V prípade potreby je neskôr možné v administrácii e-shopu jednoducho aktivovať ďalšie jazyky.',
'SELECT_SHOP_LOCATION' => 'Váš trh',
'SELECT_SHOP_LOCATION_HINT' => '',
'SETUP_CONFIG_PERMISSIONS' => '',
'SETUP_DIR_DELETE_NOTICE' => '',
'STEP_0_DESC' => '',
'STEP_0_ERROR_TEXT' => 'Váš systém nespĺňa systémové požiadavky',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '',
'STEP_0_TITLE' => '',
'STEP_1_ADDRESS' => 'OXID eSales AG<br> Bertoldstr. 48<br> 79098 Freiburg<br> Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Pravidelne kontrolovať dostupnosť aktualizácií',
'STEP_1_DESC' => 'Víta Vás sprievodca inštaláciou OXID eShopu',
'STEP_1_TEXT' => '',
'STEP_1_TITLE' => 'Vitajte',
'STEP_2_TITLE' => 'Licenčné podmienky',
'STEP_3_1_CREATING_TABLES' => 'Vytváranie tabuliek, vloženie dát ...',
'STEP_3_1_DB_CONNECT_IS_OK' => '',
'STEP_3_1_DB_CREATE_IS_OK' => '',
'STEP_3_1_TITLE' => 'Vytvára sa databáza...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => '',
'STEP_3_2_CREATING_DATA' => '',
'STEP_3_2_TITLE' => '',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => '',
'STEP_3_DB_DATABSE_NAME' => '',
'STEP_3_DB_DEMODATA' => '',
'STEP_3_DB_HOSTNAME' => 'Hostname alebo IP adresa databázového servera',
'STEP_3_DB_PASSWORD' => 'Databázové heslo',
'STEP_3_DB_PASSWORD_SHOW' => 'Zobraziť heslo',
'STEP_3_DB_USER_NAME' => 'Databázové užívateľské meno',
'STEP_3_DESC' => '',
'STEP_3_TITLE' => 'Databáza',
'STEP_3_UTFINFO' => '',
'STEP_3_UTFMODE' => 'Použiť kódovanie UTF-8',
'STEP_3_UTFNOTSUPPORTED' => 'OXID eShop nemôže pracovať v režime UTF-8, pretože:',
'STEP_3_UTFNOTSUPPORTED1' => 'chýba PHP modul mbstring',
'STEP_3_UTFNOTSUPPORTED2' => 'nainštalovaný PCRE nepodporuje UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => '',
'STEP_4_1_TITLE' => '',
'STEP_4_ADMIN_LOGIN_NAME' => 'E-mail administrátora (bude slúžiť ako prihlasovacie meno)',
'STEP_4_ADMIN_PASS' => 'Heslo administrátora',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Potvrdiť heslo administrátora',
'STEP_4_ADMIN_PASS_MINCHARS' => 'ľubovoľné znaky, min. 6 znakov',
'STEP_4_DESC' => '',
'STEP_4_SHOP_DIR' => '',
'STEP_4_SHOP_TMP_DIR' => 'Adresár pre dočasné dáta',
'STEP_4_SHOP_URL' => 'URL adresa eShopu',
'STEP_4_TITLE' => '',
'STEP_5_1_SERIAL_ADDED' => '',
'STEP_5_1_TITLE' => '',
'STEP_5_DESC' => '',
'STEP_5_LICENCE_DESC' => '',
'STEP_5_LICENCE_KEY' => 'Licenčný kľúč',
'STEP_5_TITLE' => 'Licencia OXID eShopu',
'STEP_6_DESC' => 'Váš OXID eShop bol úspešne nainštalovaný.',
'STEP_6_LINK_TO_SHOP' => '',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => '',
'STEP_6_TITLE' => 'OXID eShop úspešne nainštalovaný',
'STEP_6_TO_SHOP' => 'Do eShopu',
'STEP_6_TO_SHOP_ADMIN' => 'Do administrácie eShopu',
'TAB_0_DESC' => 'Kontrolujú sa systémové požiadavky',
'TAB_0_TITLE' => 'Systémové požiadavky',
'TAB_1_DESC' => 'Víta Vás sprievodca inštaláciou OXID eShopu',
'TAB_1_TITLE' => 'Vitajte',
'TAB_2_DESC' => 'Potvrdiť licenčné podmienky',
'TAB_2_TITLE' => 'Licenčné podmienky',
'TAB_3_DESC' => '',
'TAB_3_TITLE' => 'Databáza',
'TAB_4_DESC' => '',
'TAB_4_TITLE' => 'Adresár a prihlásenie',
'TAB_5_DESC' => 'Zadať licenčný klúč',
'TAB_5_TITLE' => 'Licencia',
'TAB_6_DESC' => 'Inštalácia bola úspešne dokončená',
'TAB_6_TITLE' => 'Koniec',
'USE_DYNAMIC_PAGES' => '',
);
