<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: admin (1849), e.mersinlioglu (45), enginistemi (4), esen.baytekin (905), glp_i (120), Justian0 (3), marco (2), McDaim (101), mykibarli (20), scaly (10)
 */

$sLangName  = 'Türkçe';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Mevcut bir beğenilenler listeniz bulunmuyor. Oluşturmak için tıklayınız',
'ADD_RECOMM_ADDRECOMMLINK2' => 'Adres 2',
'allBrands' => 'Tüm markalar',
'byBrand' => 'Markadan',
'byManufacturer' => 'Üretici',
'byVendor' => 'Saticidan',
'DETAILS_ARTNUMBER' => 'Ürün no.:',
'DETAILS_CHOOSEVARIANT' => 'Lütfen bir biçim seciniz',
'DETAILS_LOCATOR_PRODUCT' => 'Produkt',
'DETAILS_PLUSSHIPPING2' => 'Kargo maliyetleri',
'DETAILS_PRICEALARM' => 'Fiyat Alarm',
'DETAILS_VPE_MESSAGE_1' => 'Bu ürün sadece',
'DETAILS_VPE_MESSAGE_2' => 'adetlik birimlerde sipariş edilebillir.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'An invitation from',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'to visit',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'to visit.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Ürün no.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NONE',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Ödeme Ücreti KDV',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Ödeme yapılacağı biçim:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'artı KDV',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'artı KDV',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'ile sevk edilecektir',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Kargo ücreti (KDV\'siz):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'artı vergi',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => '+ KDV',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Bildiri:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>ÖDEME BİLGİLERİ KAPALI</b> - Açmak için, application/views/[theme]/email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Sipariş etmiş olduğunuz dosyaları buradan indirebilirsiniz.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Merhaba',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Siparişin ödemesi henüz tamamlanmamıştır.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'İndirme linkleri',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Ürün no.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Sipariş no.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'Sipariş buraya gönderilecek:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Ürün',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Ürünü değerlendir',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'yorum',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Paket takibi için linkiniz:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'buraya tıklayınız',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Mağazamızı değerlendirmek için bir kaç dakikanızı ayırın.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Sizin',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Takım',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stoklar düşük',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Selamlar,',
'FOOTER_CATEGORIES' => 'KATEGORILER',
'FOOTER_DISTRIBUTORS' => 'DISTRIBUTORLER',
'FOOTER_INFORMATION' => 'BİLGİLENDİRME',
'FOOTER_MANUFACTURERS' => 'MARKALAR',
'FOOTER_SERVICES' => 'HİZMET',
'FORM_CONTACT_SEND' => 'Şifre gönder',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Şifreyi tekrarlayın:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Şifrenizi mi unuttunuz?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Ad',
'FORM_PRICEALARM_SEND' => 'Gönder',
'FORM_PRIVATESALES_INVITE_FROM' => 'Kimden:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Hello, I was looking at',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'today and found something that might be interesting for you. Just click on the link below and you will be directed to the shop.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Davetiye gönder',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Sender\'s password: ',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Headline',
'FORM_REGISTER_BILLINGADDRESS' => 'Fatura adresi',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Lütfen kalın olarak yazılmış tüm zorunlu alanları doldurunuz.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'I have been informed about my',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informed.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Kabul ediyorum',
'FORM_REGISTER_IAGREETOTERMS3' => 'Okudum, kabul ediyorum.',
'FORM_SUGGEST_MESSAGE1' => 'Hello, I was looking at',
'FORM_SUGGEST_MESSAGE2' => 'bugün ilgini çekebilecek bir şey buldum. Aşağıdaki linke tıkla, mağazaya yönlendirileceksin.',
'FORM_USER_BILLINGADDRESS' => 'Fatura adresi',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Şifreyi tekrarlayın:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Şimdi ara',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hi, I created a Gift Registry at',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Great if you could buy something for me.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Gönderme sırasında hata - e-posta adresinizi kontrol ediniz.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Tablo',
'infogrid' => 'Tablo Ayrıntılı',
'line' => 'Liste',
'NEWSLETTER_COMPLETEALLFIELEDS' => '"*" ile işaretli tüm alanları doldurunuz!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'ÇIKIŞ',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Yeni şifreyi kaydet',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Yeni hesap açın',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Fatura ve kargo ayarları',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Hediye kaydınız adrese başarıyla gönderildi:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'dispatched!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Ürün numarası',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Kuponunuz',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'reddedilmiştir.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Alt toplam',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Surcharge VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => '+ KDV',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reason',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => '+ vergi',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Alt toplam',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Ürünlerin toplamı (KDV Dahil)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Ürünlerin toplamı (KDV Hariç)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => '+ vergi',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => '+ vergi',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Mesajınız:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Fatura adresi',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Kuponunuz',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'reddedilmiştir.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Teslimat adresi',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Banka hesap numarası:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'lütfen zorunlu tüm alanları doldurun!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Şu anda bu ülke için ayarlanmış bir teslimat yöntemi bulunmuyor.</p> <p>Olası bir dağıtım yöntemi bulmayı hedefliyoruz. Teslimat maliyetleri hakkında bilgi e-posta yoluyla en kısa sürede size iletilecektir.</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'KDV Dahil',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'ek',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'COD Charge',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'The Trusted Shops buyer protection secures your online purchase. I agree with the transfer and',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'kazancınız',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'of my e-mail address for the buyer protection handling by Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Koşullar',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'for the buyer protection.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Siparişiniz kaydedilmiştir. Sipariş Numaranız:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Siparişiniz için teşekkür ederiz',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'in',
'PAGE_CHECKOUT_USER' => 'Dispatch',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Kayıtlı kullanıcı olursanız aşağıdaki avantajlardan yararlanabilirsiniz:<br> - Adres yönetimi<br> - Sipariş durumu kontrolü<br> - Sipariş Geçmişi<br> - Kişisel istek listesi <br> - Kişisel Hediye Kaydı<br> - Haber Bülteni Aboneliği<br> - Özel teklifler ve indirimler',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'İptal',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NONE',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Teşekkür ederiz.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'Yorumlarınızı değerlendireceğiz.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'We will inform you as soon as the price falls below',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Çerezler (Cookies) hakkında',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Teşekkür ederiz.',
'PAGE_INFO_CONTACT_THANKYOU2' => ' appreciates your comments.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'News from',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Bu ürünler istek listesinde',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Eğer onu memnun etmek istiyorsanız, bu ürünlerin bir veya bir kaçını satın alın.',
'searchResult' => '"%s" için arama sonuçları.',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'User will be registered after he provided his password',
'view' => 'Görünüm',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Diğer...',
'WIDGET_LOGINBOX_LOGIN' => 'Giriş',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Ürün detayı',
'WIDGET_SERVICES_GUESTBOOK' => 'Ziyaretçi Defteri',
'WIDGET_SERVICES_HOME' => 'Home',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Daha fazla bilgi',
);
