<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: asot (45), pianoservis (2816)
 */

$sLangName  = 'Українська';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Увага, важливо',
'BUTTON_BEGIN_INSTALL' => 'Розпочати установку',
'BUTTON_DB_INSTALL' => 'Створити базу даних зараз.',
'BUTTON_LICENCE' => 'Далі',
'BUTTON_PROCEED_INSTALL' => 'Розпочати установку',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Встановити демо-дані',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Я приймаю умови ліцензійної угоди.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Я не приймаю умови ліцензійної угоди.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong> Не </ strong> встановлювати демо-дані',
'BUTTON_START_INSTALL' => 'Почати установку знову',
'BUTTON_WRITE_DATA' => 'Зберегти базу даних зараз',
'BUTTON_WRITE_LICENCE' => 'Зберегти ліцензійний ключ',
'ERROR_BAD_DEMODATA' => 'ПОМИЛКА: проблема з наступною SQL-командою:',
'ERROR_BAD_SERIAL_NUMBER' => 'ПОМИЛКА: серійний номер невірний!',
'ERROR_BAD_SQL' => 'ПОМИЛКА: (таблиці) проблеми з наступними SQL-командами:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ПОМИЛКА: %s/config.inc.php неможливо редагувати!',
'ERROR_COULD_NOT_CREATE_DB' => 'ПОМИЛКА: база даних %s не існує, також її неможливо створити!',
'ERROR_COULD_NOT_FIND_FILE' => 'Установник не зміг знайти файл "%s"',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Неможливо відкрити config.inc.php. Будь ласка, прочитайте FAQ або форум або зв\'яжіться зі службою підтримки OXID.',
'ERROR_COULD_NOT_READ_FILE' => 'Установник не зміг відкрити файл "%s"!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Установник не зміг відредагувати файл "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ПОМИЛКА: можливо в базі даних вже існує база даних OXID. Будь ласка, видаліть її.',
'ERROR_DB_CONNECT' => 'ПОМИЛКА: неможливо з\'єднатися з базою даних!',
'ERROR_FILL_ALL_FIELDS' => 'ПОМИЛКА: будь ласка, заповніть всі обов\'язкові поля!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Версія MySQL не відповідає системним вимогам.',
'ERROR_NOT_AVAILABLE' => 'ПОМИЛКА: %s не існує!',
'ERROR_NOT_WRITABLE' => 'ПОМИЛКА: %s неможливо редагувати!',
'ERROR_OPENING_SQL_FILE' => 'ПОМИЛКА: неможливо відкрити SQL-файл %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Паролі не збігаються',
'ERROR_PASSWORD_TOO_SHORT' => 'Пароль занадто короткий',
'ERROR_SETUP_CANCELLED' => 'Установка перервана, так як Ви не погодилися з умовами ліцензійної угоди.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Будь ласка, вкажіть існуючий e-mail!',
'ERROR_VIEWS_CANT_CREATE' => 'ПОМИЛКА: неможливо створити Views. Будь ласка, перевірте Ваші права користувача для бази даних.',
'ERROR_VIEWS_CANT_DROP' => 'ПОМИЛКА: неможливо створити Views. Будь ласка, перевірте Ваші права користувача для бази даних.',
'ERROR_VIEWS_CANT_SELECT' => 'ПОМИЛКА: неможливо створити Views. Будь ласка, перевірте Ваші права користувача для бази даних.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop Майстер установки',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Якщо установка не почнеться через кілька секунд, будь ласка натисніть',
'HERE' => 'тут',
'LOAD_DYN_CONTENT_NOTICE' => 'Якщо прапорець встановлений, ви побачите додаткове меню в адмінці вашого OXID eShop. </ Р> <р> У цьому меню ви отримаєте додаткову інформацію про сервіси електронної комерції , такі як "Google пошук товару." </ Р> <р> Ви можете змінити ці налаштування в будь-який час.',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen to port 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Можливі проблеми на сервері через помилки PHP',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'Завантаження файлів включено (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] вкл. підтримку JPEG',
'MOD_INI_SET' => 'ini_set дозволено',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Модуль mod_rewrite Apache',
'MOD_MYSQL_CONNECT' => 'Клієнт конектор MySQL для MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Режим сумісності Zend має бути вимкнений',
'MOD_PHP_CONFIG' => 'Конфігурація PHP',
'MOD_PHP_EXTENNSIONS' => 'Розширення PHP',
'MOD_PHP_VERSION' => 'PHP як мінімум версії 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals має бути вимкнений',
'MOD_REQUEST_URI' => 'REQUEST_URI набор',
'MOD_SERVER_CONFIG' => 'Конфігурація сервера',
'MOD_SERVER_PERMISSIONS' => 'Файли / папки права доступу',
'MOD_SESSION_AUTOSTART' => 'session.auto_start має бути вимкнений',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Токенізатор',
'MOD_UNICODE_SUPPORT' => 'UTF-8 підтримка',
'MOD_ZEND_OPTIMIZER' => 'Встановлено Zend Optimizer або Zend Guard Loader',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Встановлено Zend Platform або Zend Server',
'PRIVACY_POLICY' => 'Заява про конфіденційність',
'SELECT_DELIVERY_COUNTRY' => 'Головна країна доставки',
'SELECT_DELIVERY_COUNTRY_HINT' => 'При необхідності, включіть більше країн доставки в адмін панелі.',
'SELECT_PLEASE_CHOOSE' => 'Виберіть, будь ласка',
'SELECT_SETUP_LANG' => 'Мова для установки',
'SELECT_SETUP_LANG_SUBMIT' => 'Виберіть',
'SELECT_SHOP_LANG' => 'Мова магазину',
'SELECT_SHOP_LANG_HINT' => 'При необхідності, включіть більше мов в адмін.',
'SELECT_SHOP_LOCATION' => 'Ваш ринок',
'SELECT_SHOP_LOCATION_HINT' => 'Будь ласка, виберіть ринок, на який зосереджений магазин. Відповідно до цього, додаткові Послуги  електронної комерції будуть завантажені з сервера OXID, якщо ви дозволите на це.',
'SETUP_CONFIG_PERMISSIONS' => 'З міркувань безпеки переведіть config.inc.php файл в режим "тільки для читання"!',
'SETUP_DIR_DELETE_NOTICE' => 'З міркувань безпеки видаліть каталог установки, якщо це ще не зроблено в процесі установки.',
'STEP_0_DESC' => 'На цьому етапі ми перевіряємо, чи відповідає Ваша система вимогам:',
'STEP_0_ERROR_TEXT' => 'Ваша система не підходить під системні вимоги',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Ваша система відповідає вимогам</li><li class="pmin"> - Вимога не є, або тільки частково підходить. Купити Інтернет буде працювати в будь-якому випадку, і може бути встановлений ..</li><li class="fail"> - Ваша система не відповідає вимогам Купити Інтернет не буде працювати без нього і не може бути встановлена.</li><li class="null"> - Вимогу не можливо перевірити</ul>',
'STEP_0_TITLE' => 'Перевірити Системні вимоги',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Перевіряти наявність оновлень регулярно',
'STEP_1_DESC' => 'Ласкаво просимо в майстер установки OXID eShop',
'STEP_1_TEXT' => 'Будь ласка, уважно прочитайте наступні інструкції, щоб гарантувати легку установку.',
'STEP_1_TITLE' => 'Ласкаво просимо',
'STEP_2_TITLE' => 'Ліцензійні умови',
'STEP_3_1_CREATING_TABLES' => 'Створення таблиць, застосовуючи дані ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Підключення до бази даних успішно протестовано ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'База даних %s успішно створена ...',
'STEP_3_1_TITLE' => 'База даних - створюється ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Якщо ви хочете, щоб переписати всі існуючі дані і встановіти натисніть кнопку',
'STEP_3_2_CREATING_DATA' => 'База даних успішно створена. Будь ласка, зачекайте ...',
'STEP_3_2_TITLE' => 'Створюються таблиці баз даних ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'Якщо база даних не існує, вона буде створена',
'STEP_3_DB_DATABSE_NAME' => 'Ім\'я бази даних',
'STEP_3_DB_DEMODATA' => 'Демо дані',
'STEP_3_DB_HOSTNAME' => 'Ім\'я хоста бази даних або IP',
'STEP_3_DB_PASSWORD' => 'Пароль бази даних',
'STEP_3_DB_PASSWORD_SHOW' => 'Показати поароль',
'STEP_3_DB_USER_NAME' => 'Користувач бази даних',
'STEP_3_DESC' => 'Буде створено Базу даних  і необхідні таблиці. Будь ласка, надайте інформацію:',
'STEP_3_TITLE' => 'База даних',
'STEP_3_UTFINFO' => 'UTF-8 кодування забезпечує кращу підтримку для спеціальних символів, ніж інші кодування. Це особливо важливо для багатомовних eShops. Тим не менш, кодування UTF-8 трохи повільніше, ніж стандарт кодування (ІСО 8859-15). <br /> Якщо ви плануєте, використовувати в Вашому Інтернет-магазині різні мови, Ви повинні використовувати UTF-8. Якщо Ви просто хочете, щоб забезпечити кілька мов, використовуючи відповідні набори символів (наприклад, англійська, німецька, французька), Вам не потрібно UTF-8.',
'STEP_3_UTFMODE' => 'Використовуйте кодування символів UTF-8',
'STEP_3_UTFNOTSUPPORTED' => 'OXID eShop не може працювати в UTF-8 режимі, у зв\'язку з:',
'STEP_3_UTFNOTSUPPORTED1' => 'Відсутній модуль PHP MBstring',
'STEP_3_UTFNOTSUPPORTED2' => 'Встановлений PCRE не підтримує UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Перевірка та запис даних успішні. Будь ласка, зачекайте ...',
'STEP_4_1_TITLE' => 'Каталог - створюється ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'e-mail Адміністраторв (використовується в якості логіна)',
'STEP_4_ADMIN_PASS' => 'Пароль адміністратора',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Підтвердіть пароль адміністратора',
'STEP_4_ADMIN_PASS_MINCHARS' => 'вільний вибір, мін. 6 символів',
'STEP_4_DESC' => 'Будь ласка, надайте необхідні дані для запуску OXID eShop:',
'STEP_4_SHOP_DIR' => 'Каталог для OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Каталог для тимчасових даних',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Налаштування інтернет-магазину OXID eShop',
'STEP_5_1_SERIAL_ADDED' => 'Ліцензійний ключ успішно збережений! <br> Зачекайте будь ласка ...',
'STEP_5_1_TITLE' => 'Ліцензійний ключ - працює ...',
'STEP_5_DESC' => 'Будь ласка, введіть ліцензійний ключ для OXID eShop:',
'STEP_5_LICENCE_DESC' => 'Наданий ключ дійсний протягом 30 днів. Після цього періоду всі зміни залишаються якщо вставити діючий ліцензійний ключ.',
'STEP_5_LICENCE_KEY' => 'Ліцензійний ключ',
'STEP_5_TITLE' => 'OXID eShop ліцензія',
'STEP_6_DESC' => 'OXID eShop успішно встановлений',
'STEP_6_LINK_TO_SHOP' => 'Доступ к Ваш магазин',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Доступ до Вашої адміністрації магазину',
'STEP_6_TITLE' => 'OXID eShop успішно встановлений',
'STEP_6_TO_SHOP' => 'До магазину',
'STEP_6_TO_SHOP_ADMIN' => 'До адміністрації магазину',
'TAB_0_DESC' => 'Перевірка, чи Ваша система відповідає вимогам',
'TAB_0_TITLE' => 'Технічні передумови',
'TAB_1_DESC' => 'Ласкаво просимо в майстер установки OXID eShop',
'TAB_1_TITLE' => 'Привіт!',
'TAB_2_DESC' => 'Підтвердіть ліцензійні умови',
'TAB_2_TITLE' => 'Ліцензійні умови',
'TAB_3_DESC' => 'Перевірка з\'єднання бази даних, побудова таблиць',
'TAB_3_TITLE' => 'База даних',
'TAB_4_DESC' => 'Налаштування каталогів і вибору логін адміністратора',
'TAB_4_TITLE' => 'Каталог та вхід',
'TAB_5_DESC' => 'Застосуйте ліцензійний ключ',
'TAB_5_TITLE' => 'Ліцензіч',
'TAB_6_DESC' => 'Установка пройшла успішно',
'TAB_6_TITLE' => 'Фініш',
'USE_DYNAMIC_PAGES' => 'Для збільшення успіху для вашого бізнесу отримайте додаткову інформацію з сервера Oxid в. Додаткову інформацію Ви знайдете в наших',
);
