<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: alexraimondo (1), Alpha-Sys (5), chatard (318), cowboy9571 (10), ET (10), ftn2018 (236), marco (7), patmat2809 (5), Phenix (203), piccobello (1), Rainbow40 (2), rava3000 (8), vikapera (376)
 */

$sLangName  = 'Français';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Attention, important',
'BUTTON_BEGIN_INSTALL' => 'Démarrer l\'installation',
'BUTTON_DB_INSTALL' => 'Créer la base de données maintenant',
'BUTTON_LICENCE' => 'Continuer',
'BUTTON_PROCEED_INSTALL' => 'Lancer l\'installation',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Installer le jeu de données de démonstration',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'J\'accepte les conditions de licence.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Je refuse les conditions de licence.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => 'Ne <strong>pas</strong> installer le jeu de données de démonstration',
'BUTTON_START_INSTALL' => 'Relancer l\'installation',
'BUTTON_WRITE_DATA' => 'Enregistrer et continuer',
'BUTTON_WRITE_LICENCE' => 'Enregister la clé de licence',
'ERROR_BAD_DEMODATA' => 'ERREUR: Problème rencontré lors de l\'exécution de la requête SQL suivante:',
'ERROR_BAD_SERIAL_NUMBER' => 'Erreur : Mauvaise clé de licence !',
'ERROR_BAD_SQL' => 'ERREUR: Problème rencontré lors de l\'exécution de la requête SQL suivante:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ERREUR: %s/config.inc.php est en lecture seule!',
'ERROR_COULD_NOT_CREATE_DB' => 'ERREUR: La base de données n\'est pas disponible et ne peut pas être créée!',
'ERROR_COULD_NOT_FIND_FILE' => 'La procédure d\'installation n\'à pas pu trouver "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Impossible d\'ouvrir %s en lecture! Merci de consulter nos FAQ, forum ou bien contactez l\'équipe de support OXID!',
'ERROR_COULD_NOT_READ_FILE' => 'Impossible d\'ouvrir "%s" en lecture!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Impossible d\'écrire dans "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ERREUR: Il semble qu\'une base de données OXID eShop existe déjà : %s. Merci de la supprimer avant de continuer!',
'ERROR_DB_CONNECT' => 'ERREUR: Aucune connexion possible à la Base de données!',
'ERROR_FILL_ALL_FIELDS' => 'ERREUR: Merci de renseigner tous les champs nécessaires!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Le version de MySQL ne satisfait pas les pré-requis',
'ERROR_NOT_AVAILABLE' => 'ERREUR: %s n\'a pas été trouvé!',
'ERROR_NOT_WRITABLE' => 'ERREUR: %s est en lecture seule!',
'ERROR_OPENING_SQL_FILE' => 'ERREUR: Impossible d\'ouvrir le fichier SQL %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Les mots de passe ne correspondent pas.',
'ERROR_PASSWORD_TOO_SHORT' => 'Le mot de passe est trop court !',
'ERROR_SETUP_CANCELLED' => 'La procédure d\'installation à été annulée car vous n\'avez pas accepté les conditions de licence.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Merci de renseigner une adresse e-mail valide !',
'ERROR_VIEWS_CANT_CREATE' => 'ERREUR: Impossible de créer des vues. Veuillez vérifier les privilèges de l\'utilisateur sur la base de données.',
'ERROR_VIEWS_CANT_DROP' => 'ERREUR: Impossible de supprimer des vues. Veuillez vérifier les privilèges de l\'utilisateur sur la base de données.',
'ERROR_VIEWS_CANT_SELECT' => 'ERREUR: Impossible d\'accéder aux vues. Veuillez vérifier les privilèges de l\'utilisateur sur la base de données.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'Assistant d\'installation OXID eShop',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Si la procédure d\'installation ne démarre pas sous quelques secondes, cliquez',
'HERE' => 'ici',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Si cette case est cochée, vous aurez accès à un menu additionnel dans le back-office de votre boutique.</p><p>Dans ce menu, vous accéderez à des informations relatives à des services eCommerce comme Google...</p> <p>Vous avez la possibilité de modifier ces paramètres à tout moment.</p>',
'MOD_ALLOW_URL_FOPEN' => 'Le module allow_url_fopen ou fsockopen doit utiliser le port 80',
'MOD_BC_MATH' => 'Module BCMath',
'MOD_BUG53632' => 'Des erreurs peuvent survenir sur votre serveur à cause de bugs PHP',
'MOD_CURL' => 'Module cURL',
'MOD_FILE_UPLOADS' => 'Envoi de fichiers activé (file_uploads)',
'MOD_GD_INFO' => 'Module GDlib v2 [v1] incl. support du format JPEG',
'MOD_INI_SET' => 'Module ini_set autorisé',
'MOD_I_CONV' => 'Module ICONV',
'MOD_J_SON' => 'Module JSON',
'MOD_LIB_XML2' => 'Module LIB XML2',
'MOD_MB_STRING' => 'Module mbstring',
'MOD_MOD_REWRITE' => 'Module apache mod_rewrite',
'MOD_MYSQL_CONNECT' => 'Module MySQL pour MySQL 5',
'MOD_OPEN_SSL' => 'Module OpenSSL',
'MOD_PHP4_COMPAT' => 'La compatibilité Zend doit être off',
'MOD_PHP_CONFIG' => 'Configuration PHP',
'MOD_PHP_EXTENNSIONS' => 'Extensions PHP',
'MOD_PHP_VERSION' => 'La version de PHP minimale est 5.2.0',
'MOD_PHP_XML' => 'Module DOM',
'MOD_REGISTER_GLOBALS' => 'Le module register_globals doit être off',
'MOD_REQUEST_URI' => 'Le module REQUEST_URI est activé',
'MOD_SERVER_CONFIG' => 'Configuration Serveur',
'MOD_SERVER_PERMISSIONS' => 'Droits d\'accès sur les répertoires/fichiers',
'MOD_SESSION_AUTOSTART' => 'session.auto_start doit être positionné en off',
'MOD_SOAP' => 'Module SOAP',
'MOD_TOKENIZER' => 'Module Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 supporté',
'MOD_ZEND_OPTIMIZER' => 'Module Zend Optimizer ou Zend Guard Loader installé',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Module Zend Platform ou Zend Server installé',
'PRIVACY_POLICY' => 'déclaration de confidentialité',
'SELECT_DELIVERY_COUNTRY' => 'Pays de livraison par défaut',
'SELECT_DELIVERY_COUNTRY_HINT' => 'Si nécessaire, vous pouvez activer d\'autres pays de destination dans le back-office.',
'SELECT_PLEASE_CHOOSE' => 'Veuillez choisir',
'SELECT_SETUP_LANG' => 'Veuillez choisir une langue',
'SELECT_SETUP_LANG_SUBMIT' => 'Selectionner',
'SELECT_SHOP_LANG' => 'Langue de la boutique',
'SELECT_SHOP_LANG_HINT' => 'Si besoin, activez facilement plus de langues dans l\'administration.',
'SELECT_SHOP_LOCATION' => 'Votre magasin',
'SELECT_SHOP_LOCATION_HINT' => 'S\'il vous plaît, choisissez l\'activité autour de laquelle la boutique se concentre. En fonction de cela des services complémentaires seront chargés à partir du serveur OXID si vous êtes d\'accord.',
'SETUP_CONFIG_PERMISSIONS' => 'Pour des raisons de sécurité, veuillez modifier les propriétés du fichier config.inc.php en lecture seule!',
'SETUP_DIR_DELETE_NOTICE' => 'Pour des raisons de sécurité, veuillez supprimer le répertoire \'setup\' s\'il n\'avait pas été supprimé durant le processus d\'installation.',
'STEP_0_DESC' => 'Cette étape permet de vérifier si votre système est conforme aux conditions requises:',
'STEP_0_ERROR_TEXT' => 'Votre système ne satisfait pas les pré-requis techniques.',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Votre système satisfait aux conditions requises.</li><li class="pmin"> - Les conditions requises ne sont pas pleinement satisfaites. OXID eShop pourra cependant fonctionner et peut être installé..</li><li class="fail"> - Votre système ne satisfait pas au conditions requises. OXID eShop ne peut fonctionner dans ces conditions et ne peut être installé dans l\'état.</li><li class="null"> - Les conditions requises n\'ont pas pu être vérifiées.</ul>',
'STEP_0_TITLE' => 'Vérification de la configuration',
'STEP_1_ADDRESS' => 'OXID eSales France<br>',
'STEP_1_CHECK_UPDATES' => 'Vérifiez la présence de mise à jour régulièrement',
'STEP_1_DESC' => 'Bienvenue dans l\'assistant d\'installation d\'OXID eShop',
'STEP_1_TEXT' => 'Merci de lire attentivement les instructions ci-après afin de garantir une installation sans encombres.
                                                      Nous vous souhaitons le plus grand succès dans l\'utilisation d\'OXID eShop',
'STEP_1_TITLE' => 'Bienvenue',
'STEP_2_TITLE' => 'Conditions de licence',
'STEP_3_1_CREATING_TABLES' => 'Création des tables ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Test de connexion à la base de données effectué ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'La base de données %s à bien été créée ...',
'STEP_3_1_TITLE' => 'Base de données - En cours de création ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Si vous souhaitez continuer et écraser vos données existantes cliquez',
'STEP_3_2_CREATING_DATA' => 'La base de données à bien été créée. Merci de patienter ...',
'STEP_3_2_TITLE' => 'Base de données - Tables en cours de création ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'Si la base de données n\'esiste pas, elle sera créée',
'STEP_3_DB_DATABSE_NAME' => 'Nom de la base de données',
'STEP_3_DB_DEMODATA' => 'Jeu de données de démonstration',
'STEP_3_DB_HOSTNAME' => 'Nom d\'hôte ou adresse IP du serveur de base de données',
'STEP_3_DB_PASSWORD' => 'Mot de passe du serveur de bases de données',
'STEP_3_DB_PASSWORD_SHOW' => 'Afficher le mot de passe',
'STEP_3_DB_USER_NAME' => 'Nom d\'utilisateur du serveur de bases de données',
'STEP_3_DESC' => 'La base de données va être créée ainsi que les tables nécessaires. Merci de renseigner les information suivantes:',
'STEP_3_TITLE' => 'Base de données',
'STEP_3_UTFINFO' => 'L\'encodage UTF-8 procure un meilleur support des caractères spéciaux que les autres encodages. Ce point est particulièrement important pour les boutiques multilingue. Cependant, UTF-8 est légèrement plus lent que les encodages standard (ISO 8859-15). <br /> Si vous prévoyez de proposer votre boutiques dans plusieurs langues, vous devriez utiliser UTF-8. Si vous souhaitez proposer seulement quelques langues utilisant le même alphabet (ex: English, German, French), UTF-8 n\'est pas nécessaire.',
'STEP_3_UTFMODE' => 'Utiliser l\'encodage UTF-8',
'STEP_3_UTFNOTSUPPORTED' => 'OXID eShop ne peut fonctionner en mode UTF-8, pour les raisons suivantes:',
'STEP_3_UTFNOTSUPPORTED1' => 'Le module PHP mbstring est absent',
'STEP_3_UTFNOTSUPPORTED2' => 'Le module PCRE installé ne supporte pas UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Insertion et vérification des données. Merci de patienter ...',
'STEP_4_1_TITLE' => 'Répertoires - en cours de création ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Adresse e-mail de l\'administrateur (Utilisée comme login)',
'STEP_4_ADMIN_PASS' => 'Mot de passe pour l\'administrateur',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Confirmer le mot de passe pour l\'administrateur',
'STEP_4_ADMIN_PASS_MINCHARS' => '6 caractères minimum',
'STEP_4_DESC' => 'Merci de renseigner les données nécessaires au bon fonctionnement d\'OXID eShop:',
'STEP_4_SHOP_DIR' => 'Répertoire d\'OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Répertoire pour les données temporaires',
'STEP_4_SHOP_URL' => 'Adresse URL de la boutique OXID eShop',
'STEP_4_TITLE' => 'Configuration des dossiers et URL d\'OXID eShop',
'STEP_5_1_SERIAL_ADDED' => 'La clé de licence est sauvegardée. Merci de patienter ...',
'STEP_5_1_TITLE' => 'La clé de licence est en cours de sauvegarde ...',
'STEP_5_DESC' => 'Merci de confirmer votre clé de licence:',
'STEP_5_LICENCE_DESC' => 'La clé fournie est valide pour une durée de 30 jours. Après cette période l\'intégralité de vos modifications seront conservées si vous insérez une clé de licence valide.',
'STEP_5_LICENCE_KEY' => 'Clé de licence',
'STEP_5_TITLE' => 'Licence OXID eShop',
'STEP_6_DESC' => 'Votre boutique OXID eShop a été installée avec succès.',
'STEP_6_LINK_TO_SHOP' => 'Accéder à votre boutique OXID eShop',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Accéder à l\'administration de votre boutique OXID eShop',
'STEP_6_TITLE' => 'OXID eShop a été installé avec succès',
'STEP_6_TO_SHOP' => 'A la boutique',
'STEP_6_TO_SHOP_ADMIN' => 'A l\'administration de la boutique',
'TAB_0_DESC' => 'Vérification de la conformité de votre configuration',
'TAB_0_TITLE' => 'Configuration requise',
'TAB_1_DESC' => 'Bienvenue dans l\'assistant d\'installation d\'OXID eShop',
'TAB_1_TITLE' => 'Bienvenue',
'TAB_2_DESC' => 'Veuillez confirmer les conditions de licence',
'TAB_2_TITLE' => 'Conditions de licence',
'TAB_3_DESC' => 'Test de connexion à la base de données, création des tables',
'TAB_3_TITLE' => 'Base de données',
'TAB_4_DESC' => 'Configuration des répertoires et définition du compte administrateur',
'TAB_4_TITLE' => 'Répertoire & connexion',
'TAB_5_DESC' => 'Appliquer la clé de licence',
'TAB_5_TITLE' => 'Licence',
'TAB_6_DESC' => 'Installation effectuée avec succès',
'TAB_6_TITLE' => 'Terminée',
'USE_DYNAMIC_PAGES' => 'Afin d\'augmenter votre réussite des information supplementaires sont disponibles sur les serveurs d\'OXID. Vous trouverez davantage d\'information dans',
);
