<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: AWIDON (752), buby (118), KonopArt (1), ondrej123 (327)
 */

$sLangName  = 'Hrvatski';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Pozor, važno',
'BUTTON_BEGIN_INSTALL' => 'Pokreni instalaciju',
'BUTTON_DB_INSTALL' => 'Kreiraj databazu',
'BUTTON_LICENCE' => 'Nastaviti',
'BUTTON_PROCEED_INSTALL' => 'Započmi instalaciju',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Instaliraj demodata',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Suglasan sam sa licencom',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Ne suglasim sa licencom',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Ne</strong>instalirati demodata',
'BUTTON_START_INSTALL' => 'Pokreni setup ponovo',
'BUTTON_WRITE_DATA' => 'Spremiti i nastaviti',
'BUTTON_WRITE_LICENCE' => 'Spremi licencijski ključ',
'ERROR_BAD_DEMODATA' => '',
'ERROR_BAD_SERIAL_NUMBER' => '',
'ERROR_BAD_SQL' => '',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => '',
'ERROR_COULD_NOT_CREATE_DB' => '',
'ERROR_COULD_NOT_FIND_FILE' => '',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => '',
'ERROR_COULD_NOT_READ_FILE' => '',
'ERROR_COULD_NOT_WRITE_TO_FILE' => '',
'ERROR_DB_ALREADY_EXISTS' => '',
'ERROR_DB_CONNECT' => '',
'ERROR_FILL_ALL_FIELDS' => '',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => '',
'ERROR_NOT_AVAILABLE' => '',
'ERROR_NOT_WRITABLE' => '',
'ERROR_OPENING_SQL_FILE' => '',
'ERROR_PASSWORDS_DO_NOT_MATCH' => '',
'ERROR_PASSWORD_TOO_SHORT' => '',
'ERROR_SETUP_CANCELLED' => '',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => '',
'ERROR_VIEWS_CANT_CREATE' => '',
'ERROR_VIEWS_CANT_DROP' => '',
'ERROR_VIEWS_CANT_SELECT' => '',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003-Y',
'HEADER_META_MAIN_TITLE' => '',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => '',
'HERE' => 'tu',
'LOAD_DYN_CONTENT_NOTICE' => '',
'MOD_ALLOW_URL_FOPEN' => '',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => '',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => '',
'MOD_GD_INFO' => 'GDlib v2 [v1] ukl. JPEG support',
'MOD_INI_SET' => '',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite module',
'MOD_MYSQL_CONNECT' => 'MySQL client connector za MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => '',
'MOD_PHP_CONFIG' => 'PHP konfiguracija',
'MOD_PHP_EXTENNSIONS' => '',
'MOD_PHP_VERSION' => '',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => '',
'MOD_REQUEST_URI' => '',
'MOD_SERVER_CONFIG' => '',
'MOD_SERVER_PERMISSIONS' => '',
'MOD_SESSION_AUTOSTART' => '',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => '',
'MOD_ZEND_OPTIMIZER' => '',
'MOD_ZEND_PLATFORM_OR_SERVER' => '',
'PRIVACY_POLICY' => '',
'SELECT_DELIVERY_COUNTRY' => '',
'SELECT_DELIVERY_COUNTRY_HINT' => '',
'SELECT_PLEASE_CHOOSE' => '',
'SELECT_SETUP_LANG' => '',
'SELECT_SETUP_LANG_SUBMIT' => '',
'SELECT_SHOP_LANG' => '',
'SELECT_SHOP_LANG_HINT' => '',
'SELECT_SHOP_LOCATION' => '',
'SELECT_SHOP_LOCATION_HINT' => '',
'SETUP_CONFIG_PERMISSIONS' => '',
'SETUP_DIR_DELETE_NOTICE' => '',
'STEP_0_DESC' => '',
'STEP_0_ERROR_TEXT' => '',
'STEP_0_ERROR_URL' => '',
'STEP_0_TEXT' => '',
'STEP_0_TITLE' => '',
'STEP_1_ADDRESS' => 'OXID eSales AG<br> Bertoldstr. 48<br> 79098 Freiburg<br> Deutschland<br>',
'STEP_1_CHECK_UPDATES' => '',
'STEP_1_DESC' => '',
'STEP_1_TEXT' => '',
'STEP_1_TITLE' => '',
'STEP_2_TITLE' => '',
'STEP_3_1_CREATING_TABLES' => '',
'STEP_3_1_DB_CONNECT_IS_OK' => '',
'STEP_3_1_DB_CREATE_IS_OK' => '',
'STEP_3_1_TITLE' => '',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => '',
'STEP_3_2_CREATING_DATA' => '',
'STEP_3_2_TITLE' => '',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => '',
'STEP_3_DB_DATABSE_NAME' => '',
'STEP_3_DB_DEMODATA' => 'Demodata',
'STEP_3_DB_HOSTNAME' => '',
'STEP_3_DB_PASSWORD' => '',
'STEP_3_DB_PASSWORD_SHOW' => '',
'STEP_3_DB_USER_NAME' => '',
'STEP_3_DESC' => '',
'STEP_3_TITLE' => 'Baza podataka',
'STEP_3_UTFINFO' => '',
'STEP_3_UTFMODE' => '',
'STEP_3_UTFNOTSUPPORTED' => '',
'STEP_3_UTFNOTSUPPORTED1' => '',
'STEP_3_UTFNOTSUPPORTED2' => '',
'STEP_4_1_DATA_WAS_WRITTEN' => '',
'STEP_4_1_TITLE' => '',
'STEP_4_ADMIN_LOGIN_NAME' => '',
'STEP_4_ADMIN_PASS' => '',
'STEP_4_ADMIN_PASS_CONFIRM' => '',
'STEP_4_ADMIN_PASS_MINCHARS' => '',
'STEP_4_DESC' => '',
'STEP_4_SHOP_DIR' => '',
'STEP_4_SHOP_TMP_DIR' => '',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => '',
'STEP_5_1_SERIAL_ADDED' => '',
'STEP_5_1_TITLE' => '',
'STEP_5_DESC' => '',
'STEP_5_LICENCE_DESC' => '',
'STEP_5_LICENCE_KEY' => '',
'STEP_5_TITLE' => 'OXID eShop licenc',
'STEP_6_DESC' => '',
'STEP_6_LINK_TO_SHOP' => '',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => '',
'STEP_6_TITLE' => '',
'STEP_6_TO_SHOP' => '',
'STEP_6_TO_SHOP_ADMIN' => '',
'TAB_0_DESC' => '',
'TAB_0_TITLE' => '',
'TAB_1_DESC' => '',
'TAB_1_TITLE' => '',
'TAB_2_DESC' => '',
'TAB_2_TITLE' => '',
'TAB_3_DESC' => '',
'TAB_3_TITLE' => 'Baza podataka',
'TAB_4_DESC' => '',
'TAB_4_TITLE' => '',
'TAB_5_DESC' => '',
'TAB_5_TITLE' => 'Licenc',
'TAB_6_DESC' => '',
'TAB_6_TITLE' => '',
'USE_DYNAMIC_PAGES' => '',
);
