<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (1082), johnjase (163), monteiro (2)
 */

$sLangName  = 'Português';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'De momento, não existem listas Listmania. Para criar uma, clique',
'ADD_RECOMM_ADDRECOMMLINK2' => 'aqui',
'allBrands' => 'Todas as marcas',
'byBrand' => 'Por marca',
'byManufacturer' => 'Por marca',
'byVendor' => 'Por distribuidor',
'DETAILS_ARTNUMBER' => 'Product Nr.:',
'DETAILS_CHOOSEVARIANT' => 'Please select a variant',
'DETAILS_LOCATOR_PRODUCT' => 'PRODUTO',
'DETAILS_PLUSSHIPPING2' => 'shipping costs.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Alerta de preço',
'DETAILS_VPE_MESSAGE_1' => 'Este produto só pode ser encomendado em packs de',
'DETAILS_VPE_MESSAGE_2' => 'purchased.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Um convite de',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'para visitar',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'to visit.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Product Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NENHUM',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Taxa de Iva para pagamento',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Will be paid by:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Will be shipped with',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Shipping costs (w/o tax):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'plus tax',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'plus tax',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Message: ',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>PAYMENT INFORMATION SWITCHED OFF</b> - To switch them on, please change application/views/[theme]/email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'The order is shipped to:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Product',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Product Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'review',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Your shipment tracking URL:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'click here',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Please take a minute to rate our shop.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Your',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Team',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stock low',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Kind regards,',
'FOOTER_CATEGORIES' => 'CATEGORIAS',
'FOOTER_DISTRIBUTORS' => 'DISTRIBUIDORES',
'FOOTER_INFORMATION' => 'INFORMAÇÕES',
'FOOTER_MANUFACTURERS' => 'MARCAS',
'FOOTER_SERVICES' => 'SERVIÇOS',
'FORM_CONTACT_SEND' => 'Send password',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Repeat password:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Forgot password?',
'FORM_NEWSLETTER_FIRSTNAME' => 'First name',
'FORM_PRICEALARM_SEND' => 'Send',
'FORM_PRIVATESALES_INVITE_FROM' => 'From: ',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Olá, estava a visitar a',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'hoje e, encontrei algo que pode ser do seu interesse. Clique no seguinte link e será redirecionado para a loja.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Send invitation',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Sender\'s password: ',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Headline',
'FORM_REGISTER_BILLINGADDRESS' => 'Billing address',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Por favor, preencha todos os campos obrigatórios.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Fui informado acerca do meu',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informed.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Concordo com o',
'FORM_REGISTER_IAGREETOTERMS3' => 'read and accept them.',
'FORM_SUGGEST_MESSAGE1' => 'Olá, estava a visitar a',
'FORM_SUGGEST_MESSAGE2' => 'hoje e, encontrei algo que pode ser do seu interesse. Clique no seguinte link e será redirecionado para a loja.',
'FORM_USER_BILLINGADDRESS' => 'Billing address',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Repeat password:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Search now',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Olá, Criei um registo-presente na',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Seria ótimo se me pudesse oferecer algo.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Error while sending - please check your email address.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Grelha',
'infogrid' => 'Grelha dupla',
'line' => 'Linha',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Please fill all fields with a "*"!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'LOGOUT',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Save new password',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Open new account',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Definições de Faturação e Entregas',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'O seu registo-presente foi enviado com sucesso para:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'dispatched!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Product number',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Iva',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reason',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Sum of products (incl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Sum of products (excl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Your message:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Billing address',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Shipping address',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Bank account number:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Please fill all fields properly!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>De momento não dispomos de métodos de entrega definidos para este país.</p> <p>Estamos a trabalhar no sentido de disponibilizar um método de entrega e informá-lo-emos logo que possível, via e-mail, incluindo mais informações acerca dos custos de entrega.</p> <p>Se concorda com este procedimento, por favor, selecione "seguir para o próximo passo"</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'Iva incluído',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'Taxa adicional',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Taxa COD',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'A protecção de compras Trusted Shops segura a sua compra online. Concordo com a transferência e',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'salvando',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'of my e-mail address for the buyer protection handling by Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Condições',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'for the buyer protection.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'A sua encomenda foi registada com o número:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Desde já ficam os nossos agradecimentos pela sua preferência.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'em',
'PAGE_CHECKOUT_USER' => 'Dispatch',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Um cliente registado tem as seguintes vantagens:<br> - Administração de endereços para entregas<br> - Verificar estado de encomendas<br> - Historial de encomendas<br> - Lista de desejos pessoal<br> - Registo-presentes pessoal<br> - Subscrição de Newsletter<br> - Ofertas especiais e descontos',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Cancel',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NENHUM',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Obrigado.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'agradecemos os seus comentários.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Iremos informá-lo logo que o preço sofra alterações',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Information about Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Obrigado.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'agradecemos os seus comentários.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'News from',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Estes produtos encontram-se na lista de desejos de',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Se pretende agradá-lo(a), compre um ou múltiplos destes produtos.',
'searchResult' => 'Resultados da pesquisa para "%s"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'O utilizador será registado após fornecer a sua password',
'view' => 'Ver',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'More ...',
'WIDGET_LOGINBOX_LOGIN' => 'Login',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Product details',
'WIDGET_SERVICES_GUESTBOOK' => 'Guest book',
'WIDGET_SERVICES_HOME' => 'Home',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'More Information',
);
