<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: afimage (504), diegotech (7), djraptor (1226), Espana (5), ET (219), jmatos (31), jsmaster (6), mvirolde (8), nuelgoz (156)
 */

$sLangName  = 'Español';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Atención',
'BUTTON_BEGIN_INSTALL' => 'Comienzo de la instalación',
'BUTTON_DB_INSTALL' => 'Crear base de datos ahora',
'BUTTON_LICENCE' => 'Continuar',
'BUTTON_PROCEED_INSTALL' => 'Instalar',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Instalar muestra',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Acepto las condiciones de la licencia.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'No acepto las condiciones de la licencia.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>No</strong> instalar datos de prueba',
'BUTTON_START_INSTALL' => 'Reinicie la instalación',
'BUTTON_WRITE_DATA' => 'Guardar y continuar',
'BUTTON_WRITE_LICENCE' => 'Guardar clave de licencia',
'ERROR_BAD_DEMODATA' => 'ERROR: Problema al insertar este SQL:',
'ERROR_BAD_SERIAL_NUMBER' => 'Error: Licencia errónea!',
'ERROR_BAD_SQL' => 'Error: Problema insertando estas sentencias SQL:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ERROR: %s/config.inc.php no editable!',
'ERROR_COULD_NOT_CREATE_DB' => 'ERROR: Base de datos no disponible y tampoco puede crearse!',
'ERROR_COULD_NOT_FIND_FILE' => 'Setup no encuentra "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'No se puede abrir %s para lectura! Por favor, consulta nuestro FAQ, foro o contacta con el staff de soporte de OXID',
'ERROR_COULD_NOT_READ_FILE' => 'Setup no puede abrir "%s" para lectura!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Setup no puede escribir en "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ERROR: Parece que ya existe una tienda OXID instalada en la base de datos %s. Por favor, bórrala antes de continuar!',
'ERROR_DB_CONNECT' => 'ERROR: No es posible la conexión con la base de datos!',
'ERROR_FILL_ALL_FIELDS' => 'ERROR: Por favor, rellene todos los campos necesarios!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Versión de MySQL no alcanza los requerimientos del sistema',
'ERROR_NOT_AVAILABLE' => 'ERROR: %s no encontrado!',
'ERROR_NOT_WRITABLE' => 'ERROR: %s no se puede escribir!',
'ERROR_OPENING_SQL_FILE' => 'ERROR: No se puede abrir fichero SQL %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Contraseñas no coinciden!',
'ERROR_PASSWORD_TOO_SHORT' => 'Contraseña es muy corta!',
'ERROR_SETUP_CANCELLED' => 'Setup ha sido cancelado porque no has aceptado las condiciones de la licencia.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Por favor, introduzca una dirección de e-mail válida!',
'ERROR_VIEWS_CANT_CREATE' => 'ERROR: No se pueden crear vistas. Por favor, compruebe los privilegios de usuario en la base de datos.',
'ERROR_VIEWS_CANT_DROP' => 'ERROR: No se pueden eliminar vistas. Por favor, compruebe sus privilegios de usuario en la base de datos.',
'ERROR_VIEWS_CANT_SELECT' => 'ERROR: No puede hacer select de vistas. Por favor, compruebe sus privilegios de usuario en la base de datos.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'Asistente de instalación de OXID eShop',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Si setup no continua en un par de segundos, por favor click',
'HERE' => 'Aquí',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Si la masilla está marcada, verás un menú adicional en el área administradora de tu tienda OXID.</p><p>En este menú, puedes obtener más informacióm sobre servicios eCommerce como búsqueda de productos en Google.</p> <p>Puedes cambiar esta configuración en cualquier momento.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen al puerto 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Posibles problemas en servidor debido a bugs de PHP',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'Subida de ficheros está habilitada (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. soporte JPEG',
'MOD_INI_SET' => 'ini_set permitido',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'libxml2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Módulo mod_rewrite de Apache',
'MOD_MYSQL_CONNECT' => 'MySQL conector de cliente para MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Modo de compatibilidad Zend debe estar desactivado',
'MOD_PHP_CONFIG' => 'configuración PHP',
'MOD_PHP_EXTENNSIONS' => 'extensiones PHP',
'MOD_PHP_VERSION' => 'PHP versión menos 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals debe estar desactivado',
'MOD_REQUEST_URI' => 'Conjunto REQUEST_URI',
'MOD_SERVER_CONFIG' => 'Configuración del servidor',
'MOD_SERVER_PERMISSIONS' => 'Permisos de acceso en ficheros/carpetas',
'MOD_SESSION_AUTOSTART' => 'session.auto_start debe estar apagado',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'Soporte UTF-8',
'MOD_ZEND_OPTIMIZER' => 'Optimizador Zend o Zend Guard Loader instalado',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Plataforma Zend o Servidor Zend instalado',
'PRIVACY_POLICY' => 'condiciones de privacidad',
'SELECT_DELIVERY_COUNTRY' => 'País de envío principal',
'SELECT_DELIVERY_COUNTRY_HINT' => 'Si es necesario, activa más paises de envío en admin.',
'SELECT_PLEASE_CHOOSE' => 'Por favor, elige',
'SELECT_SETUP_LANG' => 'Idioma de instalación',
'SELECT_SETUP_LANG_SUBMIT' => 'Selecciona',
'SELECT_SHOP_LANG' => 'Idioma de la tienda',
'SELECT_SHOP_LANG_HINT' => 'Si fuera necesario, activa más idiomas en admin.',
'SELECT_SHOP_LOCATION' => 'Su mercado',
'SELECT_SHOP_LOCATION_HINT' => 'Por favor, elige el mercado al cual la tienda va dirigido. De acuerdo a ello, servicios adicionales de eCommerce serán cargados desde el servidor OXID, si lo permites.',
'SETUP_CONFIG_PERMISSIONS' => 'Debido a razones de seguridad pon tu fichero config.inc.php en modo solo lectura!',
'SETUP_DIR_DELETE_NOTICE' => 'Debido a razones de seguridad, elimine el directorio setup si no se ha hecho durante la instalación.',
'STEP_0_DESC' => 'En este paso comprobaremos si tu sistema se ajusta a los requerimientos:',
'STEP_0_ERROR_TEXT' => 'Tu sistema no se ajusta a los requerimientos del sistema',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Tu sistema cumple los requerimientos.</li><li class="pmin"> - El equerimiento no se cumple o se cumple parcialmente. La tienda funcionará igualmente y puede ser instalada...</li><li class="fail"> - Tu sistema no cumple los requerimientos. La tienda no funcionará sin ellos y no puede ser instalada.</li><li class="null"> - El requerimiento no puede ser comprobado.</ul>',
'STEP_0_TITLE' => 'Comprobación de requerimientos del sistema',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Compruebe actualizaciones disponibles regularmente',
'STEP_1_DESC' => 'Bienvenido al asistente de instalación de OXID eShop',
'STEP_1_TEXT' => 'Lea cuidadosamente las siguientes intrucciones para garantizar una instalación correcta.

Nuestros deseos para el mejor resultado usando tu eShop OXID por',
'STEP_1_TITLE' => 'Bienvenido',
'STEP_2_TITLE' => 'Condiciones de la licencia',
'STEP_3_1_CREATING_TABLES' => 'Creando tablas, aplicando datos ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Conexión a base de datos correctamente comprobada ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Base de datos %s correctamente creada ...',
'STEP_3_1_TITLE' => 'Base de datos - empezando a crearse ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Si quieres sobrescribir todos los datos existentes e instalar de todas formas, haga click',
'STEP_3_2_CREATING_DATA' => 'Base de datos creada correctamente. Por favor, espere ...',
'STEP_3_2_TITLE' => 'Base de datos - tablas están siendo creadas ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'Si la base de datos no existe, será creada',
'STEP_3_DB_DATABSE_NAME' => 'Nombre de base de datos',
'STEP_3_DB_DEMODATA' => 'Datos de demostración',
'STEP_3_DB_HOSTNAME' => 'Hostname o IP de base de datos',
'STEP_3_DB_PASSWORD' => 'Contraseña de base de datos',
'STEP_3_DB_PASSWORD_SHOW' => 'Mostrar contraseña',
'STEP_3_DB_USER_NAME' => 'Usuario de base de datos',
'STEP_3_DESC' => 'La base de datos será creada y las tablas necesarias rellenas. Por favor, provea la siguiente información:',
'STEP_3_TITLE' => 'Base de datos',
'STEP_3_UTFINFO' => 'La codificación UTF-8 proporciona mejor soporte para caracteres especiales que otras codificaciones. Esto es particularmente importante para eShops multilenguaje. Aunque UTF-8 es ligeramente mas lento que el estandar de codificación (ISO 8859-15). <br /> Si tienes planeado proporcionar a tu tienda diferentes idiomas, deberías usar UTF-8. Si quieres proporcionar unos cuantos idiomas que usan simbolos relacionados (Ej: Ingés, Alemán, Francés), no necesitas UTF-8.',
'STEP_3_UTFMODE' => 'Usar codificación UTF-8',
'STEP_3_UTFNOTSUPPORTED' => 'La tienda no puede operar en modo UTF-8, debido a:',
'STEP_3_UTFNOTSUPPORTED1' => 'modulo PHP mbstring desaparecido',
'STEP_3_UTFNOTSUPPORTED2' => 'instalado PCRE no soporta UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Comprobando y escribiendo datos correcto. Espere ...',
'STEP_4_1_TITLE' => 'Directorios - Siendo creados ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'E-Mail de Administrador (usado como nombre de usuario)',
'STEP_4_ADMIN_PASS' => 'Contraseña de administrador',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Confirmas contraseña de administrador',
'STEP_4_ADMIN_PASS_MINCHARS' => 'libremente seleccionable, min 6 caracteres',
'STEP_4_DESC' => 'Proporcione los datos necesarios para ejecutar OXID eShop:',
'STEP_4_SHOP_DIR' => 'Directorio para eShop OXID',
'STEP_4_SHOP_TMP_DIR' => 'Directorio para datos temporales',
'STEP_4_SHOP_URL' => 'URL de Tienda',
'STEP_4_TITLE' => 'Configurando directorios y URL de eShop OXID',
'STEP_5_1_SERIAL_ADDED' => 'Licencia guardada correctamente. Espere ...',
'STEP_5_1_TITLE' => 'Licencia está siendo insertada ...',
'STEP_5_DESC' => 'Confirme licencia:',
'STEP_5_LICENCE_DESC' => 'La licencia proporcionada es válida para 30 días. Después de este periodo todos tus cambios permanecerán si has insertado una licencia válida.',
'STEP_5_LICENCE_KEY' => 'Licencia',
'STEP_5_TITLE' => 'Licencia de Oxid eShop',
'STEP_6_DESC' => 'Tu eShop OXID ha sido instalada correctamente.',
'STEP_6_LINK_TO_SHOP' => 'Continué a tu eShop OXID',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Continúe a la interfaz de administración de tu eShop OXID',
'STEP_6_TITLE' => 'eShop OXID instalada correctamente',
'STEP_6_TO_SHOP' => 'A tienda',
'STEP_6_TO_SHOP_ADMIN' => 'A interfaz de administración',
'TAB_0_DESC' => 'Comprobando si tu sistema cumple los requisitos',
'TAB_0_TITLE' => 'Requerimientos del sistema',
'TAB_1_DESC' => 'Bienvenido al asistente de instalación de eShop OXID',
'TAB_1_TITLE' => 'Bienvenido',
'TAB_2_DESC' => 'Confirme condiciones de licencia',
'TAB_2_TITLE' => 'Condiciones de licencia',
'TAB_3_DESC' => 'Comprobación de conexión de base de datos, creando tablas',
'TAB_3_TITLE' => 'Base de datos',
'TAB_4_DESC' => 'Configurando directorios y seleccionando login de admin',
'TAB_4_TITLE' => 'Directorio y login',
'TAB_5_DESC' => 'Aplicar licencia',
'TAB_5_TITLE' => 'Licencia',
'TAB_6_DESC' => 'Instalación completa',
'TAB_6_TITLE' => 'Acabado',
'USE_DYNAMIC_PAGES' => 'Para incrementar tu negocio obtiene información adicional desde el servidor OXID. Encuentra mas información en nuestro',
);
