<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: afimage (504), diegotech (7), djraptor (418), Espana (5), ET (212), jmatos (31), jsmaster (6), mvirolde (8), nuelgoz (156)
 */

$sLangName  = 'Español';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Atención',
'BUTTON_BEGIN_INSTALL' => 'Comienzo de la instalación',
'BUTTON_DB_INSTALL' => 'Crear base de datos ahora',
'BUTTON_LICENCE' => 'Continuar',
'BUTTON_PROCEED_INSTALL' => 'Instalar',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Instalar muestra',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Acepto las condiciones de la licencia.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'No acepto las condiciones de la licencia.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>No</strong> instalar datos de prueba',
'BUTTON_START_INSTALL' => 'Reinicie la instalación',
'BUTTON_WRITE_DATA' => 'Guardar y continuar',
'BUTTON_WRITE_LICENCE' => 'Guardar clave de licencia',
'ERROR_BAD_DEMODATA' => 'ERROR: Problema al insertar este SQL:',
'ERROR_BAD_SERIAL_NUMBER' => 'Error: Licencia errónea!',
'ERROR_BAD_SQL' => 'Error: Problema insertando estas sentencias SQL:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ERROR: %s/config.inc.php no editable!',
'ERROR_COULD_NOT_CREATE_DB' => 'ERROR: Base de datos no disponible y tampoco puede crearse!',
'ERROR_COULD_NOT_FIND_FILE' => 'Setup no encuentra "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'No se puede abrir %s para lectura! Por favor, consulta nuestro FAQ, foro o contacta con el staff de soporte de OXID',
'ERROR_COULD_NOT_READ_FILE' => 'Setup no puede abrir "%s" para lectura!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Setup no puede escribir en "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ERROR: Parece que ya existe una tienda OXID instalada en la base de datos %s. Por favor, bórrala antes de continuar!',
'ERROR_DB_CONNECT' => 'ERROR: No es posible la conexión con la base de datos!',
'ERROR_FILL_ALL_FIELDS' => 'ERROR: Por favor, rellene todos los campos necesarios!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Versión de MySQL no alcanza los requerimientos del sistema',
'ERROR_NOT_AVAILABLE' => 'ERROR: %s no encontrado!',
'ERROR_NOT_WRITABLE' => 'ERROR: %s no se puede escribir!',
'ERROR_OPENING_SQL_FILE' => 'ERROR: No se puede abrir fichero SQL %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Contraseñas no coinciden!',
'ERROR_PASSWORD_TOO_SHORT' => 'Contraseña es muy corta!',
'ERROR_SETUP_CANCELLED' => 'Setup ha sido cancelado porque no has aceptado las condiciones de la licencia.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Por favor, introduzca una dirección de e-mail válida!',
'ERROR_VIEWS_CANT_CREATE' => 'ERROR: No se pueden crear vistas. Por favor, compruebe los privilegios de usuario en la base de datos.',
'ERROR_VIEWS_CANT_DROP' => 'ERROR: No se pueden eliminar vistas. Por favor, compruebe sus privilegios de usuario en la base de datos.',
'ERROR_VIEWS_CANT_SELECT' => 'ERROR: No puede hacer select de vistas. Por favor, compruebe sus privilegios de usuario en la base de datos.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'Asistente de instalación de OXID eShop',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Si setup no continua en un par de segundos, por favor click',
'HERE' => 'Aquí',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Si la masilla está marcada, verás un menú adicional en el área administradora de tu tienda OXID.</p><p>En este menú, puedes obtener más informacióm sobre servicios eCommerce como búsqueda de productos en Google.</p> <p>Puedes cambiar esta configuración en cualquier momento.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen al puerto 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Possible issues on server due to PHP Bugs',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'File uploads are enabled (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. soporte JPEG',
'MOD_INI_SET' => 'ini_set permitido',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'libxml2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MEMORY_LIMIT' => 'Límite de memoria PHP (mín. 14MB, 30MB recomendados)',
'MOD_MOD_REWRITE' => 'Módulo mod_rewrite de Apache',
'MOD_MYSQL_CONNECT' => 'MySQL conector de cliente para MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend compatibility mode must be off',
'MOD_PHP_CONFIG' => 'configuración PHP',
'MOD_PHP_EXTENNSIONS' => 'extensiones PHP',
'MOD_PHP_VERSION' => 'PHP versión menos 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals debe estar desactivado',
'MOD_REQUEST_URI' => 'Conjunto REQUEST_URI',
'MOD_SERVER_CONFIG' => 'Configuración del servidor',
'MOD_SERVER_PERMISSIONS' => 'Files/folders access rights',
'MOD_SESSION_AUTOSTART' => 'session.auto_start debe estar apagado',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'Soporte UTF-8',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer or Zend Guard Loader installed',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform or Zend Server installed',
'PRIVACY_POLICY' => 'privacy statements',
'SELECT_COUNTRY_LANG' => 'Please choose your country',
'SELECT_DELIVERY_COUNTRY' => 'Main delivery country',
'SELECT_DELIVERY_COUNTRY_HINT' => 'If needed, activate easily more delivery countries in admin.',
'SELECT_PLEASE_CHOOSE' => 'Please choose',
'SELECT_SETUP_LANG' => 'Installation language',
'SELECT_SETUP_LANG_HINT' => '. If needed, activate easily more languages in admin.',
'SELECT_SETUP_LANG_SUBMIT' => 'Select',
'SELECT_SHOP_LANG' => 'Idioma de la tienda',
'SELECT_SHOP_LANG_HINT' => 'If needed, activate easily more languages in admin.',
'SELECT_SHOP_LOCATION' => 'Su mercado',
'SELECT_SHOP_LOCATION_HINT' => 'Please choose the market to which shop is focused. According to it, additional eCommerce Services will be loaded from OXID server, if you allow that.',
'SETUP_CONFIG_PERMISSIONS' => 'Due to security reasons put your config.inc.php file to read-only mode!',
'SETUP_DIR_DELETE_NOTICE' => 'Due to security reasons remove setup directory if not yet done during installation.',
'STEP_0_DESC' => 'In this step we check if your system fits the requirements:',
'STEP_0_ERROR_TEXT' => 'Your system does not fit system requirements',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Your system fits the requirement.</li><li class="pmin"> - The requirement is not or only partly fit. The OXID eShop will work anyway and can be installed..</li><li class="fail"> - Your system doesn\'t fit the requirement. The OXID eShop will not work without it and cannot be installed.</li><li class="null"> - The requirement could  not be checked.</ul>',
'STEP_0_TITLE' => 'System requirements check',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Check for available updates regularly',
'STEP_1_DESC' => 'Welcome to installation wizard of OXID eShop',
'STEP_1_TEXT' => 'Please read carefully the following instructions to guarantee a smooth installation.
                                                    Wishes for best success in using your OXID eShop by',
'STEP_1_TITLE' => 'Bienvenido',
'STEP_2_TITLE' => 'Condiciones de la licencia',
'STEP_3_1_CREATING_TABLES' => 'Creating tables, applying data ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Database connection successfully tested ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Database %s successfully created ...',
'STEP_3_1_TITLE' => 'Database - being created ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'If you want to overwrite all existing data and install anyway click ',
'STEP_3_2_CREATING_DATA' => 'Database successfully created. Please wait ...',
'STEP_3_2_TITLE' => 'Database - tables are beeing created ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'If database does not exist, it\'s going to be created',
'STEP_3_DB_DATABSE_NAME' => 'Database name',
'STEP_3_DB_DEMODATA' => 'Demodata',
'STEP_3_DB_HOSTNAME' => 'Database hostname or IP',
'STEP_3_DB_PASSWORD' => 'Database password',
'STEP_3_DB_PASSWORD_SHOW' => 'Show password',
'STEP_3_DB_USER_NAME' => 'Database username',
'STEP_3_DESC' => 'Database is going to be created and needed tables are written. Please provide some information:',
'STEP_3_TITLE' => 'Database',
'STEP_3_UTFINFO' => 'UTF-8 character encoding provides better support for special chars than other character encodings. This is particulary important for multilingual eShops. However, UTF-8 is slightly slower than the standard encoding (ISO 8859-15). <br /> If you plan to provide your eShop in many different languages, you should use UTF-8. If you just want to provide a few languages using related symbol sets (e. g. English, German, French), you don\'t need UTF-8.',
'STEP_3_UTFMODE' => 'Use UTF-8 character encoding',
'STEP_3_UTFNOTSUPPORTED' => 'The OXID eShop cannot operate in UTF-8 mode, due to:',
'STEP_3_UTFNOTSUPPORTED1' => ' missing mbstring PHP module',
'STEP_3_UTFNOTSUPPORTED2' => ' installed PCRE does not support UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Check and writing data successful. Please wait ...',
'STEP_4_1_TITLE' => 'Directories - being created ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Administrator e-mail (used as login name)',
'STEP_4_ADMIN_PASS' => 'Contraseña de administrador',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Confirm Administrator password',
'STEP_4_ADMIN_PASS_MINCHARS' => 'freely selectable, min. 6 chars',
'STEP_4_DESC' => 'Please provide neccesary data for running OXID eShop:',
'STEP_4_SHOP_DIR' => 'Directory for OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Directory for temporary data',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Setting up OXID eShop directories and URL',
'STEP_5_1_SERIAL_ADDED' => 'License key successfully saved. Please wait ...',
'STEP_5_1_TITLE' => 'License key is being inserted ...',
'STEP_5_DESC' => 'Please confirm license key:',
'STEP_5_LICENCE_DESC' => 'The provided key is valid for 30 days. After this period all of your changes remain if you insert a valid license key.',
'STEP_5_LICENCE_KEY' => 'License key',
'STEP_5_TITLE' => 'Licencia de Oxid eShop',
'STEP_6_DESC' => 'Your OXID eShop has been installed successfully.',
'STEP_6_LINK_TO_SHOP' => 'Continue to your OXID eShop',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Continue to your OXID eShop admin interface',
'STEP_6_TITLE' => 'OXID eShop successfully installed',
'STEP_6_TO_SHOP' => 'To Shop',
'STEP_6_TO_SHOP_ADMIN' => 'To admin interface',
'TAB_0_DESC' => 'Checking if your system fits the requirements',
'TAB_0_TITLE' => 'System Requirements',
'TAB_1_DESC' => 'Welcome to OXID eShop installation wizard',
'TAB_1_TITLE' => 'Bienvenido',
'TAB_2_DESC' => 'Confirm license conditions',
'TAB_2_TITLE' => 'License conditions',
'TAB_3_DESC' => 'Test database connection, building tables',
'TAB_3_TITLE' => 'Base de datos',
'TAB_4_DESC' => 'Configuring directories and selecting admin login',
'TAB_4_TITLE' => 'Directory & login',
'TAB_5_DESC' => 'Apply license key',
'TAB_5_TITLE' => 'Licencia',
'TAB_6_DESC' => 'Installation succeeded',
'TAB_6_TITLE' => 'Acabado',
'USE_DYNAMIC_PAGES' => 'To increase your business success get additional information from OXID\'s server. You find more information in our ',
);
