<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: allabreve (3668), koikaam (227), patmat2809 (7)
 */

$sLangName  = 'Magyar';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Figyelem!',
'BUTTON_BEGIN_INSTALL' => 'Az eShop telepítésének megkezdése',
'BUTTON_DB_INSTALL' => 'Az adatbázis telepítése',
'BUTTON_LICENCE' => 'Tovább',
'BUTTON_PROCEED_INSTALL' => 'A telepítés megkezdése',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Demó adatok telepítése',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Elfogadom a Licencfeltételeket.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Nem fogadom el a Licencfeltételeket.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => 'Demó adatok telepítésének <strong>mellőzése</strong>',
'BUTTON_START_INSTALL' => 'A telepítés újraindítása',
'BUTTON_WRITE_DATA' => 'Adatok mentése',
'BUTTON_WRITE_LICENCE' => 'Licenc-kulcs mentése',
'ERROR_BAD_DEMODATA' => 'HIBA: (Demó adatok)Probléma a következő SQL parancsokkal:',
'ERROR_BAD_SERIAL_NUMBER' => 'HIBA: Hibás sorozatszám!',
'ERROR_BAD_SQL' => 'HIBA: (Táblázat) Probléma a következő SQL parancsokkal:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'HIBA: %s/config.inc.php nem írható!',
'ERROR_COULD_NOT_CREATE_DB' => 'HIBA: Az %s adatbázis nem létezik, és nem hozható létre!',
'ERROR_COULD_NOT_FIND_FILE' => 'A telepítő nem találta a "%s" fájlt!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'A config.inc.php-t nem lehet megnyitni. Kérem, a GYIK-ben, illetve a Fórumon olvasson utána, vagy lépjen kapcsolatba az OXID támogatassal .',
'ERROR_COULD_NOT_READ_FILE' => 'A telepítő nem tudja megnyitni a "%s" fájlt!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'A telepítő nem tud a "%s" fájlba írni!',
'ERROR_DB_ALREADY_EXISTS' => 'HIBA: Úgy tűnik, hogy az %s adatbázisban már létezne OXID adatbázis. Kérem, törölje!',
'ERROR_DB_CONNECT' => 'HIBA: Az adatbázissal történő kapcsolatteremtés nem lehetséges!',
'ERROR_FILL_ALL_FIELDS' => 'HIBA: Kérem, töltse ki a szükséges mezőket!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'A MySQL verzió nem felel meg a rendszerkövetelményeknek.',
'ERROR_NOT_AVAILABLE' => 'HIBA: %s nem létezik!',
'ERROR_NOT_WRITABLE' => 'HIBA: %s nem írható!',
'ERROR_OPENING_SQL_FILE' => 'HIBA: Az SQL adatbázis %s nem nyitható meg!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'A jelszavak nem egyeznek!',
'ERROR_PASSWORD_TOO_SHORT' => 'A jelszó túl rövid!',
'ERROR_SETUP_CANCELLED' => 'A telepítés meg lett szakítva, mert nem fogadta el Licenc-feltételeinket.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Kérem adjon meg egy érvényes e-mail címet!',
'ERROR_VIEWS_CANT_CREATE' => 'HIBA: A nézettáblázat (Views) nem létrehozható. Kérem, ellenőrizze a felhasználói jogokat az adatbázishoz!',
'ERROR_VIEWS_CANT_DROP' => 'HIBA: A nézettáblázat nem törölhető. Kann Views nicht löschen. Kérem, ellenőrizze a felhasználói jogokat az adatbázishoz!',
'ERROR_VIEWS_CANT_SELECT' => 'HIBA: Nincs hozzáférés a nézettáblázathoz (Views). Kérem, ellenőrizze a felhasználói jogokat az adatbázishoz!',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003-Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop telepítő asszisztens',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Ha a telepítés nem indul el automatikusan néhány másodpercen belül, akkor kattintson!',
'HERE' => 'ide',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Ha ezt az opciót aktiválja, akkor az oxid shop adminisztrációs felületén további menüpontokat találhat.</p><p>Ezeknek a menüpontok segítségével további információkhoz juthat az E-Commerce szervízszolgáltatásainkról, mint pl.: Goolge termékkeresés, vagy Econda...</p> <p>Ez a beállítás módosítható az adminisztrációs felületen.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen vagy fsockopen 80-as Portra',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'PHP programhiba (Bug) okozta lehetséges szerver problémák',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'Fájlok feltöltése engedélyezve(file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. JPEG támogatás',
'MOD_INI_SET' => 'ini_set engedélyezve',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite Modul',
'MOD_MYSQL_CONNECT' => 'MySQL Client Connector MySQL 5-höz',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'A Zend kompatibilitási módot ki kell kapcsolni',
'MOD_PHP_CONFIG' => 'PHP konfiguráció',
'MOD_PHP_EXTENNSIONS' => 'PHP kiterjesztések',
'MOD_PHP_VERSION' => 'Legalacsonyabb PHP verzió 5.3.25',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals-t ki kell kapcsolni!',
'MOD_REQUEST_URI' => 'REQUEST_URI létezik',
'MOD_SERVER_CONFIG' => 'Szerver-konfiguráció',
'MOD_SERVER_PERMISSIONS' => 'Fájlhozzáférési jog (CHMOD)',
'MOD_SESSION_AUTOSTART' => 'A session.auto_start-ot ki kell kapcsolni!',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 támogatás',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer vagy Zend Guard Loader telepítve van',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform Zend Server telepítve',
'PRIVACY_POLICY' => 'Adatvédelmi irányelvünkről',
'SELECT_DELIVERY_COUNTRY' => 'Fő szállítási ország',
'SELECT_DELIVERY_COUNTRY_HINT' => 'További szállítási országot aktiválhat, ha szükséges.',
'SELECT_PLEASE_CHOOSE' => 'Kérem, válasszon',
'SELECT_SETUP_LANG' => 'A telepítés nyelve',
'SELECT_SETUP_LANG_SUBMIT' => 'Kiválasztás',
'SELECT_SHOP_LANG' => 'Az eShop nyelve',
'SELECT_SHOP_LANG_HINT' => 'A shop adminisztrációs felületén több nyelvet aktiválhat, ha szükséges...',
'SELECT_SHOP_LOCATION' => 'Az ön országa',
'SELECT_SHOP_LOCATION_HINT' => 'Kérem, válassza ki azt az országot, ahol a shop működni fog. Attól függően jelennek meg további E-Commerce szervíz szolgáltatások az OXID szerveréről, amennyiben ön engedélyezi.',
'SETUP_CONFIG_PERMISSIONS' => 'FONTOS: A config.inc.php konfigurációs fájlt állítsa read-only-módba (CHMOD 444)!',
'SETUP_DIR_DELETE_NOTICE' => 'FONTOS: Kérem törölje a telepítés (setup) könyvtárát, ha nem törlődött automatikusan!',
'STEP_0_DESC' => 'Ebben a lépésben ellenőrizve lesz, hogy az ön rendszere megfelel-e az alapkövetelményeknek:',
'STEP_0_ERROR_TEXT' => 'Az Ön rendszere nem felel meg a rendszerkövetelményeknek!',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/de/support-services/dokumentation-und-hilfe/oxid-eshop/installation/oxid-eshop-neu-installieren/server-und-systemvoraussetzungen/systemvoraussetzungen-ce.html',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - A feltételek teljesültek.</li><li class="pmin"> - A feltételek csak részben teljesültek. Az OXID eShop mindezek ellenére működik, és telepíthető.</li><li class="fail"> - A feltételek nem teljesültek. AZ OXID eShop nem működik ezen követelmények nélkül és nem telepíthető.</li><li class="null"> - A feltételek teljesítése nem ellenőrízhető.</ul>',
'STEP_0_TITLE' => 'Rendszerkövetelmények ellenőrzése',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Frissítések rendszeres ellenőrzése.',
'STEP_1_DESC' => 'Üdvözli Önt az OXID eShop telepítő asszisztense',
'STEP_1_TEXT' => '<p>A sikeres és egyszerű telepítés érdekében, szánjon arra időt, hogy a következő pontokat figyelmesen olvassa el lépésről, lépésre.</p> <p>Sok sikert kívánunk az OXID eShop-hoz!</p>',
'STEP_1_TITLE' => 'Üdvözöljük!',
'STEP_2_TITLE' => 'Licencfeltételek',
'STEP_3_1_CREATING_TABLES' => 'Táblázatok létrehozása, adatok másolása...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Az adatbázishoz való csatlakozás ellenőrzése, sikeres...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Az adatbázis %s sikeresen létrehozva...',
'STEP_3_1_TITLE' => 'Adatbázis - folyamatban...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Abban az esetben, ha mégis telepíteni szeretné, és a régi adatokat felül szeretné írni, kattinson',
'STEP_3_2_CREATING_DATA' => 'Az adatbázis létrehozva!<br>Kérem várjon...',
'STEP_3_2_TITLE' => 'Adatbázis - Táblázatok létrehozása...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'Amennyiben az adatbázis nem létezik, megkíséreljük azt létrehozni',
'STEP_3_DB_DATABSE_NAME' => 'Az adatbázis neve',
'STEP_3_DB_DEMODATA' => 'Demó adatok',
'STEP_3_DB_HOSTNAME' => 'Adatbázis hostneve vagy IP-címe',
'STEP_3_DB_PASSWORD' => 'Adatbázis jelszó',
'STEP_3_DB_PASSWORD_SHOW' => 'Jelszó megjelenítése',
'STEP_3_DB_USER_NAME' => 'Adatbázis felhasználónév',
'STEP_3_DESC' => 'Az adatbázis létrehozása  előtt szükség van még néhány adatra:',
'STEP_3_TITLE' => 'Datenbank',
'STEP_3_UTFINFO' => 'Az UTF-8 karakterkódolás jobban kezeli a különleges karaktereket mint a többi kódolás. Ez különösen a többnyelvű shopok számára fontos. Ugyanakkor az eShop kissé lassúbb az UTF-8-cal, mint a standard karakterkódolással(ISO 8859-15). <br /> Ha szándékában áll több különböző karakterkészlettel rendelkező nyelvet (pl.: magyar, orosz, lengyel, német) használni a shopban, használja az UTF-8 kódolást. Ha ön azonban több hasonló karakterkészlettel rendelkező nyelvet kíván használni (Pl.: német, angol, francia), akkor nincs szüksége az UTF-8-ra.',
'STEP_3_UTFMODE' => 'UTF-8 karakterkódolás használata',
'STEP_3_UTFNOTSUPPORTED' => 'Az OXID eShop nem alkalmazható UTF-8 karakterkódolással, mert::',
'STEP_3_UTFNOTSUPPORTED1' => 'az mbstring PHP-Modul hiányzik',
'STEP_3_UTFNOTSUPPORTED2' => 'a telepített PCRE-Verzió UTF-8 nincs támogatva',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Az adatok ellenőrzése és írása sikeres!<br>Kérem várjon...',
'STEP_4_1_TITLE' => 'Könyvtárak - folyamatban...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Adminisztrátori e-mail (felhasználónévként lesz használva)',
'STEP_4_ADMIN_PASS' => 'Adminisztrátori jelszó',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Adminisztrátori jelszó megerősítése',
'STEP_4_ADMIN_PASS_MINCHARS' => 'szabadon választható, legalább 6 karakter',
'STEP_4_DESC' => 'Kérem adja meg a működéshez szükséges adatokat:',
'STEP_4_SHOP_DIR' => 'A Shop szerverének könyvtára',
'STEP_4_SHOP_TMP_DIR' => 'A TMP Könyvtár helye a szerveren',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Az OXID eShop beállítása',
'STEP_5_1_SERIAL_ADDED' => 'A Licenc-kulcs mentése sikeres!<br>Kérem, várjon...',
'STEP_5_1_TITLE' => 'Licenc-kulcs - folyamatban...',
'STEP_5_DESC' => 'Kérem adja meg az Ön OXID eShop Licenc-kulcsát:',
'STEP_5_LICENCE_DESC' => 'A demó verzió Licenc-kulcsa (felül kitöltve) 30 napig érvényes .<br>                                                    A 30 nap lejárta után, csak érvényes Licenc-kulcs megadása után használható tovább.',
'STEP_5_LICENCE_KEY' => 'Licenc-kulcs',
'STEP_5_TITLE' => 'OXID eShop Licenc',
'STEP_6_DESC' => 'Az Ön OXID eShop telepítése sikeresen befejeződött.',
'STEP_6_LINK_TO_SHOP' => 'Tovább az eShop-baa',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Továbblépés az eShop Adminisztrációjához',
'STEP_6_TITLE' => 'OXID eShop telepítése sikeres',
'STEP_6_TO_SHOP' => 'Tovább az eShop-hoz',
'STEP_6_TO_SHOP_ADMIN' => 'Tovább az Adminisztrációhoz',
'TAB_0_DESC' => 'Ellenőrizzük, hogy az ön redszere megfelel-e a feltételeknek',
'TAB_0_TITLE' => 'Telepítési feltételek',
'TAB_1_DESC' => 'Üdvözöljük<br>az OXID eShop telepítésénél!',
'TAB_1_TITLE' => 'Üdvözöljük',
'TAB_2_DESC' => 'Kérjük, fogadja el a Lincecszerződést!',
'TAB_2_TITLE' => 'Licencfeltételek',
'TAB_3_DESC' => 'Kapcsolat ellenőrzése,<br>táblák létrehozása',
'TAB_3_TITLE' => 'Adatbázis',
'TAB_4_DESC' => 'Könyvtárak létrehozása és az Adminisztrációs bejelentkezés kiválasztása',
'TAB_4_TITLE' => 'Könyvtárak és bejelentkezés',
'TAB_5_DESC' => 'Licenckulcs megadása',
'TAB_5_TITLE' => 'Licenc',
'TAB_6_DESC' => 'A telepítés sikeres!',
'TAB_6_TITLE' => 'Végrehajt',
'USE_DYNAMIC_PAGES' => 'Az OXID szerverrel való összeköttetés engedélyezése. További információk az',
);
