<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: abejingas (188), agladutis (19), muslimukas (5), NFQ Lithuania (2756), swolou (3), tlt (204)
 */

$sLangName  = "Lietuvių";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Mėgstamiausių prekių sąrašų sukurta nėra. Norėdami sukurti naują, spauskite',
'ADD_RECOMM_ADDRECOMMLINK2' => 'čia',
'allBrands' => '',
'byBrand' => 'Pagal gamintoją',
'byManufacturer' => 'Pagal gamintoją',
'byVendor' => 'Pagal tiekėją',
'DETAILS_ARTNUMBER' => '',
'DETAILS_CHOOSEVARIANT' => '',
'DETAILS_LOCATOR_PRODUCT' => 'PREKĖ',
'DETAILS_PLUSSHIPPING2' => '',
'DETAILS_PRICEALARM' => '<b>[!]</b> Stebėk kainą',
'DETAILS_VPE_MESSAGE_1' => 'Ši prekė parduodama tik pakuotėmis',
'DETAILS_VPE_MESSAGE_2' => '',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Pakvietimas nuo',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'apsilankyti',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => '',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => '',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NĖRA',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'PVM',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => '',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => '',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => '',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => '',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => '',
'EMAIL_ORDER_CUST_HTML_TAX1' => '',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => '',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => '',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => '',
'EMAIL_SENDDOWNLOADS_GREETING' => '',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => '',
'EMAIL_SENDDOWNLOADS_SUBJECT' => '',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => '',
'EMAIL_SENDEDNOW_HTML_REVIEW' => '',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Nuoroda pirkinio gabenimo sekimui:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'čia',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => '',
'EMAIL_STOCKREMINDER_SUBJECT' => '',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => '',
'FOOTER_CATEGORIES' => 'KATEGORIJOS',
'FOOTER_DISTRIBUTORS' => 'TIEKĖJAI',
'FOOTER_INFORMATION' => 'INFORMACIJA',
'FOOTER_MANUFACTURERS' => 'GAMINTOJAI',
'FOOTER_SERVICES' => 'PASLAUGOS',
'FORM_CONTACT_SEND' => '',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => '',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => '',
'FORM_NEWSLETTER_FIRSTNAME' => '',
'FORM_PRICEALARM_SEND' => '',
'FORM_PRIVATESALES_INVITE_FROM' => '',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Sveiki, pažiūrėkite',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'šiandien radau įdomių prekių, gal sudomins ir tave. Paspauskite ant nuorodos ir būsite nukreiptas tiesiai į el. parduotuvę.',
'FORM_PRIVATESALES_INVITE_SEND' => '',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => '',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => '',
'FORM_REGISTER_BILLINGADDRESS' => '',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Prašome užpildyti privalomus laukus.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Aš esu informuotas apie savo',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => '',
'FORM_REGISTER_IAGREETOTERMS1' => 'Aš sutinku su',
'FORM_REGISTER_IAGREETOTERMS3' => '',
'FORM_SUGGEST_MESSAGE1' => 'Sveiki, pažiūrėkite',
'FORM_SUGGEST_MESSAGE2' => 'šiandien as radau įdomių prekių, gal sudomins ir tave. Paspauskite ant nuorodos ir būsite nukreiptas tiesiai į el. parduotuvę.',
'FORM_USER_BILLINGADDRESS' => '',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => '',
'FORM_WISHLIST_SEARCH_SEARCH' => '',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Sveiki, aš susikūriau pageidavimų sąrašą',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Būtų smagu jei man ką nors nupirktumėt.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => '',
'fullDateFormat' => '',
'grid' => 'Tinkeliu',
'infogrid' => 'Dvigubu tinkeliu',
'line' => 'Eilute',
'NEWSLETTER_COMPLETEALLFIELEDS' => '',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'ATSIJUNGTI',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => '',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => '',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Registracijos ir pristatymo adresų informacija',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Jūsų pageidavimų sąrašas buvo išsiųstas sėkmingai:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'PVM',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => '',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => '',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => '',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => '',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => '',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => '',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => '',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Šiuo metu į jūsų pasirinktą šalį nepristatome.</p> <p>Mes rasite jums priimtiną pristatymo būdą ir su jumis susieksime iš karto kai tik galėsimebei aptarsime pristatymo kainas.</p> <p>Jei jūs sutinkate su mūsų sąlygomis, prašome pereiti į kitą žingsnį</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'su PVM',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => '',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Grynais',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'Trusted Shops pirkėjo apsauga, apsaugo jūsų pirkimą internetu. Aš sutinku su perdavimu ir',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'saugojimu',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'mano el. pašto adreso dėl pirkėjo Trusted Shops apsaugos duomenų tvarkymo.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Taisyklės',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'pirkėjo apsaugai.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Jūsų užsakymui suteiktas Nr.:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => '',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Dėkojame, kad užsakėte',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => '',
'PAGE_CHECKOUT_USER' => '',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Registruotas vartotojas turi pranašumą:<br> - Pristatymo adresų valdymas<br> - Užsakymo statuso tikrinimas<br> - Užsakymų istorija<br> - Prekių atmintinė<br> - Pageidavimų sąrašas<br> - Naujienlaiškio prenumerata<br> - Specialios akcijos ir nuolaidos',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => '',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NĖRA',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Dėkojame.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'vertiname jūsų nuomonę.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Mes jus informuosime, kai prekės kaina nukris žemiau.',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => '',
'PAGE_INFO_CLEARCOOKIE_TITLE' => '',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Dėkojame.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'vertiname jūsų nuomonę.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => '',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Šios prekės yra pageidavimų sąraše',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Jei norite ją/jį nustebinti, nupirkite vieną ar kelias prekes iš šio sąrašo.',
'searchResult' => 'Paieškos rezultatai "%s"',
'simpleDateFormat' => '',
'usrRegistered' => 'Vartotojas bus užregistruotas po slaptažodžio suteikimo',
'view' => 'Peržiūra',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => '',
'WIDGET_LOGINBOX_LOGIN' => '',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => '',
'WIDGET_SERVICES_GUESTBOOK' => '',
'WIDGET_SERVICES_HOME' => '',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => '',
);
