<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: abejingas (188), agladutis (19), linasg (3), muslimukas (5), NFQ Lithuania (2756), swolou (3), tlt (204), vaidasif (75)
 */

$sLangName  = "Lietuvių";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Mėgstamiausių prekių sąrašų sukurta nėra. Norėdami sukurti naują, spauskite',
'ADD_RECOMM_ADDRECOMMLINK2' => 'čia',
'allBrands' => 'All Brands',
'byBrand' => 'Pagal gamintoją',
'byManufacturer' => 'Pagal gamintoją',
'byVendor' => 'Pagal tiekėją',
'DETAILS_ARTNUMBER' => 'Product Nr.:',
'DETAILS_CHOOSEVARIANT' => 'Please select a variant',
'DETAILS_LOCATOR_PRODUCT' => 'PREKĖ',
'DETAILS_PLUSSHIPPING2' => 'shipping costs.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Stebėk kainą',
'DETAILS_VPE_MESSAGE_1' => 'Ši prekė parduodama tik pakuotėmis',
'DETAILS_VPE_MESSAGE_2' => 'purchased.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Pakvietimas nuo',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'apsilankyti',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'to visit.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Product Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NĖRA',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'PVM',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Will be paid by:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Will be shipped with',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Shipping costs (w/o tax):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'plus tax',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'plus tax',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Message: ',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>PAYMENT INFORMATION SWITCHED OFF</b> - To switch them on, please change email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'The order is shipped to:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Product',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Product Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'review',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Nuoroda pirkinio gabenimo sekimui:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'čia',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Please take a minute to rate our shop.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Your',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Team',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stock low',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Kind regards,',
'FOOTER_CATEGORIES' => 'KATEGORIJOS',
'FOOTER_DISTRIBUTORS' => 'TIEKĖJAI',
'FOOTER_INFORMATION' => 'INFORMACIJA',
'FOOTER_MANUFACTURERS' => 'GAMINTOJAI',
'FOOTER_SERVICES' => 'PASLAUGOS',
'FORM_CONTACT_SEND' => 'Send password',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Pakartokite slaptažodį:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Pamiršote slaptažodį?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Vardas',
'FORM_PRICEALARM_SEND' => 'Send',
'FORM_PRIVATESALES_INVITE_FROM' => 'From: ',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Sveiki, pažiūrėkite',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'šiandien radau įdomių prekių, gal sudomins ir tave. Paspauskite ant nuorodos ir būsite nukreiptas tiesiai į el. parduotuvę.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Send invitation',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Sender\'s password: ',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Headline',
'FORM_REGISTER_BILLINGADDRESS' => 'Billing address',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Prašome užpildyti privalomus laukus.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Aš esu informuotas apie savo',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informed.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Aš sutinku su',
'FORM_REGISTER_IAGREETOTERMS3' => 'read and accept them.',
'FORM_SUGGEST_MESSAGE1' => 'Sveiki, pažiūrėkite',
'FORM_SUGGEST_MESSAGE2' => 'šiandien as radau įdomių prekių, gal sudomins ir tave. Paspauskite ant nuorodos ir būsite nukreiptas tiesiai į el. parduotuvę.',
'FORM_USER_BILLINGADDRESS' => 'Billing address',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Pakartokite slaptažodį:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Ieškoti',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Sveiki, aš susikūriau pageidavimų sąrašą',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Būtų smagu jei man ką nors nupirktumėt.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Error while sending - please check your email address.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Tinkeliu',
'infogrid' => 'Dvigubu tinkeliu',
'line' => 'Eilute',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Please fill all fields with a "*"!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'ATSIJUNGTI',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Išsaugoti naują slaptažodį',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Open new account',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Registracijos ir pristatymo adresų informacija',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Jūsų pageidavimų sąrašas buvo išsiųstas sėkmingai:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'dispatched!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Product number',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'PVM',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reason',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Sum of products (incl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Sum of products (excl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Your message:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Billing address',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Shipping address',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Bank account number:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Please fill all fields properly!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Šiuo metu į jūsų pasirinktą šalį nepristatome.</p> <p>Mes rasite jums priimtiną pristatymo būdą ir su jumis susieksime iš karto kai tik galėsimebei aptarsime pristatymo kainas.</p> <p>Jei jūs sutinkate su mūsų sąlygomis, prašome pereiti į kitą žingsnį</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'su PVM',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Grynais',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'Trusted Shops pirkėjo apsauga, apsaugo jūsų pirkimą internetu. Aš sutinku su perdavimu ir',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'saugojimu',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'mano el. pašto adreso dėl pirkėjo Trusted Shops apsaugos duomenų tvarkymo.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Taisyklės',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'pirkėjo apsaugai.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Jūsų užsakymui suteiktas Nr.:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Dėkojame, kad užsakėte',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'in',
'PAGE_CHECKOUT_USER' => 'Dispatch',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Registruotas vartotojas turi pranašumą:<br> - Pristatymo adresų valdymas<br> - Užsakymo statuso tikrinimas<br> - Užsakymų istorija<br> - Prekių atmintinė<br> - Pageidavimų sąrašas<br> - Naujienlaiškio prenumerata<br> - Specialios akcijos ir nuolaidos',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Cancel',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NĖRA',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Dėkojame.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'vertiname jūsų nuomonę.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Mes jus informuosime, kai prekės kaina nukris žemiau.',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Information about Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Dėkojame.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'vertiname jūsų nuomonę.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'News from',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Šios prekės yra pageidavimų sąraše',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Jei norite ją/jį nustebinti, nupirkite vieną ar kelias prekes iš šio sąrašo.',
'searchResult' => 'Paieškos rezultatai "%s"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'Vartotojas bus užregistruotas po slaptažodžio suteikimo',
'view' => 'Peržiūra',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'More ...',
'WIDGET_LOGINBOX_LOGIN' => 'Login',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Product details',
'WIDGET_SERVICES_GUESTBOOK' => 'Guest book',
'WIDGET_SERVICES_HOME' => 'Home',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'More Information',
);
