<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (2202), afimage (504), Espana (5), jsmaster (6), nuelgoz (156)
 */

$sLangName  = "Español";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'No hay listas Listmanía en este momento. Para crear, haga clic en nuevo',
'ADD_RECOMM_ADDRECOMMLINK2' => 'aquí',
'allBrands' => '',
'byBrand' => 'Por Marca',
'byManufacturer' => 'Por Marca',
'byVendor' => 'Por distribuidor',
'DETAILS_ARTNUMBER' => 'Art.:',
'DETAILS_CHOOSEVARIANT' => 'Por favor, seleccione una variante',
'DETAILS_LOCATOR_PRODUCT' => 'PRODUCTO',
'DETAILS_PLUSSHIPPING2' => 'gastos de envío',
'DETAILS_PRICEALARM' => '<b> [!]</ b> Tiendas',
'DETAILS_VPE_MESSAGE_1' => 'Este producto sólo puede ser ordenado en las unidades de envasado de',
'DETAILS_VPE_MESSAGE_2' => 'Este producto sólo puede ser ordenado en las unidades de envasado de',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Una invitación de',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'para visitar',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'Para visitar.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Art.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NINGUNO',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'El pago del IVA de carga',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Forma de pago:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'más IVA',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'más IVA',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Portador del envío:',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Envío (neto):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'más IVA',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'más IVA',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Mensaje:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => '',
'EMAIL_SENDDOWNLOADS_GREETING' => '',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => '',
'EMAIL_SENDDOWNLOADS_SUBJECT' => '',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => '',
'EMAIL_SENDEDNOW_HTML_QUANTITY' => '',
'EMAIL_SENDEDNOW_HTML_REVIEW' => '',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => '',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => '',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => '',
'EMAIL_STOCKREMINDER_SUBJECT' => '',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Muchos saludos',
'FOOTER_CATEGORIES' => 'CATEGORÍAS',
'FOOTER_DISTRIBUTORS' => 'DISTRIBUIDORES',
'FOOTER_INFORMATION' => 'INFORMACIÓN',
'FOOTER_MANUFACTURERS' => 'MARCAS',
'FOOTER_SERVICES' => 'SERVICIO',
'FORM_CONTACT_SEND' => 'Enviar',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Confirmar contraseña:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => '¿Has olvidado tu contraseña?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Nombre:',
'FORM_PRICEALARM_SEND' => 'Enviar',
'FORM_PRIVATESALES_INVITE_FROM' => 'De:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Hola yo estaba mirando',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'algo que se encuentra hoy y que pueden ser interesantes para usted. Basta con hacer clic en el enlace a continuación y que será dirigido a la tienda.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Enviar',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Remitentes de correo electrónico:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Título',
'FORM_REGISTER_BILLINGADDRESS' => 'Dirección de facturación',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Por favor, complete todos los campos marcados con * class=req> span </ span>)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Se me ha informado acerca de mi',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => '',
'FORM_REGISTER_IAGREETOTERMS1' => 'Estoy de acuerdo con la',
'FORM_REGISTER_IAGREETOTERMS3' => '',
'FORM_SUGGEST_MESSAGE1' => 'Hola yo estaba mirando',
'FORM_SUGGEST_MESSAGE2' => 'algo que se encuentra hoy y que pueden ser interesantes para usted. Basta con hacer clic en el enlace a continuación y que será dirigido a la tienda.',
'FORM_USER_BILLINGADDRESS' => 'Dirección de facturación',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Confirmar contraseña:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Búsqueda',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hola he creado una lista de regalos en',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Estupendo si pudiera comprar algo para mí.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Ha ocurrido un error enviando el correo electrónico - por favor consulte la dirección de email.',
'fullDateFormat' => '',
'grid' => 'Grid',
'infogrid' => 'Doble rejilla',
'line' => 'Línea',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Por favor, complete todos los campos correctamente!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => '',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Cambiar la contraseña',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Abrir una cuenta',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Billings y configuración de envío',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Su lista de regalos se ha enviado correctamente a:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Art.:',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Su cupón',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'no podía ser aceptada.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Total:',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Recargo del IVA',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Cantidad:',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'más IVA',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Cantidad:',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Razón:',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'más IVA',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Cantidad:',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Total',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Total de Productos (bruto):',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Productos Total (neto):',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'más IVA',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'más IVA',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Su mensaje:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Dirección de facturación',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Su cupón',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'no podía ser aceptada.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Dirección de envío',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Número de cuenta:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Por favor, complete todos los campos correctamente!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p> Actualmente no tenemos forma de entrega establecido para este país. </ p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'IVA incluido. IVA',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'más',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'COD carga',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'La protección de Trusted Shops comprador asegura su compra en línea. Estoy de acuerdo con la transferencia y',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'ahorro',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'de mi dirección de correo electrónico para el manejo de protección del comprador por Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Condiciones',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'para la protección del comprador.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Se registraron su solicitud con el número:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => '',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Gracias por su pedido',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'en',
'PAGE_CHECKOUT_USER' => 'Dirección',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Un cliente con una cuenta tiene ventajas como: <br>',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Cancelar',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NINGUNO',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Gracias.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'agradece sus comentarios.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Le informaremos tan pronto como el precio cae por debajo',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => '',
'PAGE_INFO_CLEARCOOKIE_TITLE' => '',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Gracias.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'agradece sus comentarios.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Las últimas noticias y novedades en',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Estos productos están en la lista de deseos de',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Si quieres agradar a Dios / ella una compra o varios de estos productos.',
'searchResult' => 'Resultado de la búsqueda para% s',
'simpleDateFormat' => '',
'usrRegistered' => 'El usuario será registrado después de que él siempre su contraseña',
'view' => 'Ver',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => '',
'WIDGET_LOGINBOX_LOGIN' => 'Iniciar sesión',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => '',
'WIDGET_SERVICES_GUESTBOOK' => 'Libro de visitas',
'WIDGET_SERVICES_HOME' => 'Inicio',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Más información ...',
);
