<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: DominikS (404), ET (12), etch (6), i7 (754), lubosdz (18), stefanbalaz (15), tomasadamcik (60), zweistein (1)
 */

$sLangName  = 'Slovenčina';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'HELP_SHOP_THEME_blShowListDisplayType' => 'Rozhodnite sa, či návštevník vášho obchodu môže vybrať typ zoznamu produktov v prednej časti obchodu. Ak tieto možnosti nie sú aktivované, vaši návštevníci uvidia zobrazené zoznamy, ako ste si upravili do rámčeka "Predvolený typ zoznamu produktov".',
'HELP_SHOP_THEME_blSliderShowImageCaption' => 'Titulok je viditeľný, ak má aktívny snímok priradený produkt.',
'HELP_SHOP_THEME_blUseGAEcommerceTracking' => 'Nezabudnite, že táto možnosť musí byť povolená aj vo vašom účte Google Analytics. Manuál:<a href="https://support.google.com/analytics/answer/1009612?hl=en&ref_topic=1037061" target="_blank">Link</a>',
'HELP_SHOP_THEME_iNewBasketItemMessage' => 'Keď zákazník pridá produkty do košíka, OXID eShop sa môže správať inak. Nastavte, čo sa stane, aby zákazník poskytol správnu spätnú väzbu.',
'HELP_SHOP_THEME_sBackgroundColor' => 'Určené ako hexadecimálna hodnota.<br>Napríklad: #D83434',
'HELP_SHOP_THEME_sBackgroundPath' => 'Toto je relatívne k ceste <code>/out/flow/img/backgrounds/</code>.',
'HELP_SHOP_THEME_sBlogUrl' => 'Napríklad: http://blog.oxid-esales.com',
'HELP_SHOP_THEME_sCatIconsize' => 'V zobrazení kategórie sa zobrazujú kategórie obrázkov podkategórií v definovanej veľkosti.',
'HELP_SHOP_THEME_sCatPromotionsize' => 'Propagácia kategórie na úvodnej stránke potrebuje špeciálnu veľkosť obrázkov kategórie. Tu definujte veľkosť týchto obrázkov.',
'HELP_SHOP_THEME_sCatThumbnailsize' => 'V zobrazení kategórie sa zobrazuje obrázok vybranej kategórie v definovanej veľkosti.',
'HELP_SHOP_THEME_sDeliveryDaysNotOnStock' => 'Odhadovaný dátum, od ktorého očakávate doručenie objednávky zákazníkovi. Ak objednávka obsahuje viac položiek, vyberte najnovší dátum doručenia. Ak oznámete niekoľko dní, uveďte prosím neskorší koniec rozsahu. (Napr. 7 dní, ak je váš rozsah 5-7 dní).',
'HELP_SHOP_THEME_sDeliveryDaysOnStock' => 'Odhadovaný dátum, od ktorého očakávate doručenie objednávky zákazníkovi. Ak objednávka obsahuje viac položiek, vyberte najnovší dátum doručenia. Ak oznámete niekoľko dní, uveďte prosím neskorší koniec rozsahu. (Napr. 7 dní, ak je váš rozsah 5-7 dní).',
'HELP_SHOP_THEME_sEmailLogo' => 'Toto je relatívne k ceste <code>/out/flow/img/</code>.',
'HELP_SHOP_THEME_sFacebookUrl' => 'Napríklad: https://www.facebook.com/oxidesales',
'HELP_SHOP_THEME_sFaviconFile' => 'Táto favikón sa má zobrazovať na karte prehliadača. <br> Vo všeobecnosti ide o súbor ico. <br> Je to relatívne k ceste <code>/out/flow/img/favicons/</code>.',
'HELP_SHOP_THEME_sFaviconMSTileColor' => 'Určené ako hexadecimálna hodnota.<br>Napríklad: #D83434',
'HELP_SHOP_THEME_sGATrackingId' => 'Napríklad: UA-XXXXXXXX-1',
'HELP_SHOP_THEME_sGoogleMapsAddr' => 'Napríklad: OXID eSales AG, Bertoldstraße 48, 79098 Freiburg',
'HELP_SHOP_THEME_sGooglePlusUrl' => 'Napríklad: https://plus.google.com/114133952363540971062',
'HELP_SHOP_THEME_sGoogleShoppingAccountId' => 'Zadajte toto pole len vtedy, ak odovzdáte informačné kanály pre službu Nákupy Google. <br> <br> ID účtu Google Merchant Center. Táto hodnota by mala zodpovedať ID účtu, ktorý používate na odoslanie <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a> Prostredníctvom služby Google Merchant Center. Ak máte účet MCA, použite ID podúčtu priradeného k danému informačnému kanálu produktu.',
'HELP_SHOP_THEME_sGoogleVendorId' => 'Toto ID nájdete v informačnom paneli Dôveryhodných obchodov - Trusted Stores Merchant Dashboard.',
'HELP_SHOP_THEME_sIconsize' => 'Icons are the smallest pictures of a product. They are used: <br><ul><li>in the shopping cart.</li><li>if products are shown in the right menu (e.g. in <span class="filename_filepath_or_italic">TOP of the Shop</span> and <span class="filename_filepath_or_italic">Bargain</span>).</li></ul>For avoiding design issues caused by too big icons the icons are resized. Enter the maximum size for icons here.',
'HELP_SHOP_THEME_sLogoFile' => 'This is relative to the path <code>/out/flow/img/</code>.',
'HELP_SHOP_THEME_sLogoHeight' => 'Specify in as a pixel value.',
'HELP_SHOP_THEME_sLogoWidth' => 'Specify in as a pixel value.',
'HELP_SHOP_THEME_sManufacturerIconsize' => 'Manufacturer\'s/brand logo is shown on start page in manufacturer\'s slider.',
'HELP_SHOP_THEME_sPageLanguage' => 'The locale should be in the format of <language>_<country><br><br><Language> is a two-letter language code defined in ISO 639-1, and <country> is a two-letter country code defined in ISO 3166-1 alpha-2. Usually <country> should be all capitalized, and <language> should be in lowercase. e.g. en_US, en_GB, en_AU, fr_FR, de_DE, or ja_JP.',
'HELP_SHOP_THEME_sShippingDaysNotOnStock' => 'Predpokladaný termín, pri ktorom bude odoslaná objednávka; To sa líši od predpokladaného dátumu dodania. <br> V prípade, že objednávka bude obsahovať viac položiek. vyberte posledný približný dátum odoslania. <br> Ak je hlásenie zákazníkom v rozsahu dní. uveďte koniec rozsahu. (Napríklad 7 dní, ak váš rozsah pre prepravu je 5-7 dní). <br> Dátum tu uvedený bude poskytovaný zákazníkovi prostredníctvom e-mailu. <br> Zákazník dostane prehľad potvrdenia, že lehota nákupu približný dátum odoslania vypršala.',
'HELP_SHOP_THEME_sShippingDaysOnStock' => 'Tu sa jedná o približný dátum odoslania objednávky; nejedná sa o predpokladaný dátum dodania.<br><br>Pokiaľ objednávka obsahuje viac produktov, zvoľte to najvzdialenejší predpokladaný dátum odoslania.<br><br>Pokiaľ udávate zákazníkovi časový interval, zadajte posledný deň tohoto úseku. Pokiaľ napr. zasielate v rozmedzí od 5 do 7 dní, zadajte 7 dní.<br><br>Tento tu zadaný termín bude zákazníkovi oznámený e-mailom.<br><br>Po predpokladanom dátume odoslania bude zákazníkovi odoslaný dotazník ohľadom nákupu.',
'HELP_SHOP_THEME_sShoppingCountry' => 'Provide this field only if you submit feeds for Google Shopping.<br><br>Account country from Google Shopping. This value should match the account country you use to submit your <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a>.<br><br>The value of the country parameter should be a <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">two-letter ISO 3166 country code</a>.<br><br>For example, values could be US, GB, AU, FR, DE, JP.',
'HELP_SHOP_THEME_sShoppingLanguage' => 'Provide this field only if you submit feeds for Google Shopping.<br><br>Account language from Google Shopping. This value should match the account language you use to submit your <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a>.<br><br>The value of the language parameter should be a <a href="http://en.wikipedia.org/wiki/ISO_639-1" target="_blank">two-letter ISO 639-1 language code</a>.<br><br>For example, values could be en, fr, de, ja.',
'HELP_SHOP_THEME_sThumbnailsize' => 'Thumbnails are small product pictures. They are used:<br><ul><li>in product lists.</li><li>in promotions displayed in the middle of the front page, e. g. <span class="filename_filepath_or_italic">Just arrived!</span>.</li></ul>For avoiding design issues caused by too big thumbnails the thumbnails are resized. Enter the maximum size for thumbnails here.',
'HELP_SHOP_THEME_sTwitterUrl' => 'Napríklad: https://twitter.com/OXID_eSales',
'HELP_SHOP_THEME_sYouTubeUrl' => 'Napríklad: https://www.youtube.com/user/oxidesales',
'SHOP_THEME_aDetailImageSizes' => 'Product picture size (width*height)',
'SHOP_THEME_aNrofCatArticles' => 'Number of products which can be shown in a product lists (category pages, search results)<br><br>Attention: A large number of products per page (above 100) can cause performance loss!',
'SHOP_THEME_aNrofCatArticlesInGrid' => 'Grid view: Number of products which can be shown in a product lists (category pages, search results)<br><br>Attention: A large number of products per page (above 100) can cause performance loss!',
'SHOP_THEME_blBackgroundAttachment' => 'Fix background while scrolling?',
'SHOP_THEME_blEcondaRecommendationsBasket' => 'Show recommendations in basket',
'SHOP_THEME_blEcondaRecommendationsDetails' => 'Show recommendations on details page',
'SHOP_THEME_blEcondaRecommendationsList' => 'Show recommendations in listings',
'SHOP_THEME_blEcondaRecommendationsStart' => 'Show recommendations on home page',
'SHOP_THEME_blEmailsShowProductPictures' => 'Show product pictures in emails',
'SHOP_THEME_blFooterShowGuestbook' => 'Use guestbook link',
'SHOP_THEME_blFooterShowHelp' => 'Use help link',
'SHOP_THEME_blFooterShowLinks' => 'Use Links link',
'SHOP_THEME_blFooterShowNews' => 'Use news link',
'SHOP_THEME_blFooterShowNewsletter' => 'Use newsletter link',
'SHOP_THEME_blFooterShowNewsletterForm' => 'Use newsletter form',
'SHOP_THEME_blFullwidthLayout' => 'Activate full with layout',
'SHOP_THEME_blGAAnonymizeIPs' => 'Anonymize IP-Adresses',
'SHOP_THEME_blShowBirthdayFields' => 'Display input fields for date of birth when users enter their personal data',
'SHOP_THEME_blShowFinalStep' => 'Show order confirmation after order is finished (5th Step in Checkout)',
'SHOP_THEME_blShowListDisplayType' => 'Display product list type selector',
'SHOP_THEME_blSliderShowImageCaption' => 'Activate captions for slider on home page',
'SHOP_THEME_blUseBackground' => 'Show background-image',
'SHOP_THEME_blUseGAEcommerceTracking' => 'Use Google Analytics Ecommerce Tracking',
'SHOP_THEME_blUseGAPageTracker' => 'Use Google Analytics PageTracker',
'SHOP_THEME_blUseGoogleTS' => 'Use Google Trusted Stores',
'SHOP_THEME_bl_showCompareList' => 'Use compare list',
'SHOP_THEME_bl_showGiftWrapping' => 'Use gift wrapping',
'SHOP_THEME_bl_showListmania' => 'Use listmania',
'SHOP_THEME_bl_showManufacturerSlider' => 'Show manufacturer slider on Start page',
'SHOP_THEME_bl_showVouchers' => 'Use vouchers',
'SHOP_THEME_bl_showWishlist' => 'Use gift registry',
'SHOP_THEME_GROUP_background' => 'Background-image',
'SHOP_THEME_GROUP_contact' => 'Contact',
'SHOP_THEME_GROUP_display' => 'Display',
'SHOP_THEME_GROUP_econda' => 'econda Web Shop Controlling',
'SHOP_THEME_GROUP_emails' => 'E-Mails',
'SHOP_THEME_GROUP_favicons' => 'Favicons',
'SHOP_THEME_GROUP_features' => 'Features',
'SHOP_THEME_GROUP_footer' => 'Footer',
'SHOP_THEME_GROUP_googleanalytics' => 'Google Analytics',
'SHOP_THEME_GROUP_googlets' => 'Google Trusted Stores',
'SHOP_THEME_GROUP_header' => 'Header',
'SHOP_THEME_GROUP_images' => 'Images',
'SHOP_THEME_GROUP_logo' => 'Logo',
'SHOP_THEME_iNewBasketItemMessage' => 'Select action when product is added to cart',
'SHOP_THEME_iNewBasketItemMessage_0' => 'None',
'SHOP_THEME_iNewBasketItemMessage_1' => 'Display message',
'SHOP_THEME_iNewBasketItemMessage_2' => 'Open popup',
'SHOP_THEME_iNewBasketItemMessage_3' => 'Open basket',
'SHOP_THEME_iTopNaviCatCount' => 'Amount of categories that is displayed at top',
'SHOP_THEME_sBackgroundColor' => 'Background-color of shop',
'SHOP_THEME_sBackgroundPath' => 'Filename of background-image',
'SHOP_THEME_sBackgroundPosHorizontal' => 'Horizontal position of the background-image',
'SHOP_THEME_sBackgroundPosHorizontal_center' => 'centered',
'SHOP_THEME_sBackgroundPosHorizontal_left' => 'left',
'SHOP_THEME_sBackgroundPosHorizontal_right' => 'right',
'SHOP_THEME_sBackgroundPosVertical' => 'Vertical position of the background-image',
'SHOP_THEME_sBackgroundPosVertical_bottom' => 'bottom',
'SHOP_THEME_sBackgroundPosVertical_center' => 'centered',
'SHOP_THEME_sBackgroundPosVertical_top' => 'top',
'SHOP_THEME_sBackgroundRepeat' => 'Repeat background-image?',
'SHOP_THEME_sBackgroundRepeat_no-repeat' => 'No',
'SHOP_THEME_sBackgroundRepeat_repeat' => 'Yes, horizontal und vertical',
'SHOP_THEME_sBackgroundRepeat_repeat-x' => 'Yes, horizontal',
'SHOP_THEME_sBackgroundRepeat_repeat-y' => 'Yes, vertical',
'SHOP_THEME_sBackgroundSize' => 'Background-image size',
'SHOP_THEME_sBackgroundSize_contain' => 'cover (full width)',
'SHOP_THEME_sBackgroundSize_cover' => 'cover (full height)',
'SHOP_THEME_sBackgroundSize_normal' => 'Keep original size',
'SHOP_THEME_sBlogUrl' => 'Blog-URL',
'SHOP_THEME_sCatIconsize' => 'Size of a subcategory\'s picture (width*height)',
'SHOP_THEME_sCatPromotionsize' => 'Category picture size for promotion on startpage (width*height)',
'SHOP_THEME_sCatThumbnailsize' => 'Category picture size (width*height)',
'SHOP_THEME_sDefaultListDisplayType' => 'Default product list type',
'SHOP_THEME_sDefaultListDisplayType_grid' => 'Grid',
'SHOP_THEME_sDefaultListDisplayType_infogrid' => 'Double grid',
'SHOP_THEME_sDefaultListDisplayType_line' => 'List',
'SHOP_THEME_sDeliveryDaysNotOnStock' => 'Amount of days till delivery of an order that has <b>not</b> all articles in stock.',
'SHOP_THEME_sDeliveryDaysOnStock' => 'Amount of days till delivery of an order that has all articles in stock.',
'SHOP_THEME_sEcondaWidgetIdBasket' => 'Recommendation-Widget-ID für Warenkorb',
'SHOP_THEME_sEcondaWidgetIdDetails' => 'Recommendation-Widget-ID für Detailseite',
'SHOP_THEME_sEcondaWidgetIdList' => 'Recommendation-Widget-ID für Listenansicht',
'SHOP_THEME_sEcondaWidgetIdStart' => 'Recommendation widget ID for home page',
'SHOP_THEME_sEmailLogo' => 'File name of logo for email header',
'SHOP_THEME_sFacebookUrl' => 'Facebook Page-URL',
'SHOP_THEME_sFavicon128File' => 'File name of the favicon with 128*128px.',
'SHOP_THEME_sFavicon16File' => 'File name of the favicon with 16*16px',
'SHOP_THEME_sFavicon32File' => 'File name of the favicon with 32*32px',
'SHOP_THEME_sFavicon48File' => 'File name of the favicon with 48*48px',
'SHOP_THEME_sFavicon512File' => 'File name of the favicon with 512*512px',
'SHOP_THEME_sFavicon64File' => 'File name of the favicon with 64*64px',
'SHOP_THEME_sFaviconFile' => 'Favicon file name',
'SHOP_THEME_sFaviconMSTileColor' => 'Tile color for Windows 8/Windows Mobile bookmarks.',
'SHOP_THEME_sGATrackingId' => 'Google Analytics Tracking-ID',
'SHOP_THEME_sGoogleMapsAddr' => 'Your postal address',
'SHOP_THEME_sGooglePlusUrl' => 'Google+ Page-URL',
'SHOP_THEME_sGoogleShoppingAccountId' => 'Google Shopping Account-ID (optional)',
'SHOP_THEME_sGoogleVendorId' => 'Google Store-ID',
'SHOP_THEME_sIconsize' => 'Icon size (width*height)',
'SHOP_THEME_sLogoFile' => 'Filename of logo',
'SHOP_THEME_sLogoHeight' => 'Height of header logo',
'SHOP_THEME_sLogoWidth' => 'Width of header logo',
'SHOP_THEME_sManufacturerIconsize' => 'Manufacturer\'s/brand logo size',
'SHOP_THEME_sPageLanguage' => 'Language of your Shop in ISO',
'SHOP_THEME_sShippingDaysNotOnStock' => 'Počet dní do odoslania objednávky, v prípade že aspoň 1 produkt nie je skladom.(povinné)',
'SHOP_THEME_sShippingDaysOnStock' => 'Počet dní do odoslania objednávky s produktami, ktoré sú všetky skladom. (povinné)',
'SHOP_THEME_sShoppingCountry' => 'Google Shopping-Feed Country (optional)',
'SHOP_THEME_sShoppingLanguage' => 'Google Shopping-Feed Sprache (optional)',
'SHOP_THEME_sStartPageListDisplayType' => 'Product list type on Start page',
'SHOP_THEME_sStartPageListDisplayType_grid' => 'Grid',
'SHOP_THEME_sStartPageListDisplayType_infogrid' => 'Double grid',
'SHOP_THEME_sStartPageListDisplayType_line' => 'List',
'SHOP_THEME_sThumbnailsize' => 'Thumbnail size (width*height)',
'SHOP_THEME_sTwitterUrl' => 'Twitter Profile-URL',
'SHOP_THEME_sYouTubeUrl' => 'YouTube Channel-URL',
'SHOP_THEME_sZoomImageSize' => 'Zoom picture size (width*height)',
);
