<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */
$sLangName  = "English";
// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = [
'BACK_TO_OVERVIEW' => 'لمحة عامة',
'DD_BASKET_BACK_TO_SHOP' => 'العودة لتسوق',
'DD_CLOSE_MODAL' => 'اغلاق',
'DD_CONTACT_ADDRESS_HEADING' => 'العنوان',
'DD_CONTACT_FORM_HEADING' => 'الاتصال',
'DD_CONTACT_PAGE_HEADING' => 'اتصل بنا',
'DD_CONTACT_THANKYOU1' => 'شكرا لك',
'DD_CONTACT_THANKYOU2' => 'تعرب عن تقديرها للتعليقات الخاصة بك.',
'DD_DEMO_ADMIN_TOOL' => 'واجهة الإدارة المفتوحة',
'DD_DOWNLOADLINKS_HEADING' => 'وصلات التحميل الخاص بك--أوامر',
'DD_DOWNLOADS_DOWNLOAD_TOOLTIP' => 'تحميمل',
'DD_ERR_404_CONTACT_BUTTON' => 'الى صفحة الاتصال',
'DD_ERR_404_CONTACT_TEXT' => 'ربما يمكننا مساعدتك؟ 
لا تتردد في الاتصال بنا أو كتابة رسالة بريد إلكتروني:',
'DD_ERR_404_START_BUTTON' => 'اذهب الى الصفحة الرئيسية',
'DD_ERR_404_START_TEXT' => 'قد تجد المعلومات المطلوبة من الصفحة الرئيسية:',
'DD_FILE_ATTRIBUTES_FILENAME' => 'اسم الملف',
'DD_FILE_ATTRIBUTES_FILESIZE' => 'حجم الملف',
'DD_FILE_ATTRIBUTES_OCLOCK' => 'مساء',
'DD_FOOTER_CONTACT_INFO' => 'اِتِّصال',
'DD_FOOTER_FOLLOW_US' => 'اتبعنا',
'DD_FORGOT_PASSWORD_HEADING' => 'انسى كلمة السر',
'DD_FORM_VALIDATION_CHECKONE' => 'من فضلك اختر على الافل خيار واحد',
'DD_FORM_VALIDATION_INTEGER' => 'وهناك  لا يسمح بلأعداد العشرية',
'DD_FORM_VALIDATION_NEGATIVENUMBER' => 'من فضلك ادخل اعداد سالبه',
'DD_FORM_VALIDATION_NUMBER' => 'من فضلك ادخل رقم',
'DD_FORM_VALIDATION_PASSWORDAGAIN' => 'كلمة السر غير متطابقة',
'DD_FORM_VALIDATION_POSITIVENUMBER' => 'من فضلك ادخل رقم موجب',
'DD_FORM_VALIDATION_REQUIRED' => 'الرجاء تحديد قيمة لهذا الحقل المطلوب.',
'DD_FORM_VALIDATION_VALIDEMAIL' => 'الرجاء إدخال عنوان بريد إلكتروني صالح.',
'DD_GUESTBOOK_ENTRIES' => 'مداخل',
'DD_GUESTBOOK_ENTRY_FROM' => 'عند',
'DD_GUESTBOOK_ENTRY_ON' => 'على',
'DD_INVITE_HEADING' => 'أداةالتوصية',
'DD_INVITE_LINK' => 'رابط',
'DD_LINKS_NO_ENTRIES' => 'ولسوء الحظ، لا تتوفر أية روابط.',
'DD_LISTLOCATOR_FILTER_ATTRIBUTES' => 'مرشحات',
'DD_LIST_SHOW_MORE' => 'عرض المنتجات.',
'DD_LOGIN_ACCOUNT_PANEL_CREATE_BODY' => 'عن طريق إنشاء حساب في متجرنا، سيتم توجيهك خلال عملية الخروج بشكل أسرع. وبالإضافة إلى ذلك، يمكنك تخزين عدة عناوين الشحن وتتبع أوامر في الحساب الخاص بك.',
'DD_LOGIN_ACCOUNT_PANEL_CREATE_TITLE' => 'افتح حساب',
'DD_LOGIN_ACCOUNT_PANEL_LOGIN_TITLE' => 'تسجيل دخول',
'DD_MINIBASKET_CONTINUE_SHOPPING' => 'استمرار التسوق',
'DD_MINIBASKET_MODAL_TABLE_PRICE' => 'كلي',
'DD_MINIBASKET_MODAL_TABLE_TITLE' => 'اداة',
'DD_NEWSLETTER_OPTIN_HEADING' => 'الاشتراك في النشرة الإخبارية الخاصة بك',
'DD_ORDERSHIPPED_HEADING' => 'تأكيد التسليم--ترتيب',
'DD_ORDER_CUST_HEADING' => 'ترتيب',
'DD_ORDER_ORDERDATE' => 'التاريخ',
'DD_OWNER_REMINDER_HEADING' => 'الأسهم المنخفضة',
'DD_PRICEALARM_HEADING' => 'إنذار السعر',
'DD_PRODUCTMAIN_STOCKSTATUS' => 'أَسْهُم',
'DD_RATING_CUSTOMERRATINGS' => 'ملاحظات العملاء',
'DD_RECOMMENDATION_EDIT_BACK_TO_LIST' => 'العودة الى الملاحظات',
'DD_REGISTER_HEADING' => 'تسجيلاتك',
'DD_ROLES_BEMAIN_UIROOTHEADER' => 'القائمة',
'DD_SIDEBAR_CATEGORYTREE' => 'الاصناف',
'DD_SIDEBAR_TAGCLOUD' => 'الايام',
'DD_SORT_ASC' => 'تصاعدي',
'DD_SORT_DESC' => 'تنازلي',
'DD_SUGGEST_HEADING' => 'أداة التوصية',
'DD_USER_BILLING_LABEL_STATE' => 'الحالة',
'DD_USER_SHIPPING_ADD_DELIVERY_ADDRESS' => 'اضف عنوان التوصيل',
'DD_USER_SHIPPING_LABEL_STATE' => 'الحالة',
'DD_USER_SHIPPING_SELECT_ADDRESS' => 'اختار',
'DD_WISHLIST_HEADING' => 'قائمة التمني',
'DETAILS_VPE_MESSAGE_1' => 'هذا المنتج يمكن أن يطلب فقط في وحدات التعبئة والتغليف',
'DETAILS_VPE_MESSAGE_2' => 'الاسعار',
'FOOTER_NEWSLETTER_INFO' => 'الحصول على معلومات حول أحدث المنتجات والعروض في البريد الإلكتروني.',
'MANUFACTURERSLIDER_SUBHEAD' => 'ونقدم منتجاتنا مختارة بعناية، يمكن الاطلاع على منتجاتها في متجر.',
'OF' => 'من',
'PAGE_DETAILS_CUSTOMERS_ALSO_BOUGHT_SUBHEADER' => '',
'SEARCH_SUBMIT' => '',
'SEARCH_TITLE' => '',
'START_BARGAIN_HEADER' => '',
'START_BARGAIN_SUBHEADER' => '',
'START_NEWEST_HEADER' => '',
'START_NEWEST_SUBHEADER' => '',
'START_TOP_PRODUCTS_HEADER' => '',
'START_TOP_PRODUCTS_SUBHEADER' => '',
'WIDGET_PRODUCT_RELATED_PRODUCTS_ACCESSORIES_SUBHEADER' => '',
'WIDGET_PRODUCT_RELATED_PRODUCTS_CROSSSELING_SUBHEADER' => '',
'WIDGET_PRODUCT_RELATED_PRODUCTS_SIMILAR_SUBHEADER' => '',
];
