<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (367), gvlimpt (97), marco (932)
 */

$sLangName  = "Nederlands";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'U heeft op dit moment geen favorieten. Om een lijst met favorieten aan te maken, klik',
'ADD_RECOMM_ADDRECOMMLINK2' => 'hier',
'BETA_NOTE' => '',
'BETA_NOTE_CLOSE' => '',
'byBrand' => 'Op merk',
'byManufacturer' => 'Op fabrikant',
'byVendor' => 'Op leverancier',
'DETAILS_ARTNUMBER' => 'Art.nr.:',
'DETAILS_CHOOSEVARIANT' => 'Kies een variant a.u.b.',
'DETAILS_LOCATOR_PRODUCT' => 'ARTIKEL',
'DETAILS_PLUSSHIPPING2' => 'Verzendkosten',
'DETAILS_PRICEALARM' => '<b>[!]</b> Prijsalarm!',
'DETAILS_VPE_MESSAGE_1' => 'Dit artikel wordt slechts per',
'DETAILS_VPE_MESSAGE_2' => 'verkocht.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Een uitnodiging van',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => '',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'te bezoeken.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Art.nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'GEEN',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Toeslag betaalwijze btw',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'U betaalt met:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'excl. btw',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'excl. btw',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'We verzenden met',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Verzendkosten (netto):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'excl. btw',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'excl. btw',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Mededeling:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>BETAALINFORMATIE UITGESCHAKELD</b> - om deze in te schakelen a.u.b. email_order_owner_html.tpl veranderen.',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Vriendeijke groeten,',
'FOOTER_CATEGORIES' => 'CATEGORIEN',
'FOOTER_DISTRIBUTORS' => 'LVERANCIERS',
'FOOTER_INFORMATION' => 'INFORMATIE',
'FOOTER_MANUFACTURERS' => 'MERKEN',
'FOOTER_SERVICES' => 'SERVICE',
'FORM_CONTACT_SEND' => 'Bericht versturen',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Wachtwoord herhalen:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Wachtwoord vergeten?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Voornaam',
'FORM_PRICEALARM_SEND' => 'versturen',
'FORM_PRIVATESALES_INVITE_FROM' => 'Van:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Hallo! Vandaag heb ik een interessante Webshop',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'voor jou gevonden. Via de onderstaande link kom je direct in de Shop.',
'FORM_PRIVATESALES_INVITE_SEND' => 'uitnodiging versturen',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'E-mail van de afzender:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Koptext',
'FORM_REGISTER_BILLINGADDRESS' => 'factuuradres',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(A.u.b. alle vet gemarkeerde velden invullen.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Ik heb de informatie over mijn',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'gelezen.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Ik heb de',
'FORM_REGISTER_IAGREETOTERMS3' => 'gelezen en ga met deze voorwaarden akkoord.',
'FORM_SUGGEST_MESSAGE1' => 'Hallo, Vandaag heb ik een interessante Webshop',
'FORM_SUGGEST_MESSAGE2' => 'voor jou gevonden. Via de onderstaande link kom je direct in de Shop.',
'FORM_USER_BILLINGADDRESS' => 'Factuuradres',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Wachtwoord herhalen:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Nu zoeken',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hallo, ik heb bij',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => 'een verlanglijstje gemaakt. Ik zou het fijn vinden, als je me daar iets van schenkt.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Fout bij het versturen - controleer het e-mailadres a.u.b.',
'fullDateFormat' => 'd.m.Y H:i:s',
'grid' => 'Galerij',
'infogrid' => 'Galerij twee kolommen',
'line' => 'Lijst',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'A.u.b. alle velden met een * invullen!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'UITLOGGEN',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Nieuw wachtwoord opslaan',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Nieuw account aanmaken',
'PAGE_ACCOUNT_USER_USERTITLE' => '',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Uw verlanglijste is succesvol naar',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'gestuurd!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Artikel Nr.',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Uw tegoedbon',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'is ongeldig.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Totaalbedrag',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Toeslag Betaalwijze btw',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% bedrag',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'excl. btw',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% bedrag',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reden',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'excl. btw',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% bedrag',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Totaalbedrag',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Totaal Artikel (bruto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Totaal Artikel (netto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'excl. btw',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'excl. btw',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Uw tekst:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'factuuradres',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Uw tegoedbon',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'is ongeldigd.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Afleveradres',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Rekeningnummer:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'A.u.b. alle velden correct invullen!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Op dit moment is geen verzending naar dit land mogelijk.</p> <p>Als u wilt dat wij een verzendmogelijkheid voor u zoeken, klik dan op "verder".</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'incl. btw',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'excl.',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'rembourskosten',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'De Trusted Shops consumentenbescherming garandeert uw online-aankoop. Ik ben akkoord met het doorgeven en',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'het opslaan',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'van mijn e-mailadres voor het afwikkelen van de consumentenbescherming door Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Voorwaarden',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'voor de consumentenbescherming.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Uw bestelling is onder het nummer',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'bij ons geregistreerd.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'hartelijk dank voor uw bestelling',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'in',
'PAGE_CHECKOUT_USER' => 'Verzenden',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Met een persoonlijk klantaccount heeft u de volgende voordelen:<br> - beheer van afleveradressen<br> - contoleren van de bestelstatus<br> - bestelgeschiedenis<br> - persoonlijke favorieten<br> - persoonlijk verlanglijstje<br> - aanpassen van nieuwsbrief-instellingen<br> - speciale aanbiedingen en kortingsacties',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Annuleren',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'Geen',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Hartelijk dank voor uw bericht aan',
'PAGE_DETAILS_THANKYOUMESSAGE2' => '.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'U krijgt een bericht zodra de prijs onder',
'PAGE_DETAILS_THANKYOUMESSAGE4' => 'komt.',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Hartelijk dank voor uw bericht aan',
'PAGE_INFO_CONTACT_THANKYOU2' => '.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Nieuwtjes bij',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Deze producten staat op het verlanglijstje van',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => 'Als u hem/haar een passend cadeau wilt geven, geef dan een of meerdere van deze producten.',
'priceFrom' => '<span class="pricefrom">vanaf</span>',
'searchResult' => 'Zoekresultaat voor "%s"',
'simpleDateFormat' => 'd.m.Y',
'usrRegistered' => 'De gebruiker wordt na het invullen van zijn wachtwoord geregistreerd',
'view' => 'Beeld',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Meer...',
'WIDGET_LOGINBOX_LOGIN' => '',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Productdetails',
'WIDGET_SERVICES_GUESTBOOK' => 'Gasteboek',
'WIDGET_SERVICES_HOME' => 'Startpagina',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Meer informatie',
);
