<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: crashover (330), fifo (9), marco (1), val (933)
 */

$sLangName  = 'Български';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'внимание',
'BUTTON_BEGIN_INSTALL' => 'Стартиране на инсталацията',
'BUTTON_DB_INSTALL' => 'Създай база данни',
'BUTTON_LICENCE' => 'Продължи',
'BUTTON_PROCEED_INSTALL' => 'Продължи инсталацията',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Инсталирай демо база данни',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Приемам условията на лицанза.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Не приемам условията на лиценза.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Не</strong> инсталирай демо база данни',
'BUTTON_START_INSTALL' => 'Рестартирай инсталацията',
'BUTTON_WRITE_DATA' => 'Запази и продължи',
'BUTTON_WRITE_LICENCE' => 'Запази лицензионния код',
'ERROR_BAD_DEMODATA' => 'Грешка: Проблем при запис база данни:',
'ERROR_BAD_SERIAL_NUMBER' => 'Грешен лицензионен код!',
'ERROR_BAD_SQL' => 'ГРЕШКА: Проблем с внасяне на SQL отчет:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ГРЕШКА: %s/config.inc.php няма права за писане!',
'ERROR_COULD_NOT_CREATE_DB' => 'ГРЕШКА: База данни не съществува и не може да бъде създадена!',
'ERROR_COULD_NOT_FIND_FILE' => 'Инсталатора не може да намери "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Не може да се отвори %s за четене! Моля прегледайте FAQ, форума или се свържете с  OXID Support!',
'ERROR_COULD_NOT_READ_FILE' => 'Инсталатора не може да отвори "%s" за четене!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Инсталатора не може да пише в "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ГРЕШКА: Вероятно вече има инсталиран OXID eShop в база данни %s. Моля изтрийте преди да продължите!',
'ERROR_DB_CONNECT' => 'ГРЕШКА: Няма връзка с база данни!',
'ERROR_FILL_ALL_FIELDS' => 'ГРЕШКА: Моля попълнете всички необходими полета!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Версията на MySQL не отговаря на системните изисквания',
'ERROR_NOT_AVAILABLE' => 'ГРЕШКА: %s не е намерена!',
'ERROR_NOT_WRITABLE' => 'ГРЕШКА: %s няма права за писане!',
'ERROR_OPENING_SQL_FILE' => 'Не може да се отвори SQL файла %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Паролите не съвпадат!',
'ERROR_PASSWORD_TOO_SHORT' => 'Паролата е твърде къса!',
'ERROR_SETUP_CANCELLED' => 'Инсталацията е отменена поради неприемане на лицензионните условия.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Моля въведете валиден e-mail!',
'ERROR_VIEWS_CANT_CREATE' => 'ГРЕШКА: Моля проверете правата на потребителя на база данни.',
'ERROR_VIEWS_CANT_DROP' => 'ГРЕШКА: Моля проверете правата на потребителя на база данни.',
'ERROR_VIEWS_CANT_SELECT' => 'Моля проверете правата на потребителя на база данни',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop съветник за инсталиране',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Ако инсталацията не продължи след секунди натисни',
'HERE' => 'тук',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Ако има отметка, ще видите допълнително меню в админ панела на OXID eShop.</p><p>В това меню ще получите допълнителна информация за eCommerce услуги, като Google product search.</p> <p>Може да смените тези настройки оп всяко време.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen или fsockopen към порт 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Възможни проблеми със сървъра поради бъгове в PHP',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'качването на файлове е разрешено (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] вкл. JPEG поддръжка',
'MOD_INI_SET' => 'ini_set разрешено',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MEMORY_LIMIT' => 'Лимит на PHP памет (мин. 14MB, 30MB препоръчително)',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite модул',
'MOD_MYSQL_CONNECT' => 'MySQL client connector за MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend съвместимост трябва да е изключена (off)',
'MOD_PHP_CONFIG' => 'PHP конфигурация',
'MOD_PHP_EXTENNSIONS' => 'PHP разширения',
'MOD_PHP_VERSION' => 'PHP версия поне 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals трябва да е off',
'MOD_REQUEST_URI' => 'Определи REQUEST_URI',
'MOD_SERVER_CONFIG' => 'Конфигурация на сървъра',
'MOD_SERVER_PERMISSIONS' => 'Права на достъп до файлове/папки',
'MOD_SESSION_AUTOSTART' => 'session.auto_start трябва да е off',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 поддръжка',
'MOD_ZEND_OPTIMIZER' => 'Инсталиран Zend Optimizer или Zend Guard Loader',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Инсталирана Zend платформа или Zend сървър',
'PRIVACY_POLICY' => 'декларация за конфиденциалност',
'SELECT_COUNTRY_LANG' => 'Изберете държава',
'SELECT_DELIVERY_COUNTRY' => 'Основна държава за доставка',
'SELECT_DELIVERY_COUNTRY_HINT' => 'Ако е необходимо, активирайте повече държави за доставка в админ панела.',
'SELECT_PLEASE_CHOOSE' => 'Моля изберете',
'SELECT_SETUP_LANG' => 'Език на инсталатора',
'SELECT_SETUP_LANG_HINT' => 'Ако е необходимо, активирайте повече езици в админ панела.',
'SELECT_SETUP_LANG_SUBMIT' => 'Избери',
'SELECT_SHOP_LANG' => 'език на магазина',
'SELECT_SHOP_LANG_HINT' => 'Ако е необходимо, активирайте повече езици в админ панела.',
'SELECT_SHOP_LOCATION' => 'Вашия пазар',
'SELECT_SHOP_LOCATION_HINT' => 'Моля изберете пазара, към който е ориентиран магазина. Според това, допълнителни услуги ще бъдат добавени от OXID server, ако разрешите.',
'SETUP_CONFIG_PERMISSIONS' => 'От съображения за сигурност, дайте права само за четене на config.inc.php!',
'SETUP_DIR_DELETE_NOTICE' => 'От съображения за сигурност, изтрийте setup папката, ако не е изтрита при инсталацията.',
'STEP_0_DESC' => 'В тази стъпка ще проверим дали системата отговаря на изискванията:',
'STEP_0_ERROR_TEXT' => 'Вашата система не отговаря на изискванията',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Вашата система отговаря на изискванията.</li><li class="pmin"> - Системата отговаря частично на изискванията. OXID eShop все пак ще работи и може да се инсталира..</li><li class="fail"> - Вашата система не отговаря на изисканията. OXID eShop няма да работи без това и не може да се инсталира.</li><li class="null"> - Изискванията не може да се проверят.</ul>',
'STEP_0_TITLE' => 'Проверка на системните изисквания',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Проверявайте редовно за налични обновявания',
'STEP_1_DESC' => 'Добре дошли в съветника за инсталиране на OXID eShop',
'STEP_1_TEXT' => 'Моля прочетете внимателно инструкциите за безпроблемна инсталация.
                                                    С пожелания за успех в използването на OXID eShop',
'STEP_1_TITLE' => 'Добре дошли',
'STEP_2_TITLE' => 'Лицензионни условия',
'STEP_3_1_CREATING_TABLES' => 'Изграждане на таблиците, прилагане на данните ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Връзката с база данни е успешна ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'База данни %s е успешно създадена ...',
'STEP_3_1_TITLE' => 'База данни - е създадена ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Ако искате да презапишете всички съществуващи данни и да продължите инсталацията натиснете',
'STEP_3_2_CREATING_DATA' => 'База данни е създадена успешно. Моля изчакайте...',
'STEP_3_2_TITLE' => 'Таблиците в база данни са създадени ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'Ако база данни не съществува, ще бъде създадена',
'STEP_3_DB_DATABSE_NAME' => 'Име на база данни',
'STEP_3_DB_DEMODATA' => 'Демо данни',
'STEP_3_DB_HOSTNAME' => 'Име или IP на хоста с база данни',
'STEP_3_DB_PASSWORD' => 'Парола база данни',
'STEP_3_DB_PASSWORD_SHOW' => 'Покажи парола',
'STEP_3_DB_USER_NAME' => 'Потребител на база данни',
'STEP_3_DESC' => 'База данни и необходимите таблици са създадени. Моля посочете допълнителна информация:',
'STEP_3_TITLE' => 'База данни',
'STEP_3_UTFINFO' => 'UTF-8 кодиране предлага по-добра поддръжка за специалните символи от другите кодировки. Това е особено важно при многоезични eShops. За съжаление, UTF-8 е малко по-бавен от стандартния (ISO 8859-15). <br /> Ако възнамерявате да предоставяте Вашия eShop с различни езици, трябва да използвате UTF-8. Ако го предлагате само с няколко езика, които използват обикновени символи (напр. английски, немски, френски), нямате нужда от UTF-8.',
'STEP_3_UTFMODE' => 'Използвай UTF-8 кодировка',
'STEP_3_UTFNOTSUPPORTED' => 'OXID eShop не може да работи с UTF-8 кодировка, поради:',
'STEP_3_UTFNOTSUPPORTED1' => 'липсващ mbstring в PHP модула',
'STEP_3_UTFNOTSUPPORTED2' => 'Инсталирания PCRE не поддържа UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Проверката и записа на данни са успешни. Моля изчакайте ...',
'STEP_4_1_TITLE' => 'Директориите - са създадени ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'e-mail на администратора (използва се за логин)',
'STEP_4_ADMIN_PASS' => 'Администраторска парола',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Потвърди администраторската парола',
'STEP_4_ADMIN_PASS_MINCHARS' => 'по избор, мин. 6 символа',
'STEP_4_DESC' => 'Моля да предоставите необходимите данни за инсталирането на OXID eShop:',
'STEP_4_SHOP_DIR' => 'Директория за OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Директория за временни данни',
'STEP_4_SHOP_URL' => 'URL на магазина',
'STEP_4_TITLE' => 'Създаване на директориите и URL на OXID eShop',
'STEP_5_1_SERIAL_ADDED' => 'Лицензионния ключ е успешно запазен. Моля изчакайте ...',
'STEP_5_1_TITLE' => 'Лицензионния ключ е вкаран ...',
'STEP_5_DESC' => 'Моля потвърдете лицензионния ключ:',
'STEP_5_LICENCE_DESC' => 'Лицензионния ключ е валиден 30 дни. След този период всички Ваши промени ще останат при внасяне на валиден лиценз.',
'STEP_5_LICENCE_KEY' => 'Лизензионен ключ',
'STEP_5_TITLE' => 'OXID eShop лиценз',
'STEP_6_DESC' => 'Вашият OXID eShop е инсталиран успешно.',
'STEP_6_LINK_TO_SHOP' => 'Продължи към OXID eShop',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Продължи към админския интерфейс на OXID eShop',
'STEP_6_TITLE' => 'OXID eShop е успешно инсталиран',
'STEP_6_TO_SHOP' => 'Към магазина',
'STEP_6_TO_SHOP_ADMIN' => 'Към админския интерфейс',
'TAB_0_DESC' => 'Проверка на системните изисквания',
'TAB_0_TITLE' => 'Системни изисквания',
'TAB_1_DESC' => 'Добре дошли е OXID eShop съветник',
'TAB_1_TITLE' => 'Добре дошли',
'TAB_2_DESC' => 'Потвърдете условията на лиценза',
'TAB_2_TITLE' => 'Условия на лиценза',
'TAB_3_DESC' => 'Тест на връзката с база данни, изграждане на таблиците',
'TAB_3_TITLE' => 'База данни',
'TAB_4_DESC' => 'Конфигурация на директориите и избор на администраторския логин',
'TAB_4_TITLE' => 'Директория & логин',
'TAB_5_DESC' => 'Приложи лицензионния ключ',
'TAB_5_TITLE' => 'Лиценз',
'TAB_6_DESC' => 'Инсталацията е успешна',
'TAB_6_TITLE' => 'Готово',
'USE_DYNAMIC_PAGES' => 'За да повишите успеха в бизнеса си проверете за допълнителна информация в OXID\\'s server. Ще намерите повече информация в нашата',
);
