<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: e.mersinlioglu (45), enginistemi (4), esen.baytekin (905), glp_i (120), Justian0 (3), marco (2), McDaim (101), mykibarli (20), scaly (10), three13_de (127)
 */

$sLangName  = 'Türkçe';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Dikkat',
'BUTTON_BEGIN_INSTALL' => 'Install',
'BUTTON_DB_INSTALL' => 'DB Install',
'BUTTON_LICENCE' => 'Devam',
'BUTTON_PROCEED_INSTALL' => 'Devam',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Install DB Demo',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Lisansi Kabul Ediyorum',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Lisans Koşulları\'nı kabul etmiyorum.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => 'Instal Devam Edemiyor',
'BUTTON_START_INSTALL' => 'Kuruluma Basla',
'BUTTON_WRITE_DATA' => 'Bilgileri Giriniz',
'BUTTON_WRITE_LICENCE' => 'Lisans anahtarını kaydet',
'ERROR_BAD_DEMODATA' => 'HATA: SQL deyimleri eklenirken sorun oluştu:',
'ERROR_BAD_SERIAL_NUMBER' => 'HATA: Yanlış lisans anahtarı!',
'ERROR_BAD_SQL' => 'HATA: SQL deyimleri eklenirken sorun oluştu:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'HATA: %s/config.inc.php yazılabilir değil!',
'ERROR_COULD_NOT_CREATE_DB' => 'HATA: Veritabanı mevcut değil.',
'ERROR_COULD_NOT_FIND_FILE' => 'Kurulum "%s"! bulamadı',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => '%s Okumak için açılamadı! Sıkça Sorulan Sorular ve forumu inceleyin veya OXID Destek personeline danışın!',
'ERROR_COULD_NOT_READ_FILE' => 'Kurulum okumak için "%s" açamadı!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Kurulum "%s" \'e yazamadı!',
'ERROR_DB_ALREADY_EXISTS' => 'HATA: OXID eShop veritabanı %s zaten yüklü görünüyor. Devam etmek için önce veritabanını silin!',
'ERROR_DB_CONNECT' => 'HATA: Veritabanı bağlantısı mümkün değil!',
'ERROR_FILL_ALL_FIELDS' => 'HATA: Gerekli tüm alanları doldurun!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'MySQL sürümü sistem gereksinimlerini karşılamıyor.',
'ERROR_NOT_AVAILABLE' => 'HATA: %s bulunamadı!',
'ERROR_NOT_WRITABLE' => 'HATA: %s yazılabilir değil!',
'ERROR_OPENING_SQL_FILE' => 'HATA: %s SQL dosyası açılamıyor!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Şifreler eşleşmiyor!',
'ERROR_PASSWORD_TOO_SHORT' => 'Şifre çok kısa!',
'ERROR_SETUP_CANCELLED' => 'Lisans koşulları kabul edilmedi. Kurulum iptal edildi.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Geçerli bir e-posta adresinizi girin!',
'ERROR_VIEWS_CANT_CREATE' => 'HATA: SQL View(s) oluşturulamıyor. Veritabanı kullanıcı yetkileri kontrol edin.',
'ERROR_VIEWS_CANT_DROP' => 'HATA: View(s) drop edilemiyor. Veritabanı kullanıcı yetkileri kontrol edin.',
'ERROR_VIEWS_CANT_SELECT' => 'HATA: View(s)\'lerden select yapılamıyor. Veritabanı kullanıcı yetkileri kontrol edin.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop kurulum sihirbazı',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'Kurulum birkaç saniye içinde devam etmezse tıklayınız.',
'HERE' => 'Burada',
'LOAD_DYN_CONTENT_NOTICE' => '<p>Kutucuğu seçerseniz OXID admin alanında ek bir menü göreceksiniz.</p>
<p>
Bu menüde e-ticaret hizmetleri hakkında daha fazla bilgi alabilirsiniz.</p>
<p>
Istediğiniz zaman bu ayarları değiştirebilirsiniz.</p>',
'MOD_ALLOW_URL_FOPEN' => '',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => '',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'Dosya yükleme etkin (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. JPEG support',
'MOD_INI_SET' => 'ini_set allowed',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite modül',
'MOD_MYSQL_CONNECT' => 'MySQL 5 için MySQL istemci konektörü',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend uyumluluk modu kapalı olmalıdır',
'MOD_PHP_CONFIG' => 'PHP yapılandırması',
'MOD_PHP_EXTENNSIONS' => 'PHP uzantıları',
'MOD_PHP_VERSION' => 'PHP sürümü en az 5.2.10 olmalıdır',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals kapalı olmalıdır',
'MOD_REQUEST_URI' => '',
'MOD_SERVER_CONFIG' => 'Sunucu yapılandırması',
'MOD_SERVER_PERMISSIONS' => 'Dosya / klasör erişim hakları',
'MOD_SESSION_AUTOSTART' => 'session.auto_start kapalı olmalıdır',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 desteği',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer veya Zend Guard Loader yüklenmiş',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform veya Zend Server yüklü',
'PRIVACY_POLICY' => 'gizlilik politikası',
'SELECT_DELIVERY_COUNTRY' => 'Ana teslimat ülkesi',
'SELECT_DELIVERY_COUNTRY_HINT' => 'Gerektiğinde Admin arayüzünden kolayca daha fazla teslimat ülkesi etkinleştirebilirsiniz.',
'SELECT_PLEASE_CHOOSE' => 'Lütfen seçiniz',
'SELECT_SETUP_LANG' => 'Kurulum dili',
'SELECT_SETUP_LANG_SUBMIT' => 'Seç',
'SELECT_SHOP_LANG' => 'Mağaza dili',
'SELECT_SHOP_LANG_HINT' => 'Gerektiğinde Admin arayüzünden kolayca daha fazla dil etkinleştirebilirsiniz.',
'SELECT_SHOP_LOCATION' => 'Sektörünüz',
'SELECT_SHOP_LOCATION_HINT' => 'Mağazanızın odaklandığı sektörü seçiniz. Eğer izin verirseniz sektöre göre ek e-Ticaret Hizmetleri OXID sunucusundan yüklenir.',
'SETUP_CONFIG_PERMISSIONS' => 'Güvenlik nedeniyle config.inc.php dosyasını salt okunur yapmalısınız!',
'SETUP_DIR_DELETE_NOTICE' => 'Güvenlik nedeniyle kurulum sonrasında SETUP klasörünü kaldırmalısınız.',
'STEP_0_DESC' => 'Bu adımda sistem gereksinimlerinin uygun olup olmadığı kontrol edilecek:',
'STEP_0_ERROR_TEXT' => 'Sunucunuz sistem gereksinimlerini karşılamıyor',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Sistem gereksinimleri karşılanıyor.</li><li class="pmin"> - Sistem gereksinimleri tam değil yada bir kısmı karşılanıyor.Yinede OXID eShop yüklenebilir.</li><li class="fail"> - Sistem gereksinimleri uymuyor.OXID eShop çalışmaz ve yüklenemez.</li><li class="null"> - Sistem gereksinimleri kontrol edilemiyor.</ul>',
'STEP_0_TITLE' => 'Sistem gereksinimleri kontrolü',
'STEP_1_ADDRESS' => 'OXID eSales AG<br> Bertoldstr. 48<br> 79098 Freiburg<br> Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Kullanılabilir güncellemeleri kontrol et',
'STEP_1_DESC' => 'OXID eShop kurulum sihirbazına hoşgeldiniz',
'STEP_1_TEXT' => 'Sorunsuz bir yükleme için aşağıdaki talimatları dikkatlice okuyunuz.
Oxid eShop\'u başarılı bir şekilde kullanmanız için en iyi dileklerimizle.',
'STEP_1_TITLE' => 'Hoşgeldiniz',
'STEP_2_TITLE' => 'Lisans koşulları',
'STEP_3_1_CREATING_TABLES' => 'Veri kullanılarak tablolar oluşturuluyor ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Veritabanı bağlantısı başarılı...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Veritabanı %s başarıyla oluşturuldu ...',
'STEP_3_1_TITLE' => 'Veritabanı - oluşturuluyor...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'Varolan verinin üzerine yazmak istiyorsanız tıklayın',
'STEP_3_2_CREATING_DATA' => 'Veritabanı başarıyla oluşturuldu. Lütfen bekleyin...',
'STEP_3_2_TITLE' => 'Veritabanı - tablolar oluşturuluyor ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => '',
'STEP_3_DB_DATABSE_NAME' => 'Veritabanı adı',
'STEP_3_DB_DEMODATA' => 'Demo verileri',
'STEP_3_DB_HOSTNAME' => 'Veritabanı sunucu adı yada IP adresi',
'STEP_3_DB_PASSWORD' => 'Veritabanı Şifresi',
'STEP_3_DB_PASSWORD_SHOW' => 'Şifreyi göster',
'STEP_3_DB_USER_NAME' => 'Veritabanı kullanıcı adı',
'STEP_3_DESC' => '',
'STEP_3_TITLE' => 'Veritabanı',
'STEP_3_UTFINFO' => '',
'STEP_3_UTFMODE' => 'UTF-8 karakter kodlamasını kullan',
'STEP_3_UTFNOTSUPPORTED' => 'OXID eShop\'u bu nedenlerle UTF-8 modunda çalıştıramazsınız:',
'STEP_3_UTFNOTSUPPORTED1' => 'mbstring PHP modülü eksik',
'STEP_3_UTFNOTSUPPORTED2' => 'Yüklü PCRE UTF-8 desteklemiyor',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Kontrol ve veri yazma başarılı. Lütfen bekleyin ...',
'STEP_4_1_TITLE' => 'Dizinler - oluşturuluyor...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Yönetici e-posta adresi (Kullanıcı adı olarak kullanılır)',
'STEP_4_ADMIN_PASS' => 'Yönetici şifresi',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Yönetici şifresini tekrarla',
'STEP_4_ADMIN_PASS_MINCHARS' => 'min. 6 karakter',
'STEP_4_DESC' => 'Lütfen OXID eShop\'un çalışması için gerekli verileri sağlayın:',
'STEP_4_SHOP_DIR' => 'OXID eShop Dizini',
'STEP_4_SHOP_TMP_DIR' => 'Geçici veri klasörü',
'STEP_4_SHOP_URL' => 'Mağaza URL',
'STEP_4_TITLE' => '',
'STEP_5_1_SERIAL_ADDED' => 'Lisans anahtarı başarıyla kaydedildi. Lütfen bekleyin...',
'STEP_5_1_TITLE' => '',
'STEP_5_DESC' => 'Lisans anahtarı teyit edin:',
'STEP_5_LICENCE_DESC' => 'Sağlanan lisans anahtarı 30 gün için geçerlidir. Bu dönemden sonra kalıcı olarak kullanmak için geçerli bir lisans anahtarı eklemelisiniz.',
'STEP_5_LICENCE_KEY' => 'Lisans Anahtarı',
'STEP_5_TITLE' => 'OXID eShop lisans',
'STEP_6_DESC' => 'OXID eShop başarıyla kurulmuştur.',
'STEP_6_LINK_TO_SHOP' => 'OXID eShop\'a devam et',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'OXID eShop yönetici arayüzüne devam et',
'STEP_6_TITLE' => 'OXID eShop başarıyla kurulmuştur.',
'STEP_6_TO_SHOP' => 'Mağaza arayüzü',
'STEP_6_TO_SHOP_ADMIN' => 'Yönetici arayüzü',
'TAB_0_DESC' => '',
'TAB_0_TITLE' => 'Sistem gereksinimleri',
'TAB_1_DESC' => 'OXID eShop kurulum sihirbazına hoşgeldiniz',
'TAB_1_TITLE' => 'Hoşgeldiniz',
'TAB_2_DESC' => 'Lisans koşullarını onaylayın',
'TAB_2_TITLE' => 'Lisans koşulları',
'TAB_3_DESC' => 'Veritabanı bağlantısı test ediliyor, tablolar oluşturuluyor',
'TAB_3_TITLE' => 'Veritabanı',
'TAB_4_DESC' => '',
'TAB_4_TITLE' => '',
'TAB_5_DESC' => '',
'TAB_5_TITLE' => 'Lisans',
'TAB_6_DESC' => 'Kurulum başarılı',
'TAB_6_TITLE' => 'Bitti',
'USE_DYNAMIC_PAGES' => '',
);
