<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: bRanzo (210), DC-NICO (41), Effettofresnel (121), ET (205), helli (21), simon.runer (573)
 */

$sLangName  = 'Italiano';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Attenzione!',
'BUTTON_BEGIN_INSTALL' => 'Avvia l\'installazione',
'BUTTON_DB_INSTALL' => 'Crea il database',
'BUTTON_LICENCE' => 'Accetto la licenza',
'BUTTON_PROCEED_INSTALL' => 'Procedi con l\'installazione',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Installa Demo',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Accetto le condizioni di licenza',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Non Accetto le condizioni di licenza',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Non</strong> installare il demo',
'BUTTON_START_INSTALL' => 'Ravvia l\'installazione',
'BUTTON_WRITE_DATA' => 'Salva e continua',
'BUTTON_WRITE_LICENCE' => 'Salva la chiave di licenza',
'ERROR_BAD_DEMODATA' => 'ERROR: Issue while inserting this SQL statements: ',
'ERROR_BAD_SERIAL_NUMBER' => 'ERRORE: Codice di licenza scorretto',
'ERROR_BAD_SQL' => 'ERROR: Issue while inserting this SQL statements: ',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ERRORE: il file di configurazione %s/config.inc.php non è scrivibile',
'ERROR_COULD_NOT_CREATE_DB' => 'ERRORE: Non posso creare il database',
'ERROR_COULD_NOT_FIND_FILE' => 'ERRORE: Il setup non trova "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Could not open %s for reading! Please consult our FAQ, forum or contact OXID Support staff!',
'ERROR_COULD_NOT_READ_FILE' => 'Setup could not open "%s" for reading!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Setup could not write to "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ERROR: Seems there is already OXID eShop installed in database %s. Please delete it prior continuing!',
'ERROR_DB_CONNECT' => 'ERROR: No database connection possible!',
'ERROR_FILL_ALL_FIELDS' => 'ERROR: Please fill in all needed fields!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'MySQL version does not fit system requiremens',
'ERROR_NOT_AVAILABLE' => 'ERROR: %s not found!',
'ERROR_NOT_WRITABLE' => 'ERROR: %s not writeable!',
'ERROR_OPENING_SQL_FILE' => 'ERROR: Can not open SQL file %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Passwords do not match!',
'ERROR_PASSWORD_TOO_SHORT' => 'Attenzione! La password è troppo corta',
'ERROR_SETUP_CANCELLED' => 'Setup has been cancelled because you didn\'t accept the license conditions.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Please enter a valid e-mail address!',
'ERROR_VIEWS_CANT_CREATE' => 'ERROR: Can\'t create views. Please check your database user privileges.',
'ERROR_VIEWS_CANT_DROP' => 'ERROR: Can\'t drop views. Please check your database user privileges.',
'ERROR_VIEWS_CANT_SELECT' => 'ERROR: Can\'t select from views. Please check your database user privileges.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop installation wizard',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'If setup does not continue in a few seconds, please click ',
'HERE' => 'qui',
'LOAD_DYN_CONTENT_NOTICE' => '<p>If checkbox is set, you will see an additional menu in the admin area of your OXID eShop.</p><p>In that menu you get further information about e-commerce services like Google product search.</p> <p>You can change these settings at any time.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen o fsockopen verso la porta 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Possibili problemi relativi al bug 53562 di PHP!',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'l\'upload di files è abilitato (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] con supporto JPEG',
'MOD_INI_SET' => 'ini_set consentito',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'libxml2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'modulo mod_rewrite di Apache',
'MOD_MYSQL_CONNECT' => 'MySQL connettore del cliente per MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend compatibility mode must be off',
'MOD_PHP_CONFIG' => 'configurazione PHP',
'MOD_PHP_EXTENNSIONS' => 'estensioni PHP',
'MOD_PHP_VERSION' => 'PHP versione almeno 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'il parametro register_globals dev\'essere impostato su OFF',
'MOD_REQUEST_URI' => 'REQUEST_URI insieme',
'MOD_SERVER_CONFIG' => 'Configurazione del server',
'MOD_SERVER_PERMISSIONS' => 'Files/folders access rights',
'MOD_SESSION_AUTOSTART' => 'session.auto_start deve essere spento',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'Supporto UTF-8',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer or Zend Guard Loader installed',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform or Zend Server installed',
'PRIVACY_POLICY' => 'privacy statements',
'SELECT_DELIVERY_COUNTRY' => 'Main delivery country',
'SELECT_DELIVERY_COUNTRY_HINT' => 'If needed, activate easily more delivery countries in admin.',
'SELECT_PLEASE_CHOOSE' => 'Please choose',
'SELECT_SETUP_LANG' => 'Installation language',
'SELECT_SETUP_LANG_SUBMIT' => 'Select',
'SELECT_SHOP_LANG' => 'Negozio lingua',
'SELECT_SHOP_LANG_HINT' => 'If needed, activate easily more languages in admin.',
'SELECT_SHOP_LOCATION' => 'Vostro mercato',
'SELECT_SHOP_LOCATION_HINT' => 'Please choose the market to which shop is focused. According to it, additional e-commerce Services will be loaded from OXID server, if you allow that.',
'SETUP_CONFIG_PERMISSIONS' => 'Due to security reasons put your config.inc.php file to read-only mode!',
'SETUP_DIR_DELETE_NOTICE' => 'Per motivi di sicurezza ti invitiamo ad eliminare la directory <strong>setup</strong>',
'STEP_0_DESC' => 'Durante questo passaggio valuteremo se il tuo sistema soddisfa i requisiti minimi:',
'STEP_0_ERROR_TEXT' => 'Il tuo sistema non soddisfa i requisiti minimi',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Il sistema soddisfa tutti i requisiti.</li><li class="pmin"> - Il sistema soddisfa parzialmente i requisiti. Tuttavia OXID eShop può essere installato ed usato...</li><li class="fail"> - Il sistema non soddisfa i requisiti. OXID eShop non può funzionare e non verrà avviata l\'installazione.</li><li class="null"> - Impossibile eseguire il controllo dei requisiti.</ul>',
'STEP_0_TITLE' => 'Controllo dei requisiti di sistema',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Controlla regolarmente gli aggiornamenti',
'STEP_1_DESC' => 'Benvenuto al processo di installazione di OXID eShop',
'STEP_1_TEXT' => 'Please read carefully the following instructions to guarantee a smooth installation.
                                                    Wishes for best success in using your OXID eShop by',
'STEP_1_TITLE' => 'Benvenuti',
'STEP_2_TITLE' => 'Condizioni di licenza',
'STEP_3_1_CREATING_TABLES' => 'Creating tables, applying data ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Database connection successfully tested ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Database %s successfully created ...',
'STEP_3_1_TITLE' => 'Database - being created ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'If you want to overwrite all existing data and install anyway click ',
'STEP_3_2_CREATING_DATA' => 'Database successfully created. Please wait ...',
'STEP_3_2_TITLE' => 'Database - tables are beeing created ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'If database does not exist, it\'s going to be created',
'STEP_3_DB_DATABSE_NAME' => 'Database name',
'STEP_3_DB_DEMODATA' => 'Demodata',
'STEP_3_DB_HOSTNAME' => 'Database hostname or IP',
'STEP_3_DB_PASSWORD' => 'Database password',
'STEP_3_DB_PASSWORD_SHOW' => 'Show password',
'STEP_3_DB_USER_NAME' => 'Database username',
'STEP_3_DESC' => 'Database is going to be created and needed tables are written. Please provide some information:',
'STEP_3_TITLE' => 'Database',
'STEP_3_UTFINFO' => 'UTF-8 character encoding provides better support for special chars than other character encodings. This is particulary important for multilingual eShops. However, UTF-8 is slightly slower than the standard encoding (ISO 8859-15). <br /> If you plan to provide your eShop in many different languages, you should use UTF-8. If you just want to provide a few languages using related symbol sets (e. g. English, German, French), you don\'t need UTF-8.',
'STEP_3_UTFMODE' => 'Use UTF-8 character encoding',
'STEP_3_UTFNOTSUPPORTED' => 'The OXID eShop cannot operate in UTF-8 mode, due to:',
'STEP_3_UTFNOTSUPPORTED1' => ' missing mbstring PHP module',
'STEP_3_UTFNOTSUPPORTED2' => ' installed PCRE does not support UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Check and writing data successful. Please wait ...',
'STEP_4_1_TITLE' => 'Directories - being created ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Administrator e-mail (used as login name)',
'STEP_4_ADMIN_PASS' => 'Password amministratore',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Confirm Administrator password',
'STEP_4_ADMIN_PASS_MINCHARS' => 'freely selectable, min. 6 chars',
'STEP_4_DESC' => 'Please provide neccesary data for running OXID eShop:',
'STEP_4_SHOP_DIR' => 'Directory for OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Directory for temporary data',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Setting up OXID eShop directories and URL',
'STEP_5_1_SERIAL_ADDED' => 'License key successfully saved. Please wait ...',
'STEP_5_1_TITLE' => 'License key is being inserted ...',
'STEP_5_DESC' => 'Please confirm license key:',
'STEP_5_LICENCE_DESC' => 'The provided key is valid for 30 days. After this period all of your changes remain if you insert a valid license key.',
'STEP_5_LICENCE_KEY' => 'License key',
'STEP_5_TITLE' => 'Licenza di Oxid eshop',
'STEP_6_DESC' => 'OXID eShop installato correttamente',
'STEP_6_LINK_TO_SHOP' => 'Vai al tuo eShop OXID',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Vai all\'interfaccia di amministrazione',
'STEP_6_TITLE' => 'OXID eShop installato correttamente',
'STEP_6_TO_SHOP' => 'al negozio',
'STEP_6_TO_SHOP_ADMIN' => 'all\'interfaccia di amministrazione',
'TAB_0_DESC' => 'Checking if your system fits the requirements',
'TAB_0_TITLE' => 'System Requirements',
'TAB_1_DESC' => 'Welcome to OXID eShop installation wizard',
'TAB_1_TITLE' => 'Benvenuti',
'TAB_2_DESC' => 'Confirm license conditions',
'TAB_2_TITLE' => 'License conditions',
'TAB_3_DESC' => 'Test database connection, building tables',
'TAB_3_TITLE' => 'Database',
'TAB_4_DESC' => 'Configuring directories and selecting admin login',
'TAB_4_TITLE' => 'Directory & login',
'TAB_5_DESC' => 'Apply license key',
'TAB_5_TITLE' => 'License',
'TAB_6_DESC' => 'Installation succeeded',
'TAB_6_TITLE' => 'Finitura',
'USE_DYNAMIC_PAGES' => 'Per far crescere il tuo successo scarica informazioni aggiuntive dai server di OXID. Potrai trovare ulteriori informazioni sul nostro',
);
