<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: angelhardt (80), HolgerGremminger (69), marco (934), Palmer (73), rhinosmedia (4), skogsverktyg (224), topconcepts (118)
 */

$sLangName  = 'Svenska';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'OBS!',
'BUTTON_BEGIN_INSTALL' => 'Starta installation av webbutik',
'BUTTON_DB_INSTALL' => 'skapa databas nu',
'BUTTON_LICENCE' => 'Vidare',
'BUTTON_PROCEED_INSTALL' => 'Börjar setup',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Install demodata',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Jag godkänner licensvillkoret.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Jag godkänner licensvillkoret ej.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => 'Do <strong>not</strong> install demodata',
'BUTTON_START_INSTALL' => 'Starta om setup',
'BUTTON_WRITE_DATA' => 'Spara och fortsätt',
'BUTTON_WRITE_LICENCE' => 'Spara licensnyckel',
'ERROR_BAD_DEMODATA' => 'ERROR: Issue while inserting this SQL statements: ',
'ERROR_BAD_SERIAL_NUMBER' => 'FEL: fel serienummer!',
'ERROR_BAD_SQL' => 'ERROR: Issue while inserting this SQL statements: ',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ERROR: %s/config.inc.php not writeable!',
'ERROR_COULD_NOT_CREATE_DB' => 'ERROR: Database not available and also cannot be created!',
'ERROR_COULD_NOT_FIND_FILE' => 'Setup could not find "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Could not open %s for reading! Please consult our FAQ, forum or contact OXID Support staff!',
'ERROR_COULD_NOT_READ_FILE' => 'Setup could not open "%s" for reading!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Setup could not write to "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ERROR: Seems there is already OXID eShop installed in database %s. Please delete it prior continuing!',
'ERROR_DB_CONNECT' => 'ERROR: No database connection possible!',
'ERROR_FILL_ALL_FIELDS' => 'FEL: Fyll in alla nödvändinga rutor!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'MySQL version uppfyller ej systemkravet',
'ERROR_NOT_AVAILABLE' => 'FEL: %s finns inte!',
'ERROR_NOT_WRITABLE' => 'ERROR: %s not writeable!',
'ERROR_OPENING_SQL_FILE' => 'FEL: SQL datafil %s kan inte öppnas!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Lösenord stämmer inte överens',
'ERROR_PASSWORD_TOO_SHORT' => 'Lösenord för kort!',
'ERROR_SETUP_CANCELLED' => 'Setup has been cancelled because you didn\'t accept the license conditions.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Ange en giltig mejl adress!',
'ERROR_VIEWS_CANT_CREATE' => 'ERROR: Can\'t create views. Please check your database user privileges.',
'ERROR_VIEWS_CANT_DROP' => 'ERROR: Can\'t drop views. Please check your database user privileges.',
'ERROR_VIEWS_CANT_SELECT' => 'ERROR: Can\'t select from views. Please check your database user privileges.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003-Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop installationsassistent',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'If setup does not continue in a few seconds, please click ',
'HERE' => 'här',
'LOAD_DYN_CONTENT_NOTICE' => '<p>If checkbox is set, you will see an additional menu in the admin area of your OXID eShop.</p><p>In that menu you get further information about e-commerce services like Google product search.</p> <p>You can change these settings at any time.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen to port 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Possible issues on server due to PHP Bugs',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'File uploads are enabled (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. JPEG support',
'MOD_INI_SET' => 'ini_set tillåten',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite modul',
'MOD_MYSQL_CONNECT' => 'MySQL client connector till MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend compatibility mode must be off',
'MOD_PHP_CONFIG' => 'PHP konfiguration',
'MOD_PHP_EXTENNSIONS' => 'PHP extensions',
'MOD_PHP_VERSION' => 'PHP version minst 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals must be off',
'MOD_REQUEST_URI' => 'REQUEST_URI finns',
'MOD_SERVER_CONFIG' => 'server-konfiguration',
'MOD_SERVER_PERMISSIONS' => 'Files/folders access rights',
'MOD_SESSION_AUTOSTART' => 'session.auto_start must be off',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 support',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer or Zend Guard Loader installed',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform or Zend Server installed',
'PRIVACY_POLICY' => 'privacy statements',
'SELECT_DELIVERY_COUNTRY' => 'Main delivery country',
'SELECT_DELIVERY_COUNTRY_HINT' => 'If needed, activate easily more delivery countries in admin.',
'SELECT_PLEASE_CHOOSE' => 'var snäll och välja',
'SELECT_SETUP_LANG' => 'Språk för installation',
'SELECT_SETUP_LANG_SUBMIT' => 'Välja',
'SELECT_SHOP_LANG' => 'Språk för webbutik',
'SELECT_SHOP_LANG_HINT' => 'If needed, activate easily more languages in admin.',
'SELECT_SHOP_LOCATION' => 'Din region',
'SELECT_SHOP_LOCATION_HINT' => 'Please choose the market to which shop is focused. According to it, additional e-commerce Services will be loaded from OXID server, if you allow that.',
'SETUP_CONFIG_PERMISSIONS' => 'Due to security reasons put your config.inc.php file to read-only mode!',
'SETUP_DIR_DELETE_NOTICE' => 'Due to security reasons remove setup directory if not yet done during installation.',
'STEP_0_DESC' => 'I detta steg kontrolleras om systemet uppfyller alla krav:',
'STEP_0_ERROR_TEXT' => 'Ditt system uppfyller inte dem nödvändiga systemkrav.',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Your system fits the requirement.</li><li class="pmin"> - The requirement is not or only partly fit. The OXID eShop will work anyway and can be installed..</li><li class="fail"> - Your system doesn\'t fit the requirement. The OXID eShop will not work without it and cannot be installed.</li><li class="null"> - The requirement could  not be checked.</ul>',
'STEP_0_TITLE' => 'Systemkrav kontrolleras',
'STEP_1_ADDRESS' => 'OXID eSales AG<br> Bertoldstr. 48<br> 79098 Freiburg<br> Tyskland<br>',
'STEP_1_CHECK_UPDATES' => 'Check for available updates regularly',
'STEP_1_DESC' => 'Välkommen till installationsassistent för OXID eShop',
'STEP_1_TEXT' => 'Please read carefully the following instructions to guarantee a smooth installation.
                                                    Wishes for best success in using your OXID eShop by',
'STEP_1_TITLE' => 'Välkommen',
'STEP_2_TITLE' => 'Licensvillkor',
'STEP_3_1_CREATING_TABLES' => 'Creating tables, applying data ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Database connection successfully tested ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Databas %s framgångsrikt skapat...',
'STEP_3_1_TITLE' => 'Database - being created ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'If you want to overwrite all existing data and install anyway click ',
'STEP_3_2_CREATING_DATA' => 'Database successfully created. Please wait ...',
'STEP_3_2_TITLE' => 'Database - tables are beeing created ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'If database does not exist, it\'s going to be created',
'STEP_3_DB_DATABSE_NAME' => 'Databas namn',
'STEP_3_DB_DEMODATA' => 'Demodata',
'STEP_3_DB_HOSTNAME' => 'Databas hostnamn eller IP adress',
'STEP_3_DB_PASSWORD' => 'Databas lösenord',
'STEP_3_DB_PASSWORD_SHOW' => 'Vissa lösenord',
'STEP_3_DB_USER_NAME' => 'Databas användernamn',
'STEP_3_DESC' => 'Database is going to be created and needed tables are written. Please provide some information:',
'STEP_3_TITLE' => 'Databas',
'STEP_3_UTFINFO' => 'UTF-8 character encoding provides better support for special chars than other character encodings. This is particulary important for multilingual eShops. However, UTF-8 is slightly slower than the standard encoding (ISO 8859-15). <br /> If you plan to provide your eShop in many different languages, you should use UTF-8. If you just want to provide a few languages using related symbol sets (e. g. English, German, French), you don\'t need UTF-8.',
'STEP_3_UTFMODE' => 'Use UTF-8 character encoding',
'STEP_3_UTFNOTSUPPORTED' => 'The OXID eShop cannot operate in UTF-8 mode, due to:',
'STEP_3_UTFNOTSUPPORTED1' => 'mbstring PHP modul saknas',
'STEP_3_UTFNOTSUPPORTED2' => ' installed PCRE does not support UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Check and writing data successful. Please wait ...',
'STEP_4_1_TITLE' => 'Directories - being created ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Administrator mejl (används som användernamn)',
'STEP_4_ADMIN_PASS' => 'Administrator lösenord',
'STEP_4_ADMIN_PASS_CONFIRM' => 'bekräfta administrator lösenord',
'STEP_4_ADMIN_PASS_MINCHARS' => 'freely selectable, min. 6 chars',
'STEP_4_DESC' => 'Please provide neccesary data for running OXID eShop:',
'STEP_4_SHOP_DIR' => 'Directory for OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Directory for temporary data',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Setting up OXID eShop directories and URL',
'STEP_5_1_SERIAL_ADDED' => 'License key successfully saved. Please wait ...',
'STEP_5_1_TITLE' => 'License key is being inserted ...',
'STEP_5_DESC' => 'Please confirm license key:',
'STEP_5_LICENCE_DESC' => 'The provided key is valid for 30 days. After this period all of your changes remain if you insert a valid license key.',
'STEP_5_LICENCE_KEY' => 'Licensnyckel',
'STEP_5_TITLE' => 'OXID eShop licens',
'STEP_6_DESC' => 'Your OXID eShop has been installed successfully.',
'STEP_6_LINK_TO_SHOP' => 'Continue to your OXID eShop',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Continue to your OXID eShop admin interface',
'STEP_6_TITLE' => 'OXID eShop successfully installed',
'STEP_6_TO_SHOP' => 'till webbutik',
'STEP_6_TO_SHOP_ADMIN' => 'till webbutikens administration',
'TAB_0_DESC' => 'Checking if your system fits the requirements',
'TAB_0_TITLE' => 'System Requirements',
'TAB_1_DESC' => 'Welcome to OXID eShop installation wizard',
'TAB_1_TITLE' => 'Välkommen',
'TAB_2_DESC' => 'Bekräfta licensvillkor',
'TAB_2_TITLE' => 'Licensvillkor',
'TAB_3_DESC' => 'Test database connection, building tables',
'TAB_3_TITLE' => 'Databas',
'TAB_4_DESC' => 'Configuring directories and selecting admin login',
'TAB_4_TITLE' => 'Directory & login',
'TAB_5_DESC' => 'Apply license key',
'TAB_5_TITLE' => 'Licens',
'TAB_6_DESC' => 'Installation framgångsrikt',
'TAB_6_TITLE' => 'Avsluta',
'USE_DYNAMIC_PAGES' => 'To increase your business success get additional information from OXID\'s server. You find more information in our ',
);
