<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: crashover (330), val (783)
 */

$sLangName  = 'Български';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Няма Listmania списъци. За да създадете нов, кликнете',
'ADD_RECOMM_ADDRECOMMLINK2' => 'Тук',
'allBrands' => 'Всички марки',
'byBrand' => 'По марка',
'byManufacturer' => 'По производител',
'byVendor' => 'По дистрибутор',
'DETAILS_ARTNUMBER' => 'Продукт №:',
'DETAILS_CHOOSEVARIANT' => 'Моля изберете вариант',
'DETAILS_LOCATOR_PRODUCT' => 'Продукт',
'DETAILS_PLUSSHIPPING2' => 'Стойност на доставката.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Известие за цената',
'DETAILS_VPE_MESSAGE_1' => 'Този продукт може да бъде поръчан в опаковка от',
'DETAILS_VPE_MESSAGE_2' => 'поръчан.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Покана от',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'да посетите',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'да посетите.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Product Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'НЯМА',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Payment Charge VAT',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Ще бъде платена от:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Will be shipped with',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Shipping costs (w/o tax):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'плюс данък.',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Съобщение:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>PAYMENT INFORMATION SWITCHED OFF</b> - To switch them on, please change email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'Поръчката е доставена до:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Продукт',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Рейтинг на продукта',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'преглед',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'URL за следене на доставката:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'натисни тук',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Моля, отделете минутка за да гласувате за нашия магазин.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Ваш',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'екип',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Ограничено количество',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Kind regards,',
'FOOTER_CATEGORIES' => 'CATEGORIES',
'FOOTER_DISTRIBUTORS' => 'DISTRIBUTORS',
'FOOTER_INFORMATION' => 'INFORMATION',
'FOOTER_MANUFACTURERS' => 'BRANDS',
'FOOTER_SERVICES' => 'SERVICE',
'FORM_CONTACT_SEND' => 'Send password',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Repeat password:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Forgot password?',
'FORM_NEWSLETTER_FIRSTNAME' => 'First name',
'FORM_PRICEALARM_SEND' => 'Изпрати',
'FORM_PRIVATESALES_INVITE_FROM' => 'От:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Здравейте, разглеждах',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'днес и открих нещо, което може би е интересно за Вас.Просто натиснете линка отдолу и ще бъдете препратен в магазина.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Изпрати покана',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Парола на изпращача:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'заглавие',
'FORM_REGISTER_BILLINGADDRESS' => 'Адрес за фактуриране',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Моля попълнете всички задължителни/удебелени полета.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Информиран съм за',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'информиран.',
'FORM_REGISTER_IAGREETOTERMS1' => 'I agree to the',
'FORM_REGISTER_IAGREETOTERMS3' => 'read and accept them.',
'FORM_SUGGEST_MESSAGE1' => 'Hello, I was looking at',
'FORM_SUGGEST_MESSAGE2' => 'today and found something that might be interesting for you. Just click on the link below and you will be directed to the shop.',
'FORM_USER_BILLINGADDRESS' => 'Billing address',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Repeat password:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Search now',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hi, I created a Gift Registry at',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Great if you could buy something for me.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Error while sending - please check your email address.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Решетка',
'infogrid' => 'Двойна решетка',
'line' => 'Ред',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Моля попълнете всички полета с  "*"!\'',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'Излез',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Запази новата парола',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Отвори нов акаунт',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Настройки за плащане и доставка',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Вашата регистрация за подаръци беше успешмо изпратена на:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'dispatched!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Product number',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Surcharge VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reason',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => '+',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% ДДС',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Всичко',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Сума (вкл. ДДС)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Сума (нето)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Вашето съобщение:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Адрес за фактуриране',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Вашия ваучер',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'беше отхвърлен.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Адрес за доставка',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Bank account number:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Please fill all fields properly!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Currently we have no shipping method set up for this country.</p> <p>We are aiming to find a possible delivery method and we will inform you as soon as possible via e-mail about the result, including further information about delivery costs.</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'incl. VAT',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'COD Charge',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'The Trusted Shops buyer protection secures your online purchase. I agree with the transfer and',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'saving',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'of my e-mail address for the buyer protection handling by Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Conditions',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'for the buyer protection.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Регистрирахме поръчката Ви под номер:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Благодарим Ви за поръчката',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'в',
'PAGE_CHECKOUT_USER' => 'Изпращане',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Регистрирания потребител има предимства като:<br> - Администриране на адреса за доставка<br> - Да проверява статуса на поръчката<br> - История на поръчките<br> - Персонален списък с желания<br> - Специални оферти и отстъпки',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Откажи',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NONE',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Благодарим Ви.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'оценява Вашия коментар.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Ще Ви информираме, щом цената падне под',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'Вие решихте да не приемате бисквитки (cookies) от нашия сайт.Cookies са премахнати. Може да деактивирате употребата на cookies в настройките на броузера и да посетите нашия магазин с ограничена функционалност.Също така може да се върнете към магазина без промяна на настройките и да се наслаждавате на пълната фумкционалност.<br/><br/>Информация за cookies на Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Информация за Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Благодарим Ви.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'оценява Вашия коментар.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Новини от',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'These products are on the wish list of',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. If you want to please him/her, purchase one or multiple of these products.',
'searchResult' => 'Резултати от търсенето "%s"',
'simpleDateFormat' => 'Г-м-д',
'usrRegistered' => 'Потребителя ще бъде регистриран след въвеждане не паролата',
'view' => 'Виж',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Повече ...',
'WIDGET_LOGINBOX_LOGIN' => 'Логин',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Подробности за продукта',
'WIDGET_SERVICES_GUESTBOOK' => 'Книга за гости',
'WIDGET_SERVICES_HOME' => 'Начало',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'More Information',
);
