<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: crashover (330), fifo (9), marco (1), Marcus77 (35), val (933)
 */

$sLangName  = 'Български';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Няма Listmania списъци. За да създадете нов, кликнете',
'ADD_RECOMM_ADDRECOMMLINK2' => 'Тук',
'allBrands' => 'Всички марки',
'byBrand' => 'По марка',
'byManufacturer' => 'По производител',
'byVendor' => 'По дистрибутор',
'DETAILS_ARTNUMBER' => 'Продукт №:',
'DETAILS_CHOOSEVARIANT' => 'Моля изберете вариант',
'DETAILS_LOCATOR_PRODUCT' => 'Продукт',
'DETAILS_PLUSSHIPPING2' => 'Стойност на доставката.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Известие за цената',
'DETAILS_VPE_MESSAGE_1' => 'Този продукт може да бъде поръчан в опаковка от',
'DETAILS_VPE_MESSAGE_2' => 'поръчан.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Покана от',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'да посетите',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'да посетите.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Product Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'НЯМА',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => '',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Ще бъде платена от:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => '',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => '',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'плюс данък.',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'плюс данък.',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Съобщение:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => '',
'EMAIL_SENDDOWNLOADS_GREETING' => '',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => '',
'EMAIL_SENDDOWNLOADS_SUBJECT' => '',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'Поръчката е доставена до:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Продукт',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Рейтинг на продукта',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'преглед',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'URL за следене на доставката:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'натисни тук',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Моля, отделете минутка за да гласувате за нашия магазин.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Ваш',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'екип',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Ограничено количество',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => '',
'FOOTER_CATEGORIES' => '',
'FOOTER_DISTRIBUTORS' => '',
'FOOTER_INFORMATION' => '',
'FOOTER_MANUFACTURERS' => '',
'FOOTER_SERVICES' => '',
'FORM_CONTACT_SEND' => '',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => '',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Забравена парола',
'FORM_NEWSLETTER_FIRSTNAME' => '',
'FORM_PRICEALARM_SEND' => 'Изпрати',
'FORM_PRIVATESALES_INVITE_FROM' => 'От:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Здравейте, разглеждах',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'днес и открих нещо, което може би е интересно за Вас.Просто натиснете линка отдолу и ще бъдете препратен в магазина.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Изпрати покана',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Парола на изпращача:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'заглавие',
'FORM_REGISTER_BILLINGADDRESS' => 'Адрес за фактуриране',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Моля попълнете всички задължителни/удебелени полета.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Информиран съм за',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'информиран.',
'FORM_REGISTER_IAGREETOTERMS1' => '',
'FORM_REGISTER_IAGREETOTERMS3' => '',
'FORM_SUGGEST_MESSAGE1' => '',
'FORM_SUGGEST_MESSAGE2' => '',
'FORM_USER_BILLINGADDRESS' => 'Адрес за получаване на фактура',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => '',
'FORM_WISHLIST_SEARCH_SEARCH' => '',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => '',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => '',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Решетка',
'infogrid' => 'Двойна решетка',
'line' => 'Ред',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Моля попълнете всички полета с  "*"!\'',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'Излез',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Запази новата парола',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Отвори нов акаунт',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Настройки за плащане и доставка',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Вашата регистрация за подаръци беше успешмо изпратена на:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Сума',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Сума',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => '+',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% ДДС',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Всичко',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Сума (вкл. ДДС)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Сума (нето)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Вашето съобщение:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Адрес за фактуриране',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Вашия ваучер',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'беше отхвърлен.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Адрес за доставка',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => '',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => '',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'С ДДС',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => '',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => '',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Регистрирахме поръчката Ви под номер:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => '',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Благодарим Ви за поръчката',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'в',
'PAGE_CHECKOUT_USER' => 'Изпращане',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Регистрирания потребител има предимства като:<br> - Администриране на адреса за доставка<br> - Да проверява статуса на поръчката<br> - История на поръчките<br> - Персонален списък с желания<br> - Специални оферти и отстъпки',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Откажи',
'PAGE_CHECKOUT_WRAPPING_NONE' => '',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Благодарим Ви.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'оценява Вашия коментар.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Ще Ви информираме, щом цената падне под',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'Вие решихте да не приемате бисквитки (cookies) от нашия сайт.Cookies са премахнати. Може да деактивирате употребата на cookies в настройките на броузера и да посетите нашия магазин с ограничена функционалност.Също така може да се върнете към магазина без промяна на настройките и да се наслаждавате на пълната фумкционалност.<br/><br/>Информация за cookies на Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Информация за Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Благодарим Ви.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'оценява Вашия коментар.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Новини от',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => '',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '',
'searchResult' => 'Резултати от търсенето "%s"',
'simpleDateFormat' => 'Г-м-д',
'usrRegistered' => 'Потребителя ще бъде регистриран след въвеждане не паролата',
'view' => 'Виж',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Повече ...',
'WIDGET_LOGINBOX_LOGIN' => 'Логин',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Подробности за продукта',
'WIDGET_SERVICES_GUESTBOOK' => 'Книга за гости',
'WIDGET_SERVICES_HOME' => 'Начало',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => '',
);
