<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (406), HolgerGremminger (69), marco (934), rhinosmedia (4)
 */

$sLangName  = "Svenska";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Det finns för närvarande inga favoritlistor. Om du vill skapa en ny favoritlista, klicka',
'ADD_RECOMM_ADDRECOMMLINK2' => 'här',
'allBrands' => 'Alla märken',
'byBrand' => 'Efter varumärke',
'byManufacturer' => 'Efter varumärke',
'byVendor' => 'Efter leverantör',
'DETAILS_ARTNUMBER' => 'ArtNr.:',
'DETAILS_CHOOSEVARIANT' => 'Vänligen välj en variant',
'DETAILS_LOCATOR_PRODUCT' => 'ARTIKEL',
'DETAILS_PLUSSHIPPING2' => 'Fraktkostnad.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Prisalarm!',
'DETAILS_VPE_MESSAGE_1' => 'Denna artikel kan endast köpas i förpackningsenheter om',
'DETAILS_VPE_MESSAGE_2' => '.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'En inbjudan från',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => ',',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'att besöka.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Artnr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'INGA',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Tillägg % Moms',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Betalningen görs med:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'plus moms',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'plus moms',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Leverans sker med',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Fraktkostnader (netto):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'plus moms',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'plus moms',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Meddelande:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>BETALNINGSINFORMATION AVSTÄNGD</b> - För att aktivera den vänligen ändra email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'The order is shipped to:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Product',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Product Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'review',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Your shipment tracking URL:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'click here',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Please take a minute to rate our shop.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Your',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Team',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stock low',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Många Hälsningar,',
'FOOTER_CATEGORIES' => 'KATEGORIER',
'FOOTER_DISTRIBUTORS' => 'LEVERANTÖRER',
'FOOTER_INFORMATION' => 'INFORMATION',
'FOOTER_MANUFACTURERS' => 'VARUMÄRKE',
'FOOTER_SERVICES' => 'SERVICE',
'FORM_CONTACT_SEND' => 'Skicka meddelande',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Upprepa lösenord:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Glömt lösenord?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Förnamn',
'FORM_PRICEALARM_SEND' => 'skicka',
'FORM_PRIVATESALES_INVITE_FROM' => 'Från:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Hej! Idag hittade jag denna intressanta shop',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'för dig. Följ bara länken nedan direkt till shopen.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Skicka inbjudan',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Avsändarens e-post:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Titel',
'FORM_REGISTER_BILLINGADDRESS' => 'Faktureringsadress',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Fyll i alla obligatoriska fält som är märkta med fet stil.)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Jag har blivit informerad om',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informerad.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Jag har',
'FORM_REGISTER_IAGREETOTERMS3' => 'läst och godkänner.',
'FORM_SUGGEST_MESSAGE1' => 'Hej! Idag hittade jag denna intressanta shop',
'FORM_SUGGEST_MESSAGE2' => 'för dig. Följ bara länken nedan direkt till shopen.',
'FORM_USER_BILLINGADDRESS' => 'Faktureringsadress',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Upprepa lösenord:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Sök nu',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hej, jag har skapat en önskelista.',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => 'Köp gärna något härifrån.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Det uppstod ett fel när meddelandet skulle skickas - vänligen kontrollera e-post-adress.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Galleri',
'infogrid' => 'Galleri två kolumner',
'line' => 'Lista',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Vänligen fyll i alla *-märkta fält!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'LOGGA UT',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Spara nytt lösenord',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Öppna nytt konto',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Billings and Shipping settings',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Din önskelista har skickats till',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'skickats!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Artikel Nr.',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Kupongen',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'godtogs ej.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Totalt',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Tillägg % moms',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '%-belopp',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'plus moms',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '%-belopp',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Orsak',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'plus moms',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '%-belopp',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Totalt',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Summa artiklar (brutto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Summa artiklar (netto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'plus moms',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'plus moms',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Din text:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Faktureringsadress',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Kupongen',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'godtogs ej.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Leveransadress',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Kontonummer:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Fyll i alla fält korrekt!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>För närvarande är inget fraktalternativ för detta land tillgängligt.</p> <p>Vi försöker hitta fraktmöjligheter och kommer att informera dig om fraktkostnader.</p> <p>Om du är införstådd med detta, välj "Fortsätt till nästa steg".</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'inkl. moms',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Postförskott',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'Trusted Shops köpskydd skyddar ditt onlineköp. Jag godkänner att Trusted Shops',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'sparar',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'min e-postadress för hantering av köpskyddet.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Villkor',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'för köpskyddet.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Din beställning är registrerad hos oss under detta nummer',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => '.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Tack för din beställning',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'i',
'PAGE_CHECKOUT_USER' => 'Skicka',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Med ett personligt kund konto har du följande fördelar:<br> - förvaltning av leveransadresser<br> - kontroll av orderstatus<br> - orderhistorik<br> - personlig  kom-ihåg-lista<br> - personlig önskelista<br> - förvaltning av nyhetsbrev<br> - speciella rabatter',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Avbryt',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'INGA',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Tack för ditt meddelande till',
'PAGE_DETAILS_THANKYOUMESSAGE2' => '.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Du får ett meddelande från oss när priset sjunker under',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Information about Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Tack för ditt meddelande till',
'PAGE_INFO_CONTACT_THANKYOU2' => '.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Nyheter hos',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Denna artikel har',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => 'önskat sig. Köp gärna en eller flera av dessa artiklar.',
'searchResult' => 'Söka åt "%s"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'Användaren blir registrerad efter att ha angett lösenord',
'view' => 'Visa',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Mer...',
'WIDGET_LOGINBOX_LOGIN' => 'Login',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Produktdetaljer',
'WIDGET_SERVICES_GUESTBOOK' => 'Gästbok',
'WIDGET_SERVICES_HOME' => 'Hem',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Mer information',
);
