<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: menhem-it (152), tarazi (33)
 */

$sLangName  = 'العربية';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'لا يوجد حاليا أي قوائم المفضلة لديك. لإنشاء قائمة مفضلة جديدة، انقر',
'ADD_RECOMM_ADDRECOMMLINK2' => 'هنا',
'allBrands' => 'جميع الماركة',
'byBrand' => 'عن طريق الماركة',
'byManufacturer' => 'عن الشركة المصنعة',
'byVendor' => 'عن المزود',
'DETAILS_ARTNUMBER' => 'رقم المنتج',
'DETAILS_CHOOSEVARIANT' => 'يرجى اختيار الاختلاف',
'DETAILS_LOCATOR_PRODUCT' => 'المنتج',
'DETAILS_PLUSSHIPPING2' => 'تكاليف الشحن',
'DETAILS_PRICEALARM' => 'تنبيه السعر <B>! </ B>',
'DETAILS_VPE_MESSAGE_1' => 'هذا المنتج يمكن شراء فقط في وحدات التعبئة والتغليف',
'DETAILS_VPE_MESSAGE_2' => '',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'دعوة من',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'لزيارة',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'لزيارة',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'رقم المنتج',
'EMAIL_ORDER_CUST_HTML_NONE' => 'غير متوفرة',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => '',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'يتم الدفع عن طريق:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'بالإضافة إلى الضريبة',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'بالإضافة إلى الضريبة',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'الشحن عن طريق',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'تكاليف الشحن (بدون ضريبة)',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'بالإضافة إلى الضريبة',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'بالإضافة إلى الضريبة',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'رسالة',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'تحميل طلبك هنا.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'مرحبا',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'دفع لم يكتمل بعد.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'رابط دونلود',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'رقم المنتج',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'رقم طلبك',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'يتم إرسال إلى',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'منتج',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'قيم هذا المقال',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'قيم',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'الرابط الخاص بك لتتبع طلبك:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'انقر هنا',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'يرجى أن يكون لديك الوقت الكافي لتقييم محلنا.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'أنت',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'فريق',
'EMAIL_STOCKREMINDER_SUBJECT' => 'عدد قليل',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'مع أطيب التحيات،',
'FOOTER_CATEGORIES' => 'التصنيفات',
'FOOTER_DISTRIBUTORS' => 'وكيل التوزيع',
'FOOTER_INFORMATION' => 'معلومات',
'FOOTER_MANUFACTURERS' => 'الماركة',
'FOOTER_SERVICES' => 'الخدمة',
'FORM_CONTACT_SEND' => '',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'مرة أخرى أكرر كلمة السر:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'نسيت كلمة المرور ؟',
'FORM_NEWSLETTER_FIRSTNAME' => 'الاسم الأول',
'FORM_PRICEALARM_SEND' => 'إرسال',
'FORM_PRIVATESALES_INVITE_FROM' => 'من:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => '',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => '',
'FORM_PRIVATESALES_INVITE_SEND' => '',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => '',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'العنوان',
'FORM_REGISTER_BILLINGADDRESS' => 'عنوان الفواتير',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => '',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => '',
'FORM_REGISTER_IAGREETOTERMS1' => '',
'FORM_REGISTER_IAGREETOTERMS3' => '',
'FORM_SUGGEST_MESSAGE1' => '',
'FORM_SUGGEST_MESSAGE2' => '',
'FORM_USER_BILLINGADDRESS' => 'عنوان الفواتير',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'مرة أخرى أكرر كلمة السر:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'بحث الآن',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => '',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'خطأ أثناء إرسال - يرجى التحقق من عنوان البريد الإلكتروني.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'معرض',
'infogrid' => '',
'line' => 'خط',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'يرجى ملء جميع الخانات مع "*"!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'خروج',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'حفظ كلمة مرور جديدة',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'فتح حساب جديد',
'PAGE_ACCOUNT_USER_USERTITLE' => '',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => '',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'أرسلت!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'رقم المنتج',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'القسيمة',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'تم رفض.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'المبلغ الإجمالي',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => '',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '٪ المبلغ',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'بالإضافة إلى الضريبة',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '٪ المبلغ',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'السبب',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'بالإضافة إلى الضريبة',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '٪ المبلغ',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'المبلغ الإجمالي',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'مجموع المنتجات (بما في ذلك الضريبة)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'إجمالي المنتجات (باستثناء الضرائب)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'بالإضافة إلى الضريبة',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'بالإضافة إلى الضريبة',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'النص:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'عنوان الفواتير',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'القسيمة',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'تم رفض.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'عنوان الشحن',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'رقم الحساب',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'يرجى تعبئة جميع الحقول بشكل سليم!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => '',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'بالإضافة إلى',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'تخزين',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => '',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'الشروط',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => '',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'سجلنا طلبك تحت رقم:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => '',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'شكرا لطلبك',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'في',
'PAGE_CHECKOUT_USER' => 'إرسال',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => '',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'إلغاء',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'لا شيء',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'شكرا جزيلا',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'تقدر تعليقاتكم.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => '',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => '',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'معلومات عن الكوكيز',
'PAGE_INFO_CONTACT_THANKYOU1' => 'شكرا جزيلا',
'PAGE_INFO_CONTACT_THANKYOU2' => 'تقدر تعليقاتكم.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'أخبار من',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'هذه المنتجات على قائمة الامنيات',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '',
'searchResult' => 'نتائج البحث: "٪ S"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'يتم تسجيل المستخدم بعد إدخال كلمة السر',
'view' => 'عرض',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'المزيد ...',
'WIDGET_LOGINBOX_LOGIN' => 'تسجيل الدخول',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'تفاصيل المنتج',
'WIDGET_SERVICES_GUESTBOOK' => 'سجل الزوار',
'WIDGET_SERVICES_HOME' => 'الصفحة الرئيسية',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'مزيد من المعلومات',
);
