<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (2364), hodota (32)
 */

$sLangName  = "日本語";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => '現時点ではリストマニアはありません。新規作成するには',
'ADD_RECOMM_ADDRECOMMLINK2' => 'こちらをクリック',
'allBrands' => 'All Brands',
'byBrand' => 'By ブランド',
'byManufacturer' => 'By ブランド',
'byVendor' => 'By 属性',
'DETAILS_ARTNUMBER' => 'Product Nr.:',
'DETAILS_CHOOSEVARIANT' => 'Please select a variant',
'DETAILS_LOCATOR_PRODUCT' => '製品',
'DETAILS_PLUSSHIPPING2' => 'shipping costs.',
'DETAILS_PRICEALARM' => '<b>[!]</b> 価格アラート',
'DETAILS_VPE_MESSAGE_1' => 'This product can only be ordered in packaging units of ',
'DETAILS_VPE_MESSAGE_2' => 'purchased.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'An invitation from',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'to visit',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'to visit.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Product Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'なし',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Payment Charge VAT',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Will be paid by:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'plus tax.',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Will be shipped with',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Shipping costs (w/o tax):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'plus tax',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'plus tax',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Message: ',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>PAYMENT INFORMATION SWITCHED OFF</b> - To switch them on, please change email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'The order is shipped to:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Product',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Product Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'review',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Your shipment tracking URL:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'click here',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Please take a minute to rate our shop.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Your',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Team',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stock low',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Kind regards,',
'FOOTER_CATEGORIES' => 'カテゴリー',
'FOOTER_DISTRIBUTORS' => 'ディストリビューター',
'FOOTER_INFORMATION' => 'インフォメーション',
'FOOTER_MANUFACTURERS' => 'ブランド',
'FOOTER_SERVICES' => 'サービス',
'FORM_CONTACT_SEND' => 'Send password',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Repeat password:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Forgot password?',
'FORM_NEWSLETTER_FIRSTNAME' => 'First name',
'FORM_PRICEALARM_SEND' => 'Send',
'FORM_PRIVATESALES_INVITE_FROM' => 'From: ',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'こんにちは、I was looking at',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'today and found something that might be interesting for you. Just click on the link below and you will be directed to the shop.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Send invitation',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Sender\'s password: ',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Headline',
'FORM_REGISTER_BILLINGADDRESS' => 'Billing address',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(太字になっているすべての必須フィールドに記入してください。)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'I have been informed about my',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informed.',
'FORM_REGISTER_IAGREETOTERMS1' => 'I agree to the',
'FORM_REGISTER_IAGREETOTERMS3' => 'read and accept them.',
'FORM_SUGGEST_MESSAGE1' => 'こんにちは、I was looking at',
'FORM_SUGGEST_MESSAGE2' => 'today and found something that might be interesting for you. Just click on the link below and you will be directed to the shop.',
'FORM_USER_BILLINGADDRESS' => 'Billing address',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Repeat password:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Search now',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Hi, I created a Gift Registry at',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Great if you could buy something for me.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Error while sending - please check your email address.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => '４列',
'infogrid' => '２列',
'line' => 'リスト',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Please fill all fields with a "*"!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'ログアウト',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Save new password',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Open new account',
'PAGE_ACCOUNT_USER_USERTITLE' => '請求と配送の設定',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'あなたのギフトレジストリに送信されました:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'dispatched!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Product number',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Surcharge VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Reason',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Amount',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Sub total',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Sum of products (incl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Sum of products (excl. tax)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'plus tax',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Your message:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Billing address',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Your voucher',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'has been refused.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Shipping address',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Bank account number:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Please fill all fields properly!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Currently we have no delivery method set up for this country.</p> <p>We are aiming to find a possible delivery method and we will inform you as soon as possible via e-mail about the result, including further information about delivery costs.</p> <p>If you agree to this procedure, please select "move on to next step"</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => '消費税',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => '＋',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => '代引き手数料込み',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'The Trusted Shops buyer protection secures your online purchase. I agree with the transfer and',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'saving',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'of my e-mail address for the buyer protection handling by Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Conditions',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'for the buyer protection.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'We registered your order under the number:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'ご注文ありがとうございます。',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'in',
'PAGE_CHECKOUT_USER' => 'Dispatch',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'お客様がアカウントを持つと次のようなメリットがあります:<br> - 配送先住所の管理<br> - ご注文状況の確認<br> - ご注文履歴<br> - 個人のウィッシュリスト<br> - 個人のギフトレジストリ<br> - ニュースレターの購読<br> - 特別料金や割引',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Cancel',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'なし',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'ありがとうございます。',
'PAGE_DETAILS_THANKYOUMESSAGE2' => ' appreciates your comments.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'We will inform you as soon as the price falls below',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Information about Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'ありがとうございます。',
'PAGE_INFO_CONTACT_THANKYOU2' => ' appreciates your comments.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'News from',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'These products are on the wish list of',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. If you want to please him/her, purchase one or multiple of these products.',
'searchResult' => '検索結果: "%s"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'User will be registered after he provided his password',
'view' => '表示',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'More ...',
'WIDGET_LOGINBOX_LOGIN' => 'Login',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Product details',
'WIDGET_SERVICES_GUESTBOOK' => 'Guest book',
'WIDGET_SERVICES_HOME' => 'Home',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'More Information',
);
