<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2016
 * @version OXID eShop CE
 * @translators: imarius (93), ovidiu (175), patmat2809 (1), urecheatu007 (313), valdone (189)
 */

$sLangName  = 'Română';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Atentie, important',
'BUTTON_BEGIN_INSTALL' => 'Pornire instalare',
'BUTTON_DB_INSTALL' => 'Creaza baza de date acum',
'BUTTON_LICENCE' => 'Continua',
'BUTTON_PROCEED_INSTALL' => 'Continua cu instalarea',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Instalare date demonstrative',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Accept termenii licentei.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Nu accept termenii licentei.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Nu</strong> se instaleaza datele demonstrative',
'BUTTON_START_INSTALL' => 'Repornire instalare',
'BUTTON_WRITE_DATA' => 'Salveaza si continua',
'BUTTON_WRITE_LICENCE' => 'Salveaza cheia de licenta',
'ERROR_BAD_DEMODATA' => 'EROARE: Probleme la inserarea acestor interogari SQL:',
'ERROR_BAD_SERIAL_NUMBER' => 'EROARE: cheie de licenta gresita!',
'ERROR_BAD_SQL' => 'EROARE: Probleme la inserarea acestor interogari SQL:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'EROARE: %s/config.inc.php nu poate fi scris!',
'ERROR_COULD_NOT_CREATE_DB' => 'EROARE: Baza de date nu este disponibila si nici nu poate fi creata!',
'ERROR_COULD_NOT_FIND_FILE' => 'Instalarea nu a gasit "%s"!',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Nu am putut deschide %s pentru citire! Consulta FAQ, forumul sau contacteaza personalul de suport OXID!',
'ERROR_COULD_NOT_READ_FILE' => 'Instalarea nu a putut deschide "%s" pentru citire!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Instalarea nu a putut scrie in "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'EROARE: Se pare ca exista deja o instalare de OXID eShop in baza de date %s. Trebuie stearsa inainte de continuare!',
'ERROR_DB_CONNECT' => 'EROARE: Nu este posibila conectarea la baza de date!',
'ERROR_FILL_ALL_FIELDS' => 'EROARE: Trebuie completate toate campurile necesare!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Versiunea de MySQL nu indeplineste cerintele minime de sistem',
'ERROR_NOT_AVAILABLE' => '',
'ERROR_NOT_WRITABLE' => 'Eroare: Nu se poate scrie pe %s !',
'ERROR_OPENING_SQL_FILE' => '',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Parolele nu se potrivesc!',
'ERROR_PASSWORD_TOO_SHORT' => 'Parola este prea scurta',
'ERROR_SETUP_CANCELLED' => 'Instalarea a fost anulata deoarece nu ati acceptat conditiile licentei.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Va rugam introduceti o casuta postala valida !',
'ERROR_VIEWS_CANT_CREATE' => 'EROARE: Nu se pot crea vizualizari. Va rugam sa verificati privilegiile utilizatorului bazei de date.',
'ERROR_VIEWS_CANT_DROP' => '',
'ERROR_VIEWS_CANT_SELECT' => 'EROARE: Nu se poate selecta din vizualizari. Va rugam sa verificati privilegiile utilizatorului bazei de date.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => '',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => '',
'HERE' => '',
'LOAD_DYN_CONTENT_NOTICE' => '',
'MOD_ALLOW_URL_FOPEN' => '',
'MOD_BC_MATH' => '',
'MOD_BUG53632' => '',
'MOD_CURL' => '',
'MOD_FILE_UPLOADS' => '',
'MOD_GD_INFO' => '',
'MOD_INI_SET' => '',
'MOD_I_CONV' => '',
'MOD_J_SON' => '',
'MOD_LIB_XML2' => '',
'MOD_MB_STRING' => '',
'MOD_MOD_REWRITE' => '',
'MOD_MYSQL_CONNECT' => '',
'MOD_OPEN_SSL' => '',
'MOD_PHP4_COMPAT' => '',
'MOD_PHP_CONFIG' => '',
'MOD_PHP_EXTENNSIONS' => '',
'MOD_PHP_VERSION' => '',
'MOD_PHP_XML' => '',
'MOD_REGISTER_GLOBALS' => '',
'MOD_REQUEST_URI' => '',
'MOD_SERVER_CONFIG' => '',
'MOD_SERVER_PERMISSIONS' => '',
'MOD_SESSION_AUTOSTART' => '',
'MOD_SOAP' => '',
'MOD_TOKENIZER' => '',
'MOD_UNICODE_SUPPORT' => '',
'MOD_ZEND_OPTIMIZER' => '',
'MOD_ZEND_PLATFORM_OR_SERVER' => '',
'PRIVACY_POLICY' => '',
'SELECT_DELIVERY_COUNTRY' => '',
'SELECT_DELIVERY_COUNTRY_HINT' => '',
'SELECT_PLEASE_CHOOSE' => '',
'SELECT_SETUP_LANG' => '',
'SELECT_SETUP_LANG_SUBMIT' => '',
'SELECT_SHOP_LANG' => '',
'SELECT_SHOP_LANG_HINT' => '',
'SELECT_SHOP_LOCATION' => '',
'SELECT_SHOP_LOCATION_HINT' => '',
'SETUP_CONFIG_PERMISSIONS' => '',
'SETUP_DIR_DELETE_NOTICE' => '',
'STEP_0_DESC' => '',
'STEP_0_ERROR_TEXT' => '',
'STEP_0_ERROR_URL' => '',
'STEP_0_TEXT' => '',
'STEP_0_TITLE' => '',
'STEP_1_ADDRESS' => '',
'STEP_1_CHECK_UPDATES' => '',
'STEP_1_DESC' => '',
'STEP_1_TEXT' => '',
'STEP_1_TITLE' => '',
'STEP_2_TITLE' => '',
'STEP_3_1_CREATING_TABLES' => '',
'STEP_3_1_DB_CONNECT_IS_OK' => '',
'STEP_3_1_DB_CREATE_IS_OK' => '',
'STEP_3_1_TITLE' => '',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => '',
'STEP_3_2_CREATING_DATA' => '',
'STEP_3_2_TITLE' => '',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => '',
'STEP_3_DB_DATABSE_NAME' => '',
'STEP_3_DB_DEMODATA' => '',
'STEP_3_DB_HOSTNAME' => '',
'STEP_3_DB_PASSWORD' => '',
'STEP_3_DB_PASSWORD_SHOW' => '',
'STEP_3_DB_USER_NAME' => '',
'STEP_3_DESC' => '',
'STEP_3_TITLE' => '',
'STEP_3_UTFINFO' => '',
'STEP_3_UTFMODE' => '',
'STEP_3_UTFNOTSUPPORTED' => '',
'STEP_3_UTFNOTSUPPORTED1' => '',
'STEP_3_UTFNOTSUPPORTED2' => '',
'STEP_4_1_DATA_WAS_WRITTEN' => '',
'STEP_4_1_TITLE' => '',
'STEP_4_ADMIN_LOGIN_NAME' => '',
'STEP_4_ADMIN_PASS' => '',
'STEP_4_ADMIN_PASS_CONFIRM' => '',
'STEP_4_ADMIN_PASS_MINCHARS' => '',
'STEP_4_DESC' => '',
'STEP_4_SHOP_DIR' => '',
'STEP_4_SHOP_TMP_DIR' => '',
'STEP_4_SHOP_URL' => '',
'STEP_4_TITLE' => '',
'STEP_5_1_SERIAL_ADDED' => '',
'STEP_5_1_TITLE' => '',
'STEP_5_DESC' => '',
'STEP_5_LICENCE_DESC' => '',
'STEP_5_LICENCE_KEY' => '',
'STEP_5_TITLE' => '',
'STEP_6_DESC' => '',
'STEP_6_LINK_TO_SHOP' => '',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => '',
'STEP_6_TITLE' => '',
'STEP_6_TO_SHOP' => '',
'STEP_6_TO_SHOP_ADMIN' => '',
'TAB_0_DESC' => '',
'TAB_0_TITLE' => '',
'TAB_1_DESC' => '',
'TAB_1_TITLE' => '',
'TAB_2_DESC' => '',
'TAB_2_TITLE' => '',
'TAB_3_DESC' => '',
'TAB_3_TITLE' => '',
'TAB_4_DESC' => '',
'TAB_4_TITLE' => '',
'TAB_5_DESC' => '',
'TAB_5_TITLE' => '',
'TAB_6_DESC' => '',
'TAB_6_TITLE' => '',
'USE_DYNAMIC_PAGES' => '',
);
