<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (3431), alexraimondo (1), Phenix (202), vikapera (376)
 */

$sLangName  = "Français";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Il n\'existe aucune liste pour le moment. Pour en créer une nouvelle, cliquez',
'ADD_RECOMM_ADDRECOMMLINK2' => 'ici',
'allBrands' => 'All Brands',
'byBrand' => 'Par marque',
'byManufacturer' => 'Par marque',
'byVendor' => 'Par distributeur',
'DETAILS_ARTNUMBER' => 'Produit n°:',
'DETAILS_CHOOSEVARIANT' => 'Veuillez choisir une variante',
'DETAILS_LOCATOR_PRODUCT' => 'Produit',
'DETAILS_PLUSSHIPPING2' => 'coût de livraison.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Alerte Prix',
'DETAILS_VPE_MESSAGE_1' => 'Ce produit ne peut être commandé que par lot de',
'DETAILS_VPE_MESSAGE_2' => 'acheté.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Une invitation de',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'à visiter',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'à inviter.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Produit n°:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'AUCUN(E)',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'TVA sur frais de paiement',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Sera payé par:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'taxes en sus',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'taxes en sus',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Sera livré via',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Coût de livraison (HT):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'taxes en sus',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'taxes en sus',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Message:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>INFORMATIONS DE PAIEMENT DESACTIVEES</b> - Pour les réactiver, merci de changer email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Download your ordered files here.',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Hello',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Payment of the order is not yet complete.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Download links',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Art.No.:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Order No.:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'The order is shipped to:',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Product',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Product Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'review',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Your shipment tracking URL:',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'click here',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Please take a minute to rate our shop.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Your',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'Team',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Stock low',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Cordialement,',
'FOOTER_CATEGORIES' => 'CATEGORIES',
'FOOTER_DISTRIBUTORS' => 'DISTRIBUTEURS',
'FOOTER_INFORMATION' => 'INFORMATION',
'FOOTER_MANUFACTURERS' => 'MARQUES',
'FOOTER_SERVICES' => 'SERVICE',
'FORM_CONTACT_SEND' => 'Envoyer le mot de passe',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Confirmer le mot de passe:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Mot de passe oublié?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Prénom',
'FORM_PRICEALARM_SEND' => 'Envoyer',
'FORM_PRIVATESALES_INVITE_FROM' => 'De:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Bonjour, en navigant sur le site',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'aujourd\'hui, je suis tombé sur une offre qui pourrait t\'interresser. Pour consulter ce produit, cliques simplement sur le lien ci-après.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Envoyer l\'invitation',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Mot de passe de l\'expéditeur:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Titre',
'FORM_REGISTER_BILLINGADDRESS' => 'Adresse de facturation',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Veuillez renseigner l\'ensemble des données mentionnant le symbole <span class="req">*</span>)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'J\'ai bien été informé de mon',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'informé.',
'FORM_REGISTER_IAGREETOTERMS1' => 'J\'ai lu et accepte',
'FORM_REGISTER_IAGREETOTERMS3' => 'les a lu et approuvé.',
'FORM_SUGGEST_MESSAGE1' => 'Bonjour, je naviguais sur',
'FORM_SUGGEST_MESSAGE2' => 'aujourd\'hui et je suis tombé(e) sur quelque chose qui pourrait t\'intéresser. Cliques sur le lien ci-dessous pour accéder directement au produit.',
'FORM_USER_BILLINGADDRESS' => 'Adresse de facturation',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Confirmer le mot de passe:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Rechercher maintenant',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Bonjour, j\'ai créé une liste de envies sur',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => '. Je serai ravi que vous participiez à réaliser mes envies.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Erreur pendant l\'envoi - merci de vérifier votre adresse email.',
'fullDateFormat' => 'Y-m-d H:i:s',
'grid' => 'Grille',
'infogrid' => 'Double grille',
'line' => 'Ligne',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Merci de renseigner tous les champs avec une "*"!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => '*DECONNEXION*',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Enregistrer le nouveau mot de passe',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Créer un nouveau compte',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Information de facturation et de livraison',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Votre liste d\'envies à bien été envoyé aux destinataires suivants:',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'expédié!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Référence produit',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Votre bon d\'achat',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'a été refusé.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Sous total',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'TVA Frais additionnels',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% Montant',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'taxes en sus',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% Montant',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Raison',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'taxes en sus',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% Montant',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Sous total',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Somme des produits (TTC)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Somme des produits (HT)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'taxes en sus',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'taxes en sus',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Votre message:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Adresse de facturation',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Votre bon d\'achat',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'a été refusé.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Adresse de livraison',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Numéro du compte bancaire:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Merci de renseigner tous les champs correctement!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Currently we have no delivery method set up for this country.</p> <p>We are aiming to find a possible delivery method and we will inform you as soon as possible via e-mail about the result, including further information about delivery costs.</p> <p>If you agree to this procedure, please select "move on to next step"</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'TVA incl.',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Frais contre-remboursement',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'La protection des acheteurs Trusted Shops sécurise vos achats en ligne. J\'accepte le transfert et',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'l\'enregistrement',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'de mon adresse e-mail pour la protection des acheteurs Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Conditions',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'pour la protection des acheteurs.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Votre commande porte le n°:',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'registered with us.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Merci pour votre commande',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'dans',
'PAGE_CHECKOUT_USER' => 'Envoyer',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Un compte client permet à son détenteur:<br>- La gestion de ses adresses<br>- Le suivi des commandes<br>- L\'historique des commandes<br>- Les listes d\'envies<br> - Les listes de sélections<br>- L\'abonnement à la newsletter<br>- L\'accès aux offres spéciales',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Annuler',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'Aucun',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Merci.',
'PAGE_DETAILS_THANKYOUMESSAGE2' => 'pour votre commentaire.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Nous vous informerons dès que le prix atteindra votre prix',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br/><br/>Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Information about Cookies',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Merci.',
'PAGE_INFO_CONTACT_THANKYOU2' => 'Vous remercie pour vos commentaires.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Actualités de',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Ces produits sont dans la listes d\'envies de',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Si vous souhaitez faire plaisir, offrez-lui ces produits.',
'searchResult' => 'Résultats de la recherche pour "%s"',
'simpleDateFormat' => 'Y-m-d',
'usrRegistered' => 'L\'utilisateur sera enregistré après avoir fourni son mot de passe',
'view' => 'Vue',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Plus ...',
'WIDGET_LOGINBOX_LOGIN' => 'Connexion',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Détails du produit',
'WIDGET_SERVICES_GUESTBOOK' => 'Livre d\'or',
'WIDGET_SERVICES_HOME' => 'Accueil',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Plus d\'informations',
);
