<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2013
 * @version OXID eShop CE
 * @translators: jmatos (667), la bete (5), makolab (3214), marco (4), mart (139), pawelch (1660), topconcepts (209)
 */

$sLangName  = 'Polski';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Nie masz list ulubionych artykułów. Do założenia nowej listy',
'ADD_RECOMM_ADDRECOMMLINK2' => 'tutaj',
'allBrands' => 'Wszystkie marki',
'byBrand' => 'Marka/Producent',
'byManufacturer' => 'Marka/Producent',
'byVendor' => 'Dostawca',
'DETAILS_ARTNUMBER' => 'Artykuł Nr.:',
'DETAILS_CHOOSEVARIANT' => 'Proszę wybrać wariant',
'DETAILS_LOCATOR_PRODUCT' => 'Artykuł',
'DETAILS_PLUSSHIPPING2' => 'Koszty wysyłki.',
'DETAILS_PRICEALARM' => '<b>[!]</b> Alarm cenowy!',
'DETAILS_VPE_MESSAGE_1' => 'Ten artykuł dostępny tylko w opakowaniu po',
'DETAILS_VPE_MESSAGE_2' => 'sztuk.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Zaproszenie od',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'odwiedzić',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'odwiedzić.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Artykuł Nr.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'NIC',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Dodatek VAT',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Zapłacam przez:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'Plus VAT',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'Plus VAT',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Zakupy wysyłamy:',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Koszty wysyłki (netto):',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'Plus VAT',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'Plus VAT',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Wiadomość:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b>INFORMACJE O PŁATNOŚCI SĄ WYŁĄCZONE</b> - zmień ustawienia w pliku email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => 'Pobierz zamówione pliki tutaj .',
'EMAIL_SENDDOWNLOADS_GREETING' => 'Witaj',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => 'Płatność z zamówienia nie jest jeszcze zakończona.',
'EMAIL_SENDDOWNLOADS_SUBJECT' => 'Pobierz linki',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => 'Numer artykułu:',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => 'Nr zamówienia:',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => 'Zamówienie jest wysyłane do :',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => 'Produkt',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => 'Ocena produktu',
'EMAIL_SENDEDNOW_HTML_REVIEW' => 'recenzja',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => 'Twój URL śledzenia przesyłki :',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => 'kliknij tutaj',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => 'Proszę poświęć chwilę , aby ocenić nasz sklep.',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => 'Swój',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => 'zespół',
'EMAIL_STOCKREMINDER_SUBJECT' => 'Niska ilość w magazynie',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Serdeczne pozdrowienia',
'FOOTER_CATEGORIES' => 'KATEGORIE',
'FOOTER_DISTRIBUTORS' => 'DOSTAWCY',
'FOOTER_INFORMATION' => 'INFORMACJE',
'FOOTER_MANUFACTURERS' => 'MARKA',
'FOOTER_SERVICES' => 'SERVICE',
'FORM_CONTACT_SEND' => 'Wyślij wiadomość',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'powtórz hasło:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Zapomniałeś hasło?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Imię:',
'FORM_PRICEALARM_SEND' => 'Wyślij',
'FORM_PRIVATESALES_INVITE_FROM' => 'Od:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Witaj! Właśnie znalazłem interesujący sklep',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'dla ciebie. Kliknij na ten następny link',
'FORM_PRIVATESALES_INVITE_SEND' => 'Wyślij zaproszenie',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Adres e-mail nadawcy:',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Tytuł',
'FORM_REGISTER_BILLINGADDRESS' => 'Adres płatnika',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Pola zaznaczone <span class="fontred">*</span>to pola wymagane)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Informacje o',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'zostały przekazane.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Przeczytałem',
'FORM_REGISTER_IAGREETOTERMS3' => 'i zgadzam się z regulaminem sklepu.',
'FORM_SUGGEST_MESSAGE1' => 'Witaj',
'FORM_SUGGEST_MESSAGE2' => 'znalazłem dla ciebie! Kliknij na ten link',
'FORM_USER_BILLINGADDRESS' => 'Adres płatnika',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'powtórz hasło:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Szukaj',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Witaj',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => 'listę życzeń. Byłoby wspaniałe',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'błąd w wysyłce – sprawdź adres e-mail.',
'fullDateFormat' => 'd.m.Y H:i:s',
'grid' => 'Galeria',
'infogrid' => 'Galeria z kolumnami',
'line' => 'Listy',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Wypełnij wszystkie pola zaznaczone * !',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'LOGOUT',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Zapisz nowe hasło',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Zarejestruj się',
'PAGE_ACCOUNT_USER_USERTITLE' => 'ustawienia faktury i dostawy',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Lista życzeń dla',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'została wysłana!',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Artykuł Nr.:',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'twój bon towarowy',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'został odrzucony.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Suma pozycji:',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Dodatek VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% suma:',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'Plus VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% suma:',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'powód',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'Plus VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% suma:',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Suma pozycji:',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Suma pozycji (brutto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Suma pozycji (netto)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'Plus VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'Plus VAT',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Twoja wiadomość:',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Adres płatnika',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Twój bon towarowy',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'nie został przyjęty.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Adres do wysyłki',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'numer konta:',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Wypełnij wszystkie pola',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p>Brak przesyłki do tego kraju.</p><p>Postaramy się znaleźć sposoby dostawy i powiadomimy o kosztach wysyłki.</p><p>Jeśli się z tym zgadzasz, kliknij na „następny krok“.</p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'inkl. VAT',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'Opłata przy dostawie',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'Ochrona Trusted Shops zabezpiecza zakupy w sklepach internetowych. Zgadzam się z',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'przesyłką i zapisaniem mojego adresu e-mail',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'do ochrony przez Trusted Shops.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Warunki',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'dla ochrony klientów.',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Twoje zamówienie jest u nas pod numerem',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'zarejestrowane.',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Dziękujemy za zamówienie',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'w każdej chwili możesz się wypisać z newsletter bez dodatkowych opłat.',
'PAGE_CHECKOUT_USER' => 'wyślij',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Własne konto klienta ma następujące zalety:<br>                                                                      - zarządzanie adresami dostawy<br>                                                                      - analiza zamówień<br>                                                                      - historia zamówień<br>                                                                      - prywatny schowek<br>                                                                      - prywatna lista życzeń<br>                                                                      - ustawienia newslettera<br>                                                                      - promocje i rabaty',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Przerwać',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'NIC',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Dziękujemy za wiadomość dla',
'PAGE_DETAILS_THANKYOUMESSAGE2' => '.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Jak cena spadnie poniżej',
'PAGE_DETAILS_THANKYOUMESSAGE4' => 'dostaniesz wiadomość od nas.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => 'Podjąłeś decyzje o nieakceptowaniu ciasteczek pochodzących z naszego sklepu. Ciasteczka zostały usunięte. Możesz wyłączyć użycie ciasteczek w ustawieniach Twojej przeglądarki i używać naszego sklepu z pewnymi ograniczeniami. Możesz również używać naszego sklepu bez ograniczeń bez zmiany ustawień przeglądarki.<br/><br/>Informacje o ciasteczkach na Wikipedia: <a href="http://pl.wikipedia.org/wiki/Ciasteczko"><strong>http://pl.wikipedia.org/wiki/Ciasteczko</strong></a>',
'PAGE_INFO_CLEARCOOKIE_TITLE' => 'Informacje o ciasteczkach',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Dziękujemy za wiadomość do',
'PAGE_INFO_CONTACT_THANKYOU2' => '.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Nowości',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Ten artykuł życzy sobie',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => 'Jeśli chcesz jej/jemu sprawić niespodziankę',
'searchResult' => 'Rezultaty wyszukiwania dla "% s"',
'simpleDateFormat' => 'd.m.Y',
'usrRegistered' => 'Użytkownik zostanie zarejestrowany jeśli wprowadzi swoje hasło',
'view' => 'Przegląd',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Więcej ...',
'WIDGET_LOGINBOX_LOGIN' => 'Logowanie',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Szczegóły produktu',
'WIDGET_SERVICES_GUESTBOOK' => 'księga gości',
'WIDGET_SERVICES_HOME' => 'Home',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'dalsze informacje',
);
