<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (28), pianoservis (941)
 */

$sLangName  = "Українська";

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Списків Listmania ще не створено. Щоб створити новий, натисніть',
'ADD_RECOMM_ADDRECOMMLINK2' => 'тут',
'allBrands' => 'Всі бренди',
'byBrand' => 'По бренду/виробнику',
'byManufacturer' => 'По бренду/виробнику',
'byVendor' => 'По дистриб\'ютору',
'DETAILS_ARTNUMBER' => 'Арт. номер',
'DETAILS_CHOOSEVARIANT' => 'Будь ласка, виберіть варіант',
'DETAILS_LOCATOR_PRODUCT' => 'Товар',
'DETAILS_PLUSSHIPPING2' => 'доставки',
'DETAILS_PRICEALARM' => '<b>[!]</b> Повідомити про знижку',
'DETAILS_VPE_MESSAGE_1' => 'Цей товар можна замовити тільки з',
'DETAILS_VPE_MESSAGE_2' => 'шт.',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Запрошення від',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'Відвідати',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => 'відвідати.',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Артикул:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'НІ',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'Надбавка способу розрахунку',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Спосіб оплати:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'плюс ПДВ',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'плюс ПДВ',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'Спосіб доставки:',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Доставка (нетто) :',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'плюс ПДВ',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'плюс ПДВ',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Повідомлення:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '<b> ІНФОРМАЦІЯ ПРО ОПЛАТУ ВІДКЛЮЧЕНА </ b> - щоб підключити інформацію про оплату, змініть email_order_owner_html.tpl.',
'EMAIL_SENDDOWNLOADS_DOWNLOADS_DESC' => '',
'EMAIL_SENDDOWNLOADS_GREETING' => '',
'EMAIL_SENDDOWNLOADS_PAYMENT_PENDING' => '',
'EMAIL_SENDDOWNLOADS_SUBJECT' => '',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER' => '',
'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCT' => '',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING' => '',
'EMAIL_SENDEDNOW_HTML_REVIEW' => '',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING' => '',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL' => '',
'EMAIL_SENDEDNOW_HTML_TS_RATINGS_RATEUS' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM1' => '',
'EMAIL_SENDEDNOW_HTML_YUORTEAM2' => '',
'EMAIL_STOCKREMINDER_SUBJECT' => '',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Вітаю,',
'FOOTER_CATEGORIES' => 'Категорії',
'FOOTER_DISTRIBUTORS' => 'Постачальники',
'FOOTER_INFORMATION' => 'Інформація',
'FOOTER_MANUFACTURERS' => 'Бренди',
'FOOTER_SERVICES' => 'Послуги',
'FORM_CONTACT_SEND' => 'Відправити повідомлення',
'FORM_FIELDSET_USER_ACCOUNT_CONFIRMPWD' => 'Підтвердити пароль:',
'FORM_LOGIN_ACCOUNT_FORGOTPWD' => 'Забули пароль?',
'FORM_NEWSLETTER_FIRSTNAME' => 'Ім\'я',
'FORM_PRICEALARM_SEND' => 'відправити',
'FORM_PRIVATESALES_INVITE_FROM' => 'Від:',
'FORM_PRIVATESALES_INVITE_MESSAGE1' => 'Привіт! Сьогодні я знайшов цікавий магазин',
'FORM_PRIVATESALES_INVITE_MESSAGE2' => 'для тебе! Просто натисни посилання внизу і перейдеш прямо на сайт магазину.',
'FORM_PRIVATESALES_INVITE_SEND' => 'Відправити запрошення',
'FORM_PRIVATESALES_INVITE_SENDEREMAIL' => 'Електронна адреса відправника',
'FORM_RECOMMENDATION_EDIT_LISTTITLE' => 'Заголовок',
'FORM_REGISTER_BILLINGADDRESS' => 'Розрахункова адреса',
'FORM_REGISTER_COMPLETEMARKEDFIELDS' => '(Будь ласка, заповніть всі поля, відмічені жирним шрифтом)',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL1' => 'Я був поінформований що',
'FORM_REGISTER_IAGREETORIGHTOFWITHDRAWAL3' => 'і погоджуюсь із умовами.',
'FORM_REGISTER_IAGREETOTERMS1' => 'Я прочитав',
'FORM_REGISTER_IAGREETOTERMS3' => 'і погоджуюсь',
'FORM_SUGGEST_MESSAGE1' => 'Привіт! Сьогодні я знайшов цікавий магазин',
'FORM_SUGGEST_MESSAGE2' => 'для тебе! Просто натисни посилання внизу і перейдеш прямо на сайт магазину.',
'FORM_USER_BILLINGADDRESS' => 'Розрахункова адреса',
'FORM_USER_PASSWORD_CONFIRMPASSWORD' => 'Підтвердити пароль:',
'FORM_WISHLIST_SEARCH_SEARCH' => 'Шукати',
'FORM_WISHLIST_SUGGEST_BUYFORME1' => 'Привіт, я склав собі тут',
'FORM_WISHLIST_SUGGEST_BUYFORME2' => 'список бажань. Було б чудово отримати від тебе щось з цього списку.',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Помилка відправки. Будь ласка, перевірте Ваш E-Mail',
'fullDateFormat' => 'd M Y H:i:s',
'grid' => 'Галерея',
'infogrid' => 'Показати галерею в дві колонки',
'line' => 'Список',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Будь ласка, заповніть усі поля вірно!',
'PAGE_ACCOUNT_DASHBOARD_LOGOUT' => 'Вийти',
'PAGE_ACCOUNT_FORGOTPWD_UPDATEPASSWORD' => 'Зберегти новий пароль',
'PAGE_ACCOUNT_REGISTER_OPENACCOUNT' => 'Створити новий аккаунт',
'PAGE_ACCOUNT_USER_USERTITLE' => 'Вибір способу оплати і доставки',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Ваш список бажань був успішно відправлений',
'PAGE_ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'Дякую.',
'PAGE_CHECKOUT_BASKETCONTENTS_ARTNOMBER' => 'Арт. номер',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED1' => 'Ваш купон',
'PAGE_CHECKOUT_BASKETCONTENTS_COUPONNOTACCEPTED2' => 'не було прийнято.',
'PAGE_CHECKOUT_BASKETCONTENTS_GRANDTOTAL' => 'Загальна сума',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX1' => 'Сума з ПДВ',
'PAGE_CHECKOUT_BASKETCONTENTS_PAYMENTTAX2' => '% від вартості',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX1' => 'плюс ПДВ',
'PAGE_CHECKOUT_BASKETCONTENTS_PLUSTAX2' => '% від вартості',
'PAGE_CHECKOUT_BASKETCONTENTS_REASON' => 'Причина',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX1' => 'плюс ПДВ',
'PAGE_CHECKOUT_BASKETCONTENTS_TAX2' => '% від вартості',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTAL' => 'Загальна сума',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALGROSS' => 'Сума (брутто)',
'PAGE_CHECKOUT_BASKETCONTENTS_TOTALNET' => 'Сума (нетто)',
'PAGE_CHECKOUT_BASKETCONTENTS_TSPROTECTIONCHARGETAX1' => 'плюс ПДВ',
'PAGE_CHECKOUT_BASKETCONTENTS_WRAPPINGTAX1' => 'плюс ПДВ',
'PAGE_CHECKOUT_BASKETCONTENTS_YOURMESSAGE' => 'Ваше повідомлення',
'PAGE_CHECKOUT_ORDER_BILLINGADDRESS' => 'Розрахункова адреса',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED1' => 'Ваш купон',
'PAGE_CHECKOUT_ORDER_COUPONNOTACCEPTED2' => 'не було прийнято.',
'PAGE_CHECKOUT_ORDER_SHIPPINGADDRESS' => 'Адреса доставки',
'PAGE_CHECKOUT_PAYMENT_ACCOUNTNUMBER' => 'Номер аккаунта',
'PAGE_CHECKOUT_PAYMENT_COMLETEALLFIELDS' => 'Будь ласка, заповніть усі поля!',
'PAGE_CHECKOUT_PAYMENT_EMPTY_TEXT' => '<p> На даний момент ми не змогли визначити спосіб доставки до вказаного місця. </ p> <p> Ми спробуємо знайти варіант доставки і повідомимо Вам про її вартість. </ p> <p> Якщо Ви погоджуєтесь, натисніть "Перейти до наступного кроку ". </ p>',
'PAGE_CHECKOUT_PAYMENT_INCLUDEVAT' => 'з ПДВ',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE1' => 'включно',
'PAGE_CHECKOUT_PAYMENT_PLUSCODCHARGE2' => 'тариф оплати післяплатою',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT' => 'Ми гарантуємо нашим покупцям безпечне вчинення он-лайн покупок. З умовами передачі',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT2' => 'і збереження',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT3' => 'моєї електронної адреси, а також з умовами безпечного здійснення покупок згоден.',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT4' => 'Умови',
'PAGE_CHECKOUT_PAYMENT_TSPROTECTIONTEXT5' => 'захист покупців',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO1' => 'Ваше замовлення під номером',
'PAGE_CHECKOUT_THANKYOU_REGISTEREDYOUORDERNO2' => 'зареєстровано у нас',
'PAGE_CHECKOUT_THANKYOU_THANKYOU1' => 'Дякуємо за Ваше замовлення',
'PAGE_CHECKOUT_THANKYOU_THANKYOU2' => 'в',
'PAGE_CHECKOUT_USER' => '',
'PAGE_CHECKOUT_USER_OPTION_REGISTRATION_DESCRIPTION' => 'Особистий аккаунт надає Вам наступні переваги: <br> - управління адресами доставки <br> - Контроль статусу доставки <br> - Історія замовлень <br> - Особистий кошик <br> - Особистий список бажань <br> - Керування розсилкою <br> - акції та знижки',
'PAGE_CHECKOUT_WRAPPING_CANCEL' => 'Відміна',
'PAGE_CHECKOUT_WRAPPING_NONE' => 'Ні',
'PAGE_DETAILS_THANKYOUMESSAGE1' => 'Дякуємо за Ваше повідомлення',
'PAGE_DETAILS_THANKYOUMESSAGE2' => '.',
'PAGE_DETAILS_THANKYOUMESSAGE3' => 'Ви отримаєте наше повідомлення, як тільки ціна зменшиться до',
'PAGE_DETAILS_THANKYOUMESSAGE4' => '.',
'PAGE_INFO_CLEARCOOKIE_CONTENT' => '',
'PAGE_INFO_CLEARCOOKIE_TITLE' => '',
'PAGE_INFO_CONTACT_THANKYOU1' => 'Дякуємо за Ваше повідомлення',
'PAGE_INFO_CONTACT_THANKYOU2' => '.',
'PAGE_INFO_NEWS_LATESTNEWSBY' => 'Нове',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS1' => 'Цей товар знаходиться в Списку бажань у',
'PAGE_WISHLIST_PRODUCTS_PRODUCTS2' => '. Якщо Ви хочете принести йому (їй) радість, купіть цей товвар.',
'searchResult' => 'результати пошуку по запиту "%s"',
'simpleDateFormat' => 'd.m.Y',
'usrRegistered' => 'Вкажіть Ваш пароль користувача для реєстрації',
'view' => 'Дивитись',
'WIDGET_FOOTER_MANUFACTURERS_MORE' => 'Далі...',
'WIDGET_LOGINBOX_LOGIN' => 'Логін',
'WIDGET_PRODUCT_PRODUCT_DETAILS' => 'Докладніше про товар',
'WIDGET_SERVICES_GUESTBOOK' => 'Відгуки',
'WIDGET_SERVICES_HOME' => 'На стартову сторінку',
'WIDGET_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'Більше інформації',
);
