<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: admin (1341), compisat (26), marco (1026), muslimukas (4), Natalia I (37), pianoservis (4), riefi (9), unicum (35), vanilla thunder (35)
 */

$sLangName  = 'Русский';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ATTENTION' => 'Пожалуйста, обратите внимание',
'BUTTON_BEGIN_INSTALL' => 'Начать установку',
'BUTTON_DB_INSTALL' => 'Создать базу данных сейчас',
'BUTTON_LICENCE' => 'Дальше',
'BUTTON_PROCEED_INSTALL' => 'Начать установку',
'BUTTON_RADIO_INSTALL_DB_DEMO' => 'Установить демо-данные',
'BUTTON_RADIO_LICENCE_ACCEPT' => 'Я принимаю условия лицензионного соглашения.',
'BUTTON_RADIO_LICENCE_NOT_ACCEPT' => 'Я не принимаю условия лицензионного соглашения.',
'BUTTON_RADIO_NOT_INSTALL_DB_DEMO' => '<strong>Не</strong> установить демо-данные',
'BUTTON_START_INSTALL' => 'Снова начать установку',
'BUTTON_WRITE_DATA' => 'Сохранить базу данных сейчас',
'BUTTON_WRITE_LICENCE' => 'Сохранить лицензионный ключ',
'ERROR_BAD_DEMODATA' => 'ОШИБКА: проблема со следующей SQL-командой:',
'ERROR_BAD_SERIAL_NUMBER' => 'ОШИБКА: серийный номер неверный!',
'ERROR_BAD_SQL' => 'ОШИБКА: (таблицы) проблемы со следующими SQL-командами:',
'ERROR_CONFIG_FILE_IS_NOT_WRITABLE' => 'ОШИБКА: %s/config.inc.php невозможно редактировать!',
'ERROR_COULD_NOT_CREATE_DB' => 'ОШИБКА: база данный %s не существует, также ее невозможно создать!',
'ERROR_COULD_NOT_FIND_FILE' => 'Установщик не смог найти файл "%s"',
'ERROR_COULD_NOT_OPEN_CONFIG_FILE' => 'Невозможно открыть config.inc.php. Пожалуйста, прочтите FAQ или форум или свяжитесь со службой поддержки OXID.',
'ERROR_COULD_NOT_READ_FILE' => 'Установщик не смог открыть файл "%s"!',
'ERROR_COULD_NOT_WRITE_TO_FILE' => 'Установщик не смог отредактировать файл "%s"!',
'ERROR_DB_ALREADY_EXISTS' => 'ОШИБКА: возможно в базе данных уже существует база данных OXID. Пожалуйста, удалите ее.',
'ERROR_DB_CONNECT' => 'ОШИБКА: невозможно соединиться с базой данных!',
'ERROR_FILL_ALL_FIELDS' => 'ОШИБКА: пожалуйста, заполните все обязательные поля!',
'ERROR_MYSQL_VERSION_DOES_NOT_FIT_REQUIREMENTS' => 'Версия MySQL не соответствует системным требованиям.',
'ERROR_NOT_AVAILABLE' => 'ОШИБКА: %s не существует!',
'ERROR_NOT_WRITABLE' => 'ОШИБКА: %s невозможно редактировать!',
'ERROR_OPENING_SQL_FILE' => 'ОШИБКА: невозможно открыть SQL-файл %s!',
'ERROR_PASSWORDS_DO_NOT_MATCH' => 'Пароли не совпадают',
'ERROR_PASSWORD_TOO_SHORT' => 'Пароль слишком короткий',
'ERROR_SETUP_CANCELLED' => 'Установка прервана, так как Вы не согласились с условиями лицензионного соглашения.',
'ERROR_USER_NAME_DOES_NOT_MATCH_PATTERN' => 'Пожалуйста, укажите существующий e-mail!',
'ERROR_VIEWS_CANT_CREATE' => 'ОШИБКА: невозможно создать Views. Пожалуйста, проверьте Ваши права пользователя для базы данных.',
'ERROR_VIEWS_CANT_DROP' => 'ОШИБКА: невозможно удалить Views. Пожалуйста, проверьте Ваши права пользователя для базы данных.',
'ERROR_VIEWS_CANT_SELECT' => 'ОШИБКА: нет доступа к Views. Пожалуйста, проверьте Ваши права пользователя для базы данных.',
'FOOTER_OXID_ESALES' => '© OXID eSales AG 2003 - Y',
'HEADER_META_MAIN_TITLE' => 'OXID eShop Мастер установки',
'HEADER_TEXT_SETUP_NOT_RUNS_AUTOMATICLY' => 'If setup does not continue in a few seconds, please click ',
'HERE' => 'здесь',
'LOAD_DYN_CONTENT_NOTICE' => '<p>If checkbox is set, you will see an additional menu in the admin area of your OXID eShop.</p><p>In that menu you get further information about eCommerce services like Google product search.</p> <p>You can change these settings at any time.</p>',
'MOD_ALLOW_URL_FOPEN' => 'allow_url_fopen or fsockopen to port 80',
'MOD_BC_MATH' => 'BCMath',
'MOD_BUG53632' => 'Possible issues on server due to PHP Bugs',
'MOD_CURL' => 'cURL',
'MOD_FILE_UPLOADS' => 'File uploads are enabled (file_uploads)',
'MOD_GD_INFO' => 'GDlib v2 [v1] incl. JPEG support',
'MOD_INI_SET' => 'ini_set allowed',
'MOD_I_CONV' => 'ICONV',
'MOD_J_SON' => 'JSON',
'MOD_LIB_XML2' => 'LIB XML2',
'MOD_MB_STRING' => 'mbstring',
'MOD_MEMORY_LIMIT' => 'PHP Memory limit (min. 14MB, 30MB recommended)',
'MOD_MOD_REWRITE' => 'Apache mod_rewrite module',
'MOD_MYSQL_CONNECT' => 'MySQL client connector for MySQL 5',
'MOD_OPEN_SSL' => 'OpenSSL',
'MOD_PHP4_COMPAT' => 'Zend compatibility mode must be off',
'MOD_PHP_CONFIG' => 'PHP configuration',
'MOD_PHP_EXTENNSIONS' => 'PHP extensions',
'MOD_PHP_VERSION' => 'PHP version at least 5.2.10',
'MOD_PHP_XML' => 'DOM',
'MOD_REGISTER_GLOBALS' => 'register_globals must be off',
'MOD_REQUEST_URI' => 'REQUEST_URI set',
'MOD_SERVER_CONFIG' => 'Server configuration',
'MOD_SERVER_PERMISSIONS' => 'Files/folders access rights',
'MOD_SESSION_AUTOSTART' => 'session.auto_start must be off',
'MOD_SOAP' => 'SOAP',
'MOD_TOKENIZER' => 'Tokenizer',
'MOD_UNICODE_SUPPORT' => 'UTF-8 support',
'MOD_ZEND_OPTIMIZER' => 'Zend Optimizer or Zend Guard Loader installed',
'MOD_ZEND_PLATFORM_OR_SERVER' => 'Zend Platform or Zend Server installed',
'PRIVACY_POLICY' => 'privacy statements',
'SELECT_COUNTRY_LANG' => 'Please choose your country',
'SELECT_DELIVERY_COUNTRY' => 'Main delivery country',
'SELECT_DELIVERY_COUNTRY_HINT' => 'If needed, activate easily more delivery countries in admin.',
'SELECT_PLEASE_CHOOSE' => 'Please choose',
'SELECT_SETUP_LANG' => 'Installation language',
'SELECT_SETUP_LANG_HINT' => '. If needed, activate easily more languages in admin.',
'SELECT_SETUP_LANG_SUBMIT' => 'Select',
'SELECT_SHOP_LANG' => 'Shop language',
'SELECT_SHOP_LANG_HINT' => 'If needed, activate easily more languages in admin.',
'SELECT_SHOP_LOCATION' => 'Your market',
'SELECT_SHOP_LOCATION_HINT' => 'Please choose the market to which shop is focused. According to it, additional eCommerce Services will be loaded from OXID server, if you allow that.',
'SETUP_CONFIG_PERMISSIONS' => 'Due to security reasons put your config.inc.php file to read-only mode!',
'SETUP_DIR_DELETE_NOTICE' => 'Due to security reasons remove setup directory if not yet done during installation.',
'STEP_0_DESC' => 'In this step we check if your system fits the requirements:',
'STEP_0_ERROR_TEXT' => 'Your system does not fit system requirements',
'STEP_0_ERROR_URL' => 'http://www.oxid-esales.com/en/products/community-edition/system-requirements',
'STEP_0_TEXT' => '<ul class="req"><li class="pass"> - Your system fits the requirement.</li><li class="pmin"> - The requirement is not or only partly fit. The OXID eShop will work anyway and can be installed..</li><li class="fail"> - Your system doesn\'t fit the requirement. The OXID eShop will not work without it and cannot be installed.</li><li class="null"> - The requirement could  not be checked.</ul>',
'STEP_0_TITLE' => 'System requirements check',
'STEP_1_ADDRESS' => 'OXID eSales AG<br>
                                                    Bertoldstr. 48<br>
                                                    79098 Freiburg<br>
                                                    Deutschland<br>',
'STEP_1_CHECK_UPDATES' => 'Check for available updates regularly',
'STEP_1_DESC' => 'Welcome to installation wizard of OXID eShop',
'STEP_1_TEXT' => 'Please read carefully the following instructions to guarantee a smooth installation.
                                                    Wishes for best success in using your OXID eShop by',
'STEP_1_TITLE' => 'Welcome',
'STEP_2_TITLE' => 'License conditions',
'STEP_3_1_CREATING_TABLES' => 'Creating tables, applying data ...',
'STEP_3_1_DB_CONNECT_IS_OK' => 'Database connection successfully tested ...',
'STEP_3_1_DB_CREATE_IS_OK' => 'Database %s successfully created ...',
'STEP_3_1_TITLE' => 'Database - being created ...',
'STEP_3_2_CONTINUE_INSTALL_OVER_EXISTING_DB' => 'If you want to overwrite all existing data and install anyway click ',
'STEP_3_2_CREATING_DATA' => 'Database successfully created. Please wait ...',
'STEP_3_2_TITLE' => 'Database - tables are beeing created ...',
'STEP_3_CREATE_DB_WHEN_NO_DB_FOUND' => 'If database does not exist, it\'s going to be created',
'STEP_3_DB_DATABSE_NAME' => 'Database name',
'STEP_3_DB_DEMODATA' => 'Demodata',
'STEP_3_DB_HOSTNAME' => 'Database hostname or IP',
'STEP_3_DB_PASSWORD' => 'Database password',
'STEP_3_DB_PASSWORD_SHOW' => 'Show password',
'STEP_3_DB_USER_NAME' => 'Database username',
'STEP_3_DESC' => 'Database is going to be created and needed tables are written. Please provide some information:',
'STEP_3_TITLE' => 'Database',
'STEP_3_UTFINFO' => 'UTF-8 character encoding provides better support for special chars than other character encodings. This is particulary important for multilingual eShops. However, UTF-8 is slightly slower than the standard encoding (ISO 8859-15). <br /> If you plan to provide your eShop in many different languages, you should use UTF-8. If you just want to provide a few languages using related symbol sets (e. g. English, German, French), you don\'t need UTF-8.',
'STEP_3_UTFMODE' => 'Use UTF-8 character encoding',
'STEP_3_UTFNOTSUPPORTED' => 'The OXID eShop cannot operate in UTF-8 mode, due to:',
'STEP_3_UTFNOTSUPPORTED1' => ' missing mbstring PHP module',
'STEP_3_UTFNOTSUPPORTED2' => ' installed PCRE does not support UTF-8',
'STEP_4_1_DATA_WAS_WRITTEN' => 'Check and writing data successful. Please wait ...',
'STEP_4_1_TITLE' => 'Directories - being created ...',
'STEP_4_ADMIN_LOGIN_NAME' => 'Administrator e-mail (used as login name)',
'STEP_4_ADMIN_PASS' => 'Administrator password',
'STEP_4_ADMIN_PASS_CONFIRM' => 'Confirm Administrator password',
'STEP_4_ADMIN_PASS_MINCHARS' => 'freely selectable, min. 6 chars',
'STEP_4_DESC' => 'Please provide neccesary data for running OXID eShop:',
'STEP_4_SHOP_DIR' => 'Directory for OXID eShop',
'STEP_4_SHOP_TMP_DIR' => 'Directory for temporary data',
'STEP_4_SHOP_URL' => 'Shop URL',
'STEP_4_TITLE' => 'Setting up OXID eShop directories and URL',
'STEP_5_1_SERIAL_ADDED' => 'License key successfully saved. Please wait ...',
'STEP_5_1_TITLE' => 'License key is being inserted ...',
'STEP_5_DESC' => 'Please confirm license key:',
'STEP_5_LICENCE_DESC' => 'The provided key is valid for 30 days. After this period all of your changes remain if you insert a valid license key.',
'STEP_5_LICENCE_KEY' => 'License key',
'STEP_5_TITLE' => 'OXID eShop license',
'STEP_6_DESC' => 'Your OXID eShop has been installed successfully.',
'STEP_6_LINK_TO_SHOP' => 'Continue to your OXID eShop',
'STEP_6_LINK_TO_SHOP_ADMIN_AREA' => 'Continue to your OXID eShop admin interface',
'STEP_6_TITLE' => 'OXID eShop successfully installed',
'STEP_6_TO_SHOP' => 'To Shop',
'STEP_6_TO_SHOP_ADMIN' => 'To admin interface',
'TAB_0_DESC' => 'Checking if your system fits the requirements',
'TAB_0_TITLE' => 'System Requirements',
'TAB_1_DESC' => 'Welcome to OXID eShop installation wizard',
'TAB_1_TITLE' => 'Welcome',
'TAB_2_DESC' => 'Confirm license conditions',
'TAB_2_TITLE' => 'License conditions',
'TAB_3_DESC' => 'Test database connection, building tables',
'TAB_3_TITLE' => 'Database',
'TAB_4_DESC' => 'Configuring directories and selecting admin login',
'TAB_4_TITLE' => 'Directory & login',
'TAB_5_DESC' => 'Примените лицензионный ключ',
'TAB_5_TITLE' => 'лицензия',
'TAB_6_DESC' => 'установка прошла успешно',
'TAB_6_TITLE' => 'финиш',
'USE_DYNAMIC_PAGES' => 'To increase your business success get additional information from OXID\'s server. You find more information in our ',
);
